// Command walkgen writes ../walk_gen.go: the two tree walks, Walk and
// WalkTok, as one type switch over crefactor/cc's node types instead of
// reflection.  It reads cc's source with go/parser: every struct type with a
// Position method on its pointer is a node, and its exported fields are
// visited in declaration order -- a Token, a pointer to a node, or an
// interface -- which is the order and the choice reflection makes
// (fieldsOf).  TestWalkGen holds the two to each other.
//
//	go generate ./ccwalk
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type field struct {
	name string
	kind byte // t token, p pointer to a node, i interface
}

func main() {
	dir := filepath.Join("..", "cc")
	fset := token.NewFileSet()
	names0, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		log.Fatal(err)
	}
	var files []*ast.File
	for _, nm := range names0 {
		if strings.HasSuffix(nm, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, nm, nil, 0)
		if err != nil {
			log.Fatal(err)
		}
		files = append(files, f)
	}
	structs := map[string]*ast.StructType{}
	ifaces := map[string]bool{}
	nodes := map[string]bool{} // has Position() on *T
	for _, f := range files {
		for _, d := range f.Decls {
			switch d := d.(type) {
			case *ast.GenDecl:
				for _, s := range d.Specs {
					ts, ok := s.(*ast.TypeSpec)
					if !ok || ts.TypeParams != nil {
						continue
					}
					switch t := ts.Type.(type) {
					case *ast.StructType:
						structs[ts.Name.Name] = t
					case *ast.InterfaceType:
						ifaces[ts.Name.Name] = true
					}
				}
			case *ast.FuncDecl:
				if d.Recv == nil || d.Name.Name != "Position" || len(d.Recv.List) != 1 {
					continue
				}
				if st, ok := d.Recv.List[0].Type.(*ast.StarExpr); ok {
					if id, ok := st.X.(*ast.Ident); ok {
						nodes[id.Name] = true
					}
				}
			}
		}
	}
	var names []string
	for n := range nodes {
		if structs[n] != nil && ast.IsExported(n) {
			names = append(names, n)
		}
	}
	sort.Strings(names)
	fieldsOf := func(n string) []field {
		var out []field
		for _, fl := range structs[n].Fields.List {
			if len(fl.Names) == 0 {
				continue // embedded: every one in cc is unexported
			}
			var k byte
			switch t := fl.Type.(type) {
			case *ast.Ident:
				switch {
				case t.Name == "Token":
					k = 't'
				case ifaces[t.Name]:
					k = 'i'
				}
			case *ast.StarExpr:
				if id, ok := t.X.(*ast.Ident); ok && nodes[id.Name] {
					k = 'p'
				}
			}
			if k == 0 {
				continue
			}
			for _, nm := range fl.Names {
				if ast.IsExported(nm.Name) {
					out = append(out, field{nm.Name, k})
				}
			}
		}
		return out
	}

	var b bytes.Buffer
	b.WriteString(`// Code generated by walkgen; DO NOT EDIT.

package ccwalk

import "github.com/arbace/go-whim/crefactor/cc"

// genFields is, per node type, the fields the generated walks visit, as
// "name:kind" -- for TestWalkGen to hold against reflection's fieldsOf.
var genFields = map[string][]string{
`)
	for _, n := range names {
		var fs []string
		for _, f := range fieldsOf(n) {
			fs = append(fs, fmt.Sprintf("%q", f.name+":"+string(f.kind)))
		}
		fmt.Fprintf(&b, "\t%q: {%s},\n", n, strings.Join(fs, ", "))
	}
	b.WriteString("}\n\n")

	b.WriteString(`// walk calls f on every node under n, n included, in source order, and does
// not descend below a node f returns false for.
func Walk(n cc.Node, f func(cc.Node) bool) {
	switch x := n.(type) {
	case nil:
		return
`)
	for _, n := range names {
		fmt.Fprintf(&b, "\tcase *cc.%s:\n\t\tif x == nil || !f(x) {\n\t\t\treturn\n\t\t}\n", n)
		for _, f := range fieldsOf(n) {
			switch f.kind {
			case 'p':
				fmt.Fprintf(&b, "\t\tif x.%s != nil {\n\t\t\tWalk(x.%s, f)\n\t\t}\n", f.name, f.name)
			case 'i':
				fmt.Fprintf(&b, "\t\tif y, ok := any(x.%s).(cc.Node); ok {\n\t\t\tWalk(y, f)\n\t\t}\n", f.name)
			}
		}
	}
	b.WriteString(`	default:
		walkReflect(n, f)
	}
}

// WalkTok calls f on every token under n, in field order.
func WalkTok(n cc.Node, f func(cc.Token)) {
	switch x := n.(type) {
	case nil:
		return
`)
	for _, n := range names {
		fmt.Fprintf(&b, "\tcase *cc.%s:\n\t\tif x == nil {\n\t\t\treturn\n\t\t}\n", n)
		for _, f := range fieldsOf(n) {
			switch f.kind {
			case 't':
				fmt.Fprintf(&b, "\t\tf(x.%s)\n", f.name)
			case 'p':
				fmt.Fprintf(&b, "\t\tif x.%s != nil {\n\t\t\tWalkTok(x.%s, f)\n\t\t}\n", f.name, f.name)
			case 'i':
				fmt.Fprintf(&b, "\t\tif y, ok := any(x.%s).(cc.Node); ok {\n\t\t\tWalkTok(y, f)\n\t\t}\n", f.name)
			}
		}
	}
	b.WriteString(`	default:
		walkTokReflect(n, f)
	}
}
`)
	src, err := format.Source(b.Bytes())
	if err != nil {
		os.WriteFile("walk_gen.go.bad", b.Bytes(), 0o644)
		log.Fatal(err)
	}
	if err := os.WriteFile("walk_gen.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
