package p004d

// The multi-line literals /root/.claude/jobs/107d6bd5/tmp/w71.sh matches on, EXTRACTED from the phase's
// heredoc by tools/gocmp/genlits.py rather than retyped.  They carry BLANK
// LINES, which a filtered read of a phase program does not show, and a
// literal that is 90%% right matches nothing.  See that tool for the
// measurement.
const (
	w4dAddrPair1     = "                case ADDR_LOADED_BUFFERS:\n                    {\n                        buf_T *buf = firstbuf;\n                        while (buf->b_next != nullptr && buf->b_ml.ml_mfp == nullptr)\n                        {\n                            buf = buf->b_next;\n                        }\n                        eap->line1 = buf->b_fnum;\n                        buf = lastbuf;\n                        while (buf->b_prev != nullptr && buf->b_ml.ml_mfp == nullptr)\n                        {\n                            buf = buf->b_prev;\n                        }\n                        eap->line2 = buf->b_fnum;\n                        break;\n                    }\n                case ADDR_BUFFERS:\n                    eap->line1 = firstbuf->b_fnum;\n                    eap->line2 = lastbuf->b_fnum;\n                    break;\n"
	w4dNewPair1      = "                case ADDR_LOADED_BUFFERS:\n                case ADDR_BUFFERS:\n                    eap->line1 = curbuf->b_fnum;\n                    eap->line2 = curbuf->b_fnum;\n                    break;\n"
	w4dAddrPair2     = "    case ADDR_LOADED_BUFFERS:\n        {\n            buf_T *buf = firstbuf;\n            while (buf->b_next != nullptr && buf->b_ml.ml_mfp == nullptr)\n            {\n                buf = buf->b_next;\n            }\n            eap->line1 = buf->b_fnum;\n            buf = lastbuf;\n            while (buf->b_prev != nullptr && buf->b_ml.ml_mfp == nullptr)\n            {\n                buf = buf->b_prev;\n            }\n            eap->line2 = buf->b_fnum;\n        }\n        break;\n    case ADDR_BUFFERS:\n        eap->line1 = firstbuf->b_fnum;\n        eap->line2 = lastbuf->b_fnum;\n        break;\n"
	w4dNewPair2      = "    case ADDR_LOADED_BUFFERS:\n    case ADDR_BUFFERS:\n        eap->line1 = curbuf->b_fnum;\n        eap->line2 = curbuf->b_fnum;\n        break;\n"
	w4dAddrPair3     = "            case ADDR_LOADED_BUFFERS:\n                buf = lastbuf;\n                while (buf->b_ml.ml_mfp == nullptr)\n                {\n                    if (buf->b_prev == nullptr)\n                    {\n                        break;\n                    }\n                    buf = buf->b_prev;\n                }\n                lnum = buf->b_fnum;\n                break;\n            case ADDR_BUFFERS:\n                lnum = lastbuf->b_fnum;\n                break;\n"
	w4dNewPair3      = "            case ADDR_LOADED_BUFFERS:\n            case ADDR_BUFFERS:\n                lnum = curbuf->b_fnum;\n                break;\n"
	w4dAddrPair4     = "        case ADDR_LOADED_BUFFERS:\n            buf = firstbuf;\n            while (buf->b_ml.ml_mfp == nullptr)\n            {\n                if (buf->b_next == nullptr)\n                {\n                    return _(e_invalid_range);\n                }\n                buf = buf->b_next;\n            }\n            if (eap->line1 < buf->b_fnum)\n            {\n                return _(e_invalid_range);\n            }\n            buf = lastbuf;\n            while (buf->b_ml.ml_mfp == nullptr)\n            {\n                if (buf->b_prev == nullptr)\n                {\n                    return _(e_invalid_range);\n                }\n                buf = buf->b_prev;\n            }\n            if (eap->line2 > buf->b_fnum)\n            {\n                return _(e_invalid_range);\n            }\n            break;\n"
	w4dNewPair4      = "        case ADDR_LOADED_BUFFERS:\n            if (curbuf->b_ml.ml_mfp == nullptr || eap->line1 < curbuf->b_fnum || eap->line2 > curbuf->b_fnum)\n            {\n                return _(e_invalid_range);\n            }\n            break;\n"
	w4dOldReuseStart = "        if ((flags & BLN_REUSE) && buf_reuse.ga_len > 0)\n        {\n            --buf_reuse.ga_len;\n            buf->b_fnum = ((int *)buf_reuse.ga_data)[buf_reuse.ga_len];\n"
	w4dOldReuseEnd   = "        else\n        {\n            buf->b_fnum = top_file_num++;\n        }\n"
	w4dlit3          = "    return buf == curbuf;\n"
	w4dlit4          = "    return bufIsChanged(curbuf);\n"
	w4dlit5          = "    if ((curbuf->b_flags & BF_DUMMY) == 0 && !otherfile_buf(curbuf, ffname, stp))\n    {\n        return curbuf;\n    }\n    return nullptr;\n"
	w4dlit6          = "        if (curbuf->b_ml.ml_mfp != nullptr)\n        {\n            bufref_T bufref;\n\n            set_bufref(&bufref, curbuf);\n            apply_autocmds(EVENT_BUFUNLOAD, curbuf->b_fname, curbuf->b_fname, FALSE, curbuf);\n        }\n"
	w4dlit7          = "    int         match = -1;\n    char_u      *pat;\n    char_u      *patend;\n    int         attempt;\n    char_u      *p;\n    int         toggledollar;\n\n    if ((pattern_end == pattern + 1 && (*pattern == '%' || *pattern == '#')) || (in_vim9script() && pattern_end == pattern + 2 && pattern[0] == '%' && pattern[1] == '%'))\n    {\n        if (*pattern == '#' || pattern_end == pattern + 2)\n        {\n            match = 0;\n        }\n        else\n        {\n            match = curbuf->b_fnum;\n        }\n    }\n\n    else\n    {\n        pat = file_pat_to_reg_pat(pattern, pattern_end, nullptr, FALSE);\n        if (pat == nullptr)\n        {\n            return -1;\n        }\n        patend = pat +  strlen((char *)(pat))  - 1;\n        toggledollar = (patend > pat && *patend == '$');\n\n        for (attempt = 0; attempt <= 3; ++attempt)\n        {\n            regmatch_T      regmatch;\n\n            if (toggledollar)\n            {\n                *patend = (attempt < 2) ? NUL : '$';\n            }\n            p = pat;\n            if (*p == '^' && !(attempt & 1))\n            {\n                ++p;\n            }\n            regmatch.regprog = vim_regcomp(p, magic_isset() ? RE_MAGIC : 0);\n            if (regmatch.regprog == nullptr)\n            {\n                vim_free(pat);\n                return -1;\n            }\n            if (buflist_match(&regmatch, curbuf, FALSE) != nullptr)\n            {\n                match = curbuf->b_fnum;\n            }\n            vim_regfree(regmatch.regprog);\n            if (match >= 0)\n            {\n                break;\n            }\n        }\n\n        vim_free(pat);\n    }\n\n    if (match < 0)\n    {\n        semsg(_(e_no_matching_buffer_for_str), pattern);\n    }\n    return match;\n"
	w4dlit9          = "    return curbuf->b_fnum;\n"
	w4dlit10         = "for (bp = firstbuf;; bp = bp->b_next)\n"
	w4dlit11         = "for (bp = curbuf; ; bp = nullptr)\n"
	w4dlit12         = "    buf_T *b_next;\n    buf_T *b_prev;\n"
	w4dlit13         = "        buf->b_fnum = top_file_num++;\n"
	w4dlit15         = "\n        emsg(_(e_cannot_allocate_buffer_using_other_one));\n        enter_buffer(curbuf);\n        return FAIL;\n"
	w4dlit18         = "    valid = buf_valid(buf);\n    if ((valid && buf != curbuf) || curwin->w_buffer == nullptr)\n    {\n        if (!valid)\n        {\n            enter_buffer(lastbuf);\n        }\n        else\n        {\n            enter_buffer(buf);\n        }\n    }\n"
	w4dlit19         = "    if (curwin->w_buffer == nullptr)\n    {\n        enter_buffer(buf);\n    }\n"
	w4dlit20         = "        buf->b_next = nullptr;\n        if (firstbuf == nullptr)\n        {\n            buf->b_prev = nullptr;\n            firstbuf = buf;\n        }\n        else\n        {\n            lastbuf->b_next = buf;\n            buf->b_prev = lastbuf;\n        }\n        lastbuf = buf;\n"
)
