package p032

// The multi-line literals internal/phase/032/edit.go matches on, EXTRACTED from the phase's
// heredoc by tools/gocmp/genlits.py rather than retyped.  They carry BLANK
// LINES, which a filtered read of a phase program does not show, and a
// literal that is 90%% right matches nothing.  See that tool for the
// measurement.
const (
	w32lit3  = "    CMD_file,\n"
	w32lit4  = "    if (!(ea.argt & (EX_CMDWIN | EX_LOCK_OK)) && ea.cmdidx != CMD_file && curbuf_locked())\n"
	w32lit5  = "    if (!(ea.argt & (EX_CMDWIN | EX_LOCK_OK)) && curbuf_locked())\n"
	w32lit6  = "    if (ea.cmdidx == CMD_file && *ea.arg != NUL && curbuf_locked())\n    {\n        goto doend;\n    }\n"
	w32lit7  = "static buf_T *buflist_new(char_u *ffname_arg, char_u *sfname_arg, linenr_T lnum, int flags);\n"
	w32lit8  = "static buf_T *buflist_new(linenr_T lnum, int flags);\n"
	w32lit9  = "buflist_new(char_u *ffname_arg, char_u *sfname_arg, linenr_T lnum, int flags)\n"
	w32lit10 = "buflist_new(linenr_T    lnum, int         flags)\n"
	w32lit13 = "    fname_expand(curbuf, &ffname, &sfname);\n    if (sfname == nullptr || stat(((char *)sfname), (&st)) < 0)\n    {\n        st.st_dev = (dev_t)-1;\n    }\n    if (ffname != nullptr && !(flags & (BLN_DUMMY | BLN_NEW)) && (buf = buflist_findname_stat(ffname, &st)) != nullptr)\n    {\n        vim_free(ffname);\n        if (lnum != 0)\n        {\n            buflist_setfpos(buf, (flags & BLN_NOCURWIN) ? nullptr : curwin, lnum, (colnr_T)0, FALSE);\n        }\n        if ((flags & BLN_NOOPT) == 0)\n        {\n            buf_copy_options(buf, 0);\n        }\n        return buf;\n    }\n"
	w32lit14 = "        if (buf == nullptr)\n        {\n            vim_free(ffname);\n            return nullptr;\n        }\n"
	w32lit15 = "        if (buf == nullptr)\n        {\n            return nullptr;\n        }\n"
	w32lit16 = "    if (ffname != nullptr)\n    {\n        buf->b_ffname = ffname;\n        buf->b_sfname = vim_strsave(sfname);\n    }\n"
	w32lit17 = "    if ((ffname != nullptr && (buf->b_ffname == nullptr || buf->b_sfname == nullptr)) || buf->b_wininfo == nullptr)\n    {\n        if (buf->b_sfname != buf->b_ffname)\n        {\n            vim_free(buf->b_sfname);\n            (buf->b_sfname) = nullptr;\n        }\n        else\n        {\n            buf->b_sfname = nullptr;\n        }\n        vim_free(buf->b_ffname);\n        (buf->b_ffname) = nullptr;\n        if (buf != curbuf)\n"
	w32lit18 = "    if (buf->b_wininfo == nullptr)\n    {\n        if (buf != curbuf)\n"
	w32lit19 = "    buf->b_fname = buf->b_sfname;\n"
	w32lit20 = "    if (st.st_dev == (dev_t)-1)\n    {\n        buf->b_dev_valid = false;\n    }\n    else\n    {\n        buf->b_dev_valid = true;\n        buf->b_dev = st.st_dev;\n        buf->b_ino = st.st_ino;\n    }\n"
	w32lit21 = "    buf->b_dev_valid = false;\n"
	w32lit22 = "    curbuf = buflist_new(nullptr, nullptr, 1L, BLN_LISTED);\n"
	w32lit23 = "    curbuf = buflist_new(1L, BLN_LISTED);\n"
	w32lit24 = "        char_u *fname = buf->b_fname != nullptr ? buf->b_fname : buf->b_ffname;\n        vim_snprintf((char *)IObuff, emsg_iobuff_room(), _(e_attempt_to_delete_buffer_that_is_in_use_str), fname != nullptr ? fname : (char_u *)\"[No Name]\");\n        emsg(iobuff_or(_(e_attempt_to_delete_buffer_that_is_in_use_str)));\n"
	w32lit25 = "        vim_snprintf((char *)IObuff, emsg_iobuff_room(), _(e_attempt_to_delete_buffer_that_is_in_use_str), (char_u *)\"[No Name]\");\n        emsg(iobuff_or(_(e_attempt_to_delete_buffer_that_is_in_use_str)));\n"
	w32lit26 = "    char_u *fname;\n    linenr_T dummy;\n    if (buflist_name_nr(0, &fname, &dummy) == FAIL)\n    {\n        if (errmsg)\n        {\n            emsg(_(e_no_alternate_file));\n        }\n        return nullptr;\n    }\n    return fname;\n"
	w32lit27 = "    if (errmsg)\n    {\n        emsg(_(e_no_alternate_file));\n    }\n    return nullptr;\n"
	w32lit28 = "    if (name != nullptr)\n"
	w32lit29 = "buf_spname(buf_T *buf)\n{\n    if (buf->b_fname == nullptr)\n    {\n        return buf_get_fname(buf);\n    }\n    return nullptr;\n}\n"
	w32lit30 = "buf_spname(buf_T *buf)\n{\n    return buf_get_fname(buf);\n}\n"
	w32lit31 = "buf_get_fname(buf_T *buf)\n{\n    if (buf->b_fname == nullptr)\n    {\n        return (char_u *)_(\"[No Name]\");\n    }\n    return buf->b_fname;\n}\n"
	w32lit32 = "buf_get_fname(buf_T *buf)\n{\n    return (char_u *)_(\"[No Name]\");\n}\n"
	w32lit35 = "check_fname(void)\n{\n    if (curbuf->b_ffname == nullptr)\n    {\n        emsg(_(e_no_file_name));\n        return FAIL;\n    }\n    return OK;\n}\n"
	w32lit36 = "check_fname(void)\n{\n    emsg(_(e_no_file_name));\n    return FAIL;\n}\n"
	w32lit37 = "    return file_name_in_line(ml_get_curline(), curwin->w_cursor.col, options, count, curbuf->b_ffname, file_lnum);\n"
	w32lit38 = "    return file_name_in_line(ml_get_curline(), curwin->w_cursor.col, options, count, nullptr, file_lnum);\n"
	w32lit39 = "    if (buf->b_ffname == nullptr)\n"
	w32lit40 = "        *argp = curbuf->b_fname;\n"
	w32lit41 = "        *argp = nullptr;\n"
	w32lit42 = "    if (buf_spname(buf) != nullptr)\n"
	w32lit43 = "            if (eap->argt & (EX_CTRLV | EX_XFILE))\n"
	w32lit44 = "            if (eap->argt & EX_CTRLV)\n"
	w32lit46 = "    char_u dirname[PATH_MAX];\n    buf_T *buf;\n    mch_dirname(dirname, PATH_MAX);\n    buf = curbuf;\n    shorten_buf_fname(buf, dirname, force);\n"
	w32lit47 = "static void shorten_fnames(int force);\n"
	w32lit48 = "static void shorten_fnames(void);\n"
	w32lit49 = "shorten_fnames(int force)\n"
	w32lit50 = "shorten_fnames(void)\n"
	w32lit51 = "    shorten_fnames(FALSE);\n"
	w32lit52 = "    shorten_fnames();\n"
)
