// Code generated by walkgen; DO NOT EDIT.

package ccwalk

import "github.com/arbace/go-whim/crefactor/cc"

// genFields is, per node type, the fields the generated walks visit, as
// "name:kind" -- for TestWalkGen to hold against reflection's fieldsOf.
var genFields = map[string][]string{
	"AbstractDeclarator":       {"DirectAbstractDeclarator:p", "Pointer:p"},
	"AdditiveExpression":       {"AdditiveExpression:i", "MultiplicativeExpression:i", "Token:t"},
	"AlignmentSpecifier":       {"ConstantExpression:i", "Token:t", "Token2:t", "Token3:t", "TypeName:p"},
	"AndExpression":            {"AndExpression:i", "EqualityExpression:i", "Token:t"},
	"ArgumentExpressionList":   {"ArgumentExpressionList:p", "AssignmentExpression:i", "Token:t"},
	"Asm":                      {"AsmArgList:p", "AsmQualifierList:p", "Token:t", "Token2:t", "Token3:t", "Token4:t"},
	"AsmArgList":               {"AsmArgList:p", "AsmExpressionList:p", "Token:t"},
	"AsmExpressionList":        {"AsmExpressionList:p", "AsmIndex:p", "AssignmentExpression:i", "Token:t"},
	"AsmIndex":                 {"ExpressionList:i", "Token:t", "Token2:t"},
	"AsmQualifier":             {"Token:t"},
	"AsmQualifierList":         {"AsmQualifier:p", "AsmQualifierList:p"},
	"AsmStatement":             {"Asm:p", "Token:t"},
	"AssignmentExpression":     {"AssignmentExpression:i", "ConditionalExpression:i", "Token:t", "UnaryExpression:i"},
	"AtomicTypeSpecifier":      {"Token:t", "Token2:t", "Token3:t", "TypeName:p"},
	"AttributeSpecifier":       {"AttributeValueList:p", "Token:t", "Token2:t", "Token3:t", "Token4:t", "Token5:t"},
	"AttributeSpecifierList":   {"AttributeSpecifier:p", "AttributeSpecifierList:p"},
	"AttributeValue":           {"ArgumentExpressionList:p", "Token:t", "Token2:t", "Token3:t", "Prefix:t", "Colon:t", "Colon2:t", "BalancedTokenSequence:p"},
	"AttributeValueList":       {"AttributeValue:p", "AttributeValueList:p", "Token:t"},
	"BalancedTokenSequence":    {"Token:t", "BalancedTokenSequence:p"},
	"BlockItem":                {"CompoundStatement:p", "Declaration:p", "DeclarationSpecifiers:p", "Declarator:p", "LabelDeclaration:p", "Statement:p"},
	"BlockItemList":            {"BlockItem:p", "BlockItemList:p"},
	"CastExpression":           {"CastExpression:i", "Token:t", "Token2:t", "TypeName:p", "UnaryExpression:i"},
	"CompoundStatement":        {"BlockItemList:p", "Token:t", "Token2:t"},
	"ConditionalExpression":    {"ConditionalExpression:i", "ExpressionList:i", "LogicalOrExpression:i", "Token:t", "Token2:t"},
	"ConstantExpression":       {"ConditionalExpression:i"},
	"Declaration":              {"AttributeSpecifierList:p", "DeclarationSpecifiers:p", "Declarator:p", "InitDeclaratorList:p", "Initializer:p", "StaticAssertDeclaration:p", "Token:t", "Token2:t", "Token3:t"},
	"DeclarationList":          {"Declaration:p", "DeclarationList:p"},
	"DeclarationSpecifiers":    {"AttributeSpecifierList:p", "AlignmentSpecifier:p", "DeclarationSpecifiers:p", "FunctionSpecifier:p", "StorageClassSpecifier:p", "Token:t", "TypeQualifier:p", "TypeSpecifier:p"},
	"Declarator":               {"DirectDeclarator:p", "Pointer:p"},
	"Designation":              {"DesignatorList:p", "Token:t"},
	"Designator":               {"ConstantExpression:i", "ConstantExpression2:i", "Token:t", "Token2:t", "Token3:t"},
	"DesignatorList":           {"Designator:p", "DesignatorList:p"},
	"DirectAbstractDeclarator": {"AbstractDeclarator:p", "AssignmentExpression:i", "DirectAbstractDeclarator:p", "ParameterTypeList:p", "Token:t", "Token2:t", "Token3:t", "TypeQualifiers:p"},
	"DirectDeclarator":         {"AssignmentExpression:i", "Declarator:p", "DirectDeclarator:p", "IdentifierList:p", "ParameterTypeList:p", "Token:t", "Token2:t", "Token3:t", "TypeQualifiers:p", "AttributeSpecifierList:p"},
	"EnumSpecifier":            {"EnumTypeSpecifier:p", "EnumeratorList:p", "Token:t", "Token2:t", "Token3:t", "Token4:t", "Token5:t", "AttributeSpecifierList:p"},
	"EnumTypeSpecifier":        {"SpecifierQualifierList:p", "Token:t"},
	"Enumerator":               {"ConstantExpression:i", "Token:t", "Token2:t", "AttributeSpecifierList:p"},
	"EnumeratorList":           {"Enumerator:p", "EnumeratorList:p", "Token:t"},
	"EqualityExpression":       {"EqualityExpression:i", "RelationalExpression:i", "Token:t"},
	"ExclusiveOrExpression":    {"AndExpression:i", "ExclusiveOrExpression:i", "Token:t"},
	"ExpressionList":           {"AssignmentExpression:i", "ExpressionList:p", "Token:t"},
	"ExpressionStatement":      {"AttributeSpecifierList:p", "ExpressionList:i", "Token:t"},
	"ExternalDeclaration":      {"AsmStatement:p", "Declaration:p", "FunctionDefinition:p", "Token:t"},
	"FunctionDefinition":       {"CompoundStatement:p", "DeclarationList:p", "DeclarationSpecifiers:p", "Declarator:p", "AttributeSpecifierList:p"},
	"FunctionSpecifier":        {"Token:t"},
	"GenericAssociation":       {"AssignmentExpression:i", "Token:t", "Token2:t", "TypeName:p"},
	"GenericAssociationList":   {"GenericAssociation:p", "GenericAssociationList:p", "Token:t"},
	"GenericSelection":         {"AssignmentExpression:i", "GenericAssociationList:p", "Token:t", "Token2:t", "Token3:t", "Token4:t"},
	"IdentifierList":           {"IdentifierList:p", "Token:t", "Token2:t"},
	"InclusiveOrExpression":    {"ExclusiveOrExpression:i", "InclusiveOrExpression:i", "Token:t"},
	"InitDeclarator":           {"AttributeSpecifierList:p", "Asm:p", "Declarator:p", "Initializer:p", "Token:t"},
	"InitDeclaratorList":       {"AttributeSpecifierList:p", "InitDeclarator:p", "InitDeclaratorList:p", "Token:t"},
	"Initializer":              {"AssignmentExpression:i", "InitializerList:p", "Token:t", "Token2:t", "Token3:t"},
	"InitializerList":          {"Designation:p", "Initializer:p", "InitializerList:p", "Token:t"},
	"IterationStatement":       {"Declaration:p", "ExpressionList:i", "ExpressionList2:i", "ExpressionList3:i", "Statement:p", "Token:t", "Token2:t", "Token3:t", "Token4:t", "Token5:t"},
	"JumpStatement":            {"ExpressionList:i", "Token:t", "Token2:t", "Token3:t"},
	"LabelDeclaration":         {"IdentifierList:p", "Token:t", "Token2:t"},
	"LabeledStatement":         {"ConstantExpression:i", "ConstantExpression2:i", "Statement:p", "Token:t", "Token2:t", "Token3:t"},
	"LogicalAndExpression":     {"InclusiveOrExpression:i", "LogicalAndExpression:i", "Token:t"},
	"LogicalOrExpression":      {"LogicalAndExpression:i", "LogicalOrExpression:i", "Token:t"},
	"Macro":                    {"Name:t"},
	"MultiplicativeExpression": {"CastExpression:i", "MultiplicativeExpression:i", "Token:t"},
	"Parameter":                {"Declarator:p", "AbstractDeclarator:p"},
	"ParameterDeclaration":     {"AttributeSpecifierList:p", "AbstractDeclarator:p", "DeclarationSpecifiers:p", "Declarator:p"},
	"ParameterList":            {"ParameterDeclaration:p", "ParameterList:p", "Token:t"},
	"ParameterTypeList":        {"ParameterList:p", "Token:t", "Token2:t"},
	"Pointer":                  {"Pointer:p", "Token:t", "TypeQualifiers:p"},
	"PostfixExpression":        {"ArgumentExpressionList:p", "ExpressionList:i", "InitializerList:p", "PostfixExpression:i", "PrimaryExpression:i", "Token:t", "Token2:t", "Token3:t", "Token4:t", "Token5:t", "TypeName:p"},
	"PrimaryExpression":        {"CompoundStatement:p", "ExpressionList:i", "GenericSelection:p", "Token:t", "Token2:t"},
	"RelationalExpression":     {"RelationalExpression:i", "ShiftExpression:i", "Token:t"},
	"SelectionStatement":       {"ExpressionList:i", "Statement:p", "Statement2:p", "Token:t", "Token2:t", "Token3:t", "Token4:t"},
	"ShiftExpression":          {"AdditiveExpression:i", "ShiftExpression:i", "Token:t"},
	"SpecifierQualifierList":   {"AttributeSpecifierList:p", "AlignmentSpecifier:p", "SpecifierQualifierList:p", "TypeQualifier:p", "TypeSpecifier:p"},
	"Statement":                {"AsmStatement:p", "CompoundStatement:p", "ExpressionStatement:p", "IterationStatement:p", "JumpStatement:p", "LabeledStatement:p", "SelectionStatement:p", "AttributeSpecifierList:p"},
	"StaticAssertDeclaration":  {"ConstantExpression:i", "Token:t", "Token2:t", "Token3:t", "Token4:t", "Token5:t"},
	"StorageClassSpecifier":    {"Token:t", "Token2:t", "Token3:t"},
	"StructDeclaration":        {"AttributeSpecifierList:p", "SpecifierQualifierList:p", "StaticAssertDeclaration:p", "StructDeclaratorList:p", "Token:t"},
	"StructDeclarationList":    {"StructDeclaration:p", "StructDeclarationList:p"},
	"StructDeclarator":         {"ConstantExpression:i", "Declarator:p", "Token:t"},
	"StructDeclaratorList":     {"StructDeclarator:p", "StructDeclaratorList:p", "Token:t"},
	"StructOrUnion":            {"Token:t"},
	"StructOrUnionSpecifier":   {"AttributeSpecifierList:p", "AttributeSpecifierList2:p", "StructDeclarationList:p", "StructOrUnion:p", "Token:t", "Token2:t", "Token3:t"},
	"TranslationUnit":          {"ExternalDeclaration:p", "TranslationUnit:p"},
	"TypeName":                 {"AbstractDeclarator:p", "SpecifierQualifierList:p"},
	"TypeQualifier":            {"AttributeSpecifierList:p", "Token:t"},
	"TypeQualifiers":           {"TypeQualifier:p", "TypeQualifiers:p"},
	"TypeSpecifier":            {"AtomicTypeSpecifier:p", "EnumSpecifier:p", "ExpressionList:i", "StructOrUnionSpecifier:p", "Token:t", "Token2:t", "Token3:t", "TypeName:p"},
	"UnaryExpression":          {"CastExpression:i", "PostfixExpression:i", "Token:t", "Token2:t", "Token3:t", "TypeName:p", "UnaryExpression:i"},
}

// walk calls f on every node under n, n included, in source order, and does
// not descend below a node f returns false for.
func Walk(n cc.Node, f func(cc.Node) bool) {
	switch x := n.(type) {
	case nil:
		return
	case *cc.AbstractDeclarator:
		if x == nil || !f(x) {
			return
		}
		if x.DirectAbstractDeclarator != nil {
			Walk(x.DirectAbstractDeclarator, f)
		}
		if x.Pointer != nil {
			Walk(x.Pointer, f)
		}
	case *cc.AdditiveExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AdditiveExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.MultiplicativeExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.AlignmentSpecifier:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.TypeName != nil {
			Walk(x.TypeName, f)
		}
	case *cc.AndExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AndExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.EqualityExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.ArgumentExpressionList:
		if x == nil || !f(x) {
			return
		}
		if x.ArgumentExpressionList != nil {
			Walk(x.ArgumentExpressionList, f)
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.Asm:
		if x == nil || !f(x) {
			return
		}
		if x.AsmArgList != nil {
			Walk(x.AsmArgList, f)
		}
		if x.AsmQualifierList != nil {
			Walk(x.AsmQualifierList, f)
		}
	case *cc.AsmArgList:
		if x == nil || !f(x) {
			return
		}
		if x.AsmArgList != nil {
			Walk(x.AsmArgList, f)
		}
		if x.AsmExpressionList != nil {
			Walk(x.AsmExpressionList, f)
		}
	case *cc.AsmExpressionList:
		if x == nil || !f(x) {
			return
		}
		if x.AsmExpressionList != nil {
			Walk(x.AsmExpressionList, f)
		}
		if x.AsmIndex != nil {
			Walk(x.AsmIndex, f)
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.AsmIndex:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.AsmQualifier:
		if x == nil || !f(x) {
			return
		}
	case *cc.AsmQualifierList:
		if x == nil || !f(x) {
			return
		}
		if x.AsmQualifier != nil {
			Walk(x.AsmQualifier, f)
		}
		if x.AsmQualifierList != nil {
			Walk(x.AsmQualifierList, f)
		}
	case *cc.AsmStatement:
		if x == nil || !f(x) {
			return
		}
		if x.Asm != nil {
			Walk(x.Asm, f)
		}
	case *cc.AssignmentExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ConditionalExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.UnaryExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.AtomicTypeSpecifier:
		if x == nil || !f(x) {
			return
		}
		if x.TypeName != nil {
			Walk(x.TypeName, f)
		}
	case *cc.AttributeSpecifier:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeValueList != nil {
			Walk(x.AttributeValueList, f)
		}
	case *cc.AttributeSpecifierList:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifier != nil {
			Walk(x.AttributeSpecifier, f)
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
	case *cc.AttributeValue:
		if x == nil || !f(x) {
			return
		}
		if x.ArgumentExpressionList != nil {
			Walk(x.ArgumentExpressionList, f)
		}
		if x.BalancedTokenSequence != nil {
			Walk(x.BalancedTokenSequence, f)
		}
	case *cc.AttributeValueList:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeValue != nil {
			Walk(x.AttributeValue, f)
		}
		if x.AttributeValueList != nil {
			Walk(x.AttributeValueList, f)
		}
	case *cc.BalancedTokenSequence:
		if x == nil || !f(x) {
			return
		}
		if x.BalancedTokenSequence != nil {
			Walk(x.BalancedTokenSequence, f)
		}
	case *cc.BlockItem:
		if x == nil || !f(x) {
			return
		}
		if x.CompoundStatement != nil {
			Walk(x.CompoundStatement, f)
		}
		if x.Declaration != nil {
			Walk(x.Declaration, f)
		}
		if x.DeclarationSpecifiers != nil {
			Walk(x.DeclarationSpecifiers, f)
		}
		if x.Declarator != nil {
			Walk(x.Declarator, f)
		}
		if x.LabelDeclaration != nil {
			Walk(x.LabelDeclaration, f)
		}
		if x.Statement != nil {
			Walk(x.Statement, f)
		}
	case *cc.BlockItemList:
		if x == nil || !f(x) {
			return
		}
		if x.BlockItem != nil {
			Walk(x.BlockItem, f)
		}
		if x.BlockItemList != nil {
			Walk(x.BlockItemList, f)
		}
	case *cc.CastExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.CastExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.TypeName != nil {
			Walk(x.TypeName, f)
		}
		if y, ok := any(x.UnaryExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.CompoundStatement:
		if x == nil || !f(x) {
			return
		}
		if x.BlockItemList != nil {
			Walk(x.BlockItemList, f)
		}
	case *cc.ConditionalExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ConditionalExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.LogicalOrExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.ConstantExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ConditionalExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.Declaration:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if x.DeclarationSpecifiers != nil {
			Walk(x.DeclarationSpecifiers, f)
		}
		if x.Declarator != nil {
			Walk(x.Declarator, f)
		}
		if x.InitDeclaratorList != nil {
			Walk(x.InitDeclaratorList, f)
		}
		if x.Initializer != nil {
			Walk(x.Initializer, f)
		}
		if x.StaticAssertDeclaration != nil {
			Walk(x.StaticAssertDeclaration, f)
		}
	case *cc.DeclarationList:
		if x == nil || !f(x) {
			return
		}
		if x.Declaration != nil {
			Walk(x.Declaration, f)
		}
		if x.DeclarationList != nil {
			Walk(x.DeclarationList, f)
		}
	case *cc.DeclarationSpecifiers:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if x.AlignmentSpecifier != nil {
			Walk(x.AlignmentSpecifier, f)
		}
		if x.DeclarationSpecifiers != nil {
			Walk(x.DeclarationSpecifiers, f)
		}
		if x.FunctionSpecifier != nil {
			Walk(x.FunctionSpecifier, f)
		}
		if x.StorageClassSpecifier != nil {
			Walk(x.StorageClassSpecifier, f)
		}
		if x.TypeQualifier != nil {
			Walk(x.TypeQualifier, f)
		}
		if x.TypeSpecifier != nil {
			Walk(x.TypeSpecifier, f)
		}
	case *cc.Declarator:
		if x == nil || !f(x) {
			return
		}
		if x.DirectDeclarator != nil {
			Walk(x.DirectDeclarator, f)
		}
		if x.Pointer != nil {
			Walk(x.Pointer, f)
		}
	case *cc.Designation:
		if x == nil || !f(x) {
			return
		}
		if x.DesignatorList != nil {
			Walk(x.DesignatorList, f)
		}
	case *cc.Designator:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ConstantExpression2).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.DesignatorList:
		if x == nil || !f(x) {
			return
		}
		if x.Designator != nil {
			Walk(x.Designator, f)
		}
		if x.DesignatorList != nil {
			Walk(x.DesignatorList, f)
		}
	case *cc.DirectAbstractDeclarator:
		if x == nil || !f(x) {
			return
		}
		if x.AbstractDeclarator != nil {
			Walk(x.AbstractDeclarator, f)
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.DirectAbstractDeclarator != nil {
			Walk(x.DirectAbstractDeclarator, f)
		}
		if x.ParameterTypeList != nil {
			Walk(x.ParameterTypeList, f)
		}
		if x.TypeQualifiers != nil {
			Walk(x.TypeQualifiers, f)
		}
	case *cc.DirectDeclarator:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.Declarator != nil {
			Walk(x.Declarator, f)
		}
		if x.DirectDeclarator != nil {
			Walk(x.DirectDeclarator, f)
		}
		if x.IdentifierList != nil {
			Walk(x.IdentifierList, f)
		}
		if x.ParameterTypeList != nil {
			Walk(x.ParameterTypeList, f)
		}
		if x.TypeQualifiers != nil {
			Walk(x.TypeQualifiers, f)
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
	case *cc.EnumSpecifier:
		if x == nil || !f(x) {
			return
		}
		if x.EnumTypeSpecifier != nil {
			Walk(x.EnumTypeSpecifier, f)
		}
		if x.EnumeratorList != nil {
			Walk(x.EnumeratorList, f)
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
	case *cc.EnumTypeSpecifier:
		if x == nil || !f(x) {
			return
		}
		if x.SpecifierQualifierList != nil {
			Walk(x.SpecifierQualifierList, f)
		}
	case *cc.Enumerator:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
	case *cc.EnumeratorList:
		if x == nil || !f(x) {
			return
		}
		if x.Enumerator != nil {
			Walk(x.Enumerator, f)
		}
		if x.EnumeratorList != nil {
			Walk(x.EnumeratorList, f)
		}
	case *cc.EqualityExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.EqualityExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.RelationalExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.ExclusiveOrExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AndExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ExclusiveOrExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.ExpressionList:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.ExpressionList != nil {
			Walk(x.ExpressionList, f)
		}
	case *cc.ExpressionStatement:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.ExternalDeclaration:
		if x == nil || !f(x) {
			return
		}
		if x.AsmStatement != nil {
			Walk(x.AsmStatement, f)
		}
		if x.Declaration != nil {
			Walk(x.Declaration, f)
		}
		if x.FunctionDefinition != nil {
			Walk(x.FunctionDefinition, f)
		}
	case *cc.FunctionDefinition:
		if x == nil || !f(x) {
			return
		}
		if x.CompoundStatement != nil {
			Walk(x.CompoundStatement, f)
		}
		if x.DeclarationList != nil {
			Walk(x.DeclarationList, f)
		}
		if x.DeclarationSpecifiers != nil {
			Walk(x.DeclarationSpecifiers, f)
		}
		if x.Declarator != nil {
			Walk(x.Declarator, f)
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
	case *cc.FunctionSpecifier:
		if x == nil || !f(x) {
			return
		}
	case *cc.GenericAssociation:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.TypeName != nil {
			Walk(x.TypeName, f)
		}
	case *cc.GenericAssociationList:
		if x == nil || !f(x) {
			return
		}
		if x.GenericAssociation != nil {
			Walk(x.GenericAssociation, f)
		}
		if x.GenericAssociationList != nil {
			Walk(x.GenericAssociationList, f)
		}
	case *cc.GenericSelection:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.GenericAssociationList != nil {
			Walk(x.GenericAssociationList, f)
		}
	case *cc.IdentifierList:
		if x == nil || !f(x) {
			return
		}
		if x.IdentifierList != nil {
			Walk(x.IdentifierList, f)
		}
	case *cc.InclusiveOrExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ExclusiveOrExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.InclusiveOrExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.InitDeclarator:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if x.Asm != nil {
			Walk(x.Asm, f)
		}
		if x.Declarator != nil {
			Walk(x.Declarator, f)
		}
		if x.Initializer != nil {
			Walk(x.Initializer, f)
		}
	case *cc.InitDeclaratorList:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if x.InitDeclarator != nil {
			Walk(x.InitDeclarator, f)
		}
		if x.InitDeclaratorList != nil {
			Walk(x.InitDeclaratorList, f)
		}
	case *cc.Initializer:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.InitializerList != nil {
			Walk(x.InitializerList, f)
		}
	case *cc.InitializerList:
		if x == nil || !f(x) {
			return
		}
		if x.Designation != nil {
			Walk(x.Designation, f)
		}
		if x.Initializer != nil {
			Walk(x.Initializer, f)
		}
		if x.InitializerList != nil {
			Walk(x.InitializerList, f)
		}
	case *cc.IterationStatement:
		if x == nil || !f(x) {
			return
		}
		if x.Declaration != nil {
			Walk(x.Declaration, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ExpressionList2).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ExpressionList3).(cc.Node); ok {
			Walk(y, f)
		}
		if x.Statement != nil {
			Walk(x.Statement, f)
		}
	case *cc.JumpStatement:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.LabelDeclaration:
		if x == nil || !f(x) {
			return
		}
		if x.IdentifierList != nil {
			Walk(x.IdentifierList, f)
		}
	case *cc.LabeledStatement:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ConstantExpression2).(cc.Node); ok {
			Walk(y, f)
		}
		if x.Statement != nil {
			Walk(x.Statement, f)
		}
	case *cc.LogicalAndExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.InclusiveOrExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.LogicalAndExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.LogicalOrExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.LogicalAndExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.LogicalOrExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.Macro:
		if x == nil || !f(x) {
			return
		}
	case *cc.MultiplicativeExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.CastExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.MultiplicativeExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.Parameter:
		if x == nil || !f(x) {
			return
		}
		if x.Declarator != nil {
			Walk(x.Declarator, f)
		}
		if x.AbstractDeclarator != nil {
			Walk(x.AbstractDeclarator, f)
		}
	case *cc.ParameterDeclaration:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if x.AbstractDeclarator != nil {
			Walk(x.AbstractDeclarator, f)
		}
		if x.DeclarationSpecifiers != nil {
			Walk(x.DeclarationSpecifiers, f)
		}
		if x.Declarator != nil {
			Walk(x.Declarator, f)
		}
	case *cc.ParameterList:
		if x == nil || !f(x) {
			return
		}
		if x.ParameterDeclaration != nil {
			Walk(x.ParameterDeclaration, f)
		}
		if x.ParameterList != nil {
			Walk(x.ParameterList, f)
		}
	case *cc.ParameterTypeList:
		if x == nil || !f(x) {
			return
		}
		if x.ParameterList != nil {
			Walk(x.ParameterList, f)
		}
	case *cc.Pointer:
		if x == nil || !f(x) {
			return
		}
		if x.Pointer != nil {
			Walk(x.Pointer, f)
		}
		if x.TypeQualifiers != nil {
			Walk(x.TypeQualifiers, f)
		}
	case *cc.PostfixExpression:
		if x == nil || !f(x) {
			return
		}
		if x.ArgumentExpressionList != nil {
			Walk(x.ArgumentExpressionList, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
		if x.InitializerList != nil {
			Walk(x.InitializerList, f)
		}
		if y, ok := any(x.PostfixExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.PrimaryExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.TypeName != nil {
			Walk(x.TypeName, f)
		}
	case *cc.PrimaryExpression:
		if x == nil || !f(x) {
			return
		}
		if x.CompoundStatement != nil {
			Walk(x.CompoundStatement, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
		if x.GenericSelection != nil {
			Walk(x.GenericSelection, f)
		}
	case *cc.RelationalExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.RelationalExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ShiftExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.SelectionStatement:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
		if x.Statement != nil {
			Walk(x.Statement, f)
		}
		if x.Statement2 != nil {
			Walk(x.Statement2, f)
		}
	case *cc.ShiftExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.AdditiveExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.ShiftExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.SpecifierQualifierList:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if x.AlignmentSpecifier != nil {
			Walk(x.AlignmentSpecifier, f)
		}
		if x.SpecifierQualifierList != nil {
			Walk(x.SpecifierQualifierList, f)
		}
		if x.TypeQualifier != nil {
			Walk(x.TypeQualifier, f)
		}
		if x.TypeSpecifier != nil {
			Walk(x.TypeSpecifier, f)
		}
	case *cc.Statement:
		if x == nil || !f(x) {
			return
		}
		if x.AsmStatement != nil {
			Walk(x.AsmStatement, f)
		}
		if x.CompoundStatement != nil {
			Walk(x.CompoundStatement, f)
		}
		if x.ExpressionStatement != nil {
			Walk(x.ExpressionStatement, f)
		}
		if x.IterationStatement != nil {
			Walk(x.IterationStatement, f)
		}
		if x.JumpStatement != nil {
			Walk(x.JumpStatement, f)
		}
		if x.LabeledStatement != nil {
			Walk(x.LabeledStatement, f)
		}
		if x.SelectionStatement != nil {
			Walk(x.SelectionStatement, f)
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
	case *cc.StaticAssertDeclaration:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			Walk(y, f)
		}
	case *cc.StorageClassSpecifier:
		if x == nil || !f(x) {
			return
		}
	case *cc.StructDeclaration:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if x.SpecifierQualifierList != nil {
			Walk(x.SpecifierQualifierList, f)
		}
		if x.StaticAssertDeclaration != nil {
			Walk(x.StaticAssertDeclaration, f)
		}
		if x.StructDeclaratorList != nil {
			Walk(x.StructDeclaratorList, f)
		}
	case *cc.StructDeclarationList:
		if x == nil || !f(x) {
			return
		}
		if x.StructDeclaration != nil {
			Walk(x.StructDeclaration, f)
		}
		if x.StructDeclarationList != nil {
			Walk(x.StructDeclarationList, f)
		}
	case *cc.StructDeclarator:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.Declarator != nil {
			Walk(x.Declarator, f)
		}
	case *cc.StructDeclaratorList:
		if x == nil || !f(x) {
			return
		}
		if x.StructDeclarator != nil {
			Walk(x.StructDeclarator, f)
		}
		if x.StructDeclaratorList != nil {
			Walk(x.StructDeclaratorList, f)
		}
	case *cc.StructOrUnion:
		if x == nil || !f(x) {
			return
		}
	case *cc.StructOrUnionSpecifier:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
		if x.AttributeSpecifierList2 != nil {
			Walk(x.AttributeSpecifierList2, f)
		}
		if x.StructDeclarationList != nil {
			Walk(x.StructDeclarationList, f)
		}
		if x.StructOrUnion != nil {
			Walk(x.StructOrUnion, f)
		}
	case *cc.TranslationUnit:
		if x == nil || !f(x) {
			return
		}
		if x.ExternalDeclaration != nil {
			Walk(x.ExternalDeclaration, f)
		}
		if x.TranslationUnit != nil {
			Walk(x.TranslationUnit, f)
		}
	case *cc.TypeName:
		if x == nil || !f(x) {
			return
		}
		if x.AbstractDeclarator != nil {
			Walk(x.AbstractDeclarator, f)
		}
		if x.SpecifierQualifierList != nil {
			Walk(x.SpecifierQualifierList, f)
		}
	case *cc.TypeQualifier:
		if x == nil || !f(x) {
			return
		}
		if x.AttributeSpecifierList != nil {
			Walk(x.AttributeSpecifierList, f)
		}
	case *cc.TypeQualifiers:
		if x == nil || !f(x) {
			return
		}
		if x.TypeQualifier != nil {
			Walk(x.TypeQualifier, f)
		}
		if x.TypeQualifiers != nil {
			Walk(x.TypeQualifiers, f)
		}
	case *cc.TypeSpecifier:
		if x == nil || !f(x) {
			return
		}
		if x.AtomicTypeSpecifier != nil {
			Walk(x.AtomicTypeSpecifier, f)
		}
		if x.EnumSpecifier != nil {
			Walk(x.EnumSpecifier, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			Walk(y, f)
		}
		if x.StructOrUnionSpecifier != nil {
			Walk(x.StructOrUnionSpecifier, f)
		}
		if x.TypeName != nil {
			Walk(x.TypeName, f)
		}
	case *cc.UnaryExpression:
		if x == nil || !f(x) {
			return
		}
		if y, ok := any(x.CastExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if y, ok := any(x.PostfixExpression).(cc.Node); ok {
			Walk(y, f)
		}
		if x.TypeName != nil {
			Walk(x.TypeName, f)
		}
		if y, ok := any(x.UnaryExpression).(cc.Node); ok {
			Walk(y, f)
		}
	default:
		walkReflect(n, f)
	}
}

// WalkTok calls f on every token under n, in field order.
func WalkTok(n cc.Node, f func(cc.Token)) {
	switch x := n.(type) {
	case nil:
		return
	case *cc.AbstractDeclarator:
		if x == nil {
			return
		}
		if x.DirectAbstractDeclarator != nil {
			WalkTok(x.DirectAbstractDeclarator, f)
		}
		if x.Pointer != nil {
			WalkTok(x.Pointer, f)
		}
	case *cc.AdditiveExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.AdditiveExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.MultiplicativeExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.AlignmentSpecifier:
		if x == nil {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		if x.TypeName != nil {
			WalkTok(x.TypeName, f)
		}
	case *cc.AndExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.AndExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.EqualityExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.ArgumentExpressionList:
		if x == nil {
			return
		}
		if x.ArgumentExpressionList != nil {
			WalkTok(x.ArgumentExpressionList, f)
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.Asm:
		if x == nil {
			return
		}
		if x.AsmArgList != nil {
			WalkTok(x.AsmArgList, f)
		}
		if x.AsmQualifierList != nil {
			WalkTok(x.AsmQualifierList, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Token4)
	case *cc.AsmArgList:
		if x == nil {
			return
		}
		if x.AsmArgList != nil {
			WalkTok(x.AsmArgList, f)
		}
		if x.AsmExpressionList != nil {
			WalkTok(x.AsmExpressionList, f)
		}
		f(x.Token)
	case *cc.AsmExpressionList:
		if x == nil {
			return
		}
		if x.AsmExpressionList != nil {
			WalkTok(x.AsmExpressionList, f)
		}
		if x.AsmIndex != nil {
			WalkTok(x.AsmIndex, f)
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.AsmIndex:
		if x == nil {
			return
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
	case *cc.AsmQualifier:
		if x == nil {
			return
		}
		f(x.Token)
	case *cc.AsmQualifierList:
		if x == nil {
			return
		}
		if x.AsmQualifier != nil {
			WalkTok(x.AsmQualifier, f)
		}
		if x.AsmQualifierList != nil {
			WalkTok(x.AsmQualifierList, f)
		}
	case *cc.AsmStatement:
		if x == nil {
			return
		}
		if x.Asm != nil {
			WalkTok(x.Asm, f)
		}
		f(x.Token)
	case *cc.AssignmentExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ConditionalExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		if y, ok := any(x.UnaryExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
	case *cc.AtomicTypeSpecifier:
		if x == nil {
			return
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		if x.TypeName != nil {
			WalkTok(x.TypeName, f)
		}
	case *cc.AttributeSpecifier:
		if x == nil {
			return
		}
		if x.AttributeValueList != nil {
			WalkTok(x.AttributeValueList, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Token4)
		f(x.Token5)
	case *cc.AttributeSpecifierList:
		if x == nil {
			return
		}
		if x.AttributeSpecifier != nil {
			WalkTok(x.AttributeSpecifier, f)
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
	case *cc.AttributeValue:
		if x == nil {
			return
		}
		if x.ArgumentExpressionList != nil {
			WalkTok(x.ArgumentExpressionList, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Prefix)
		f(x.Colon)
		f(x.Colon2)
		if x.BalancedTokenSequence != nil {
			WalkTok(x.BalancedTokenSequence, f)
		}
	case *cc.AttributeValueList:
		if x == nil {
			return
		}
		if x.AttributeValue != nil {
			WalkTok(x.AttributeValue, f)
		}
		if x.AttributeValueList != nil {
			WalkTok(x.AttributeValueList, f)
		}
		f(x.Token)
	case *cc.BalancedTokenSequence:
		if x == nil {
			return
		}
		f(x.Token)
		if x.BalancedTokenSequence != nil {
			WalkTok(x.BalancedTokenSequence, f)
		}
	case *cc.BlockItem:
		if x == nil {
			return
		}
		if x.CompoundStatement != nil {
			WalkTok(x.CompoundStatement, f)
		}
		if x.Declaration != nil {
			WalkTok(x.Declaration, f)
		}
		if x.DeclarationSpecifiers != nil {
			WalkTok(x.DeclarationSpecifiers, f)
		}
		if x.Declarator != nil {
			WalkTok(x.Declarator, f)
		}
		if x.LabelDeclaration != nil {
			WalkTok(x.LabelDeclaration, f)
		}
		if x.Statement != nil {
			WalkTok(x.Statement, f)
		}
	case *cc.BlockItemList:
		if x == nil {
			return
		}
		if x.BlockItem != nil {
			WalkTok(x.BlockItem, f)
		}
		if x.BlockItemList != nil {
			WalkTok(x.BlockItemList, f)
		}
	case *cc.CastExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.CastExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		if x.TypeName != nil {
			WalkTok(x.TypeName, f)
		}
		if y, ok := any(x.UnaryExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
	case *cc.CompoundStatement:
		if x == nil {
			return
		}
		if x.BlockItemList != nil {
			WalkTok(x.BlockItemList, f)
		}
		f(x.Token)
		f(x.Token2)
	case *cc.ConditionalExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.ConditionalExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.LogicalOrExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
	case *cc.ConstantExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.ConditionalExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
	case *cc.Declaration:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if x.DeclarationSpecifiers != nil {
			WalkTok(x.DeclarationSpecifiers, f)
		}
		if x.Declarator != nil {
			WalkTok(x.Declarator, f)
		}
		if x.InitDeclaratorList != nil {
			WalkTok(x.InitDeclaratorList, f)
		}
		if x.Initializer != nil {
			WalkTok(x.Initializer, f)
		}
		if x.StaticAssertDeclaration != nil {
			WalkTok(x.StaticAssertDeclaration, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
	case *cc.DeclarationList:
		if x == nil {
			return
		}
		if x.Declaration != nil {
			WalkTok(x.Declaration, f)
		}
		if x.DeclarationList != nil {
			WalkTok(x.DeclarationList, f)
		}
	case *cc.DeclarationSpecifiers:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if x.AlignmentSpecifier != nil {
			WalkTok(x.AlignmentSpecifier, f)
		}
		if x.DeclarationSpecifiers != nil {
			WalkTok(x.DeclarationSpecifiers, f)
		}
		if x.FunctionSpecifier != nil {
			WalkTok(x.FunctionSpecifier, f)
		}
		if x.StorageClassSpecifier != nil {
			WalkTok(x.StorageClassSpecifier, f)
		}
		f(x.Token)
		if x.TypeQualifier != nil {
			WalkTok(x.TypeQualifier, f)
		}
		if x.TypeSpecifier != nil {
			WalkTok(x.TypeSpecifier, f)
		}
	case *cc.Declarator:
		if x == nil {
			return
		}
		if x.DirectDeclarator != nil {
			WalkTok(x.DirectDeclarator, f)
		}
		if x.Pointer != nil {
			WalkTok(x.Pointer, f)
		}
	case *cc.Designation:
		if x == nil {
			return
		}
		if x.DesignatorList != nil {
			WalkTok(x.DesignatorList, f)
		}
		f(x.Token)
	case *cc.Designator:
		if x == nil {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ConstantExpression2).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
	case *cc.DesignatorList:
		if x == nil {
			return
		}
		if x.Designator != nil {
			WalkTok(x.Designator, f)
		}
		if x.DesignatorList != nil {
			WalkTok(x.DesignatorList, f)
		}
	case *cc.DirectAbstractDeclarator:
		if x == nil {
			return
		}
		if x.AbstractDeclarator != nil {
			WalkTok(x.AbstractDeclarator, f)
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.DirectAbstractDeclarator != nil {
			WalkTok(x.DirectAbstractDeclarator, f)
		}
		if x.ParameterTypeList != nil {
			WalkTok(x.ParameterTypeList, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		if x.TypeQualifiers != nil {
			WalkTok(x.TypeQualifiers, f)
		}
	case *cc.DirectDeclarator:
		if x == nil {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.Declarator != nil {
			WalkTok(x.Declarator, f)
		}
		if x.DirectDeclarator != nil {
			WalkTok(x.DirectDeclarator, f)
		}
		if x.IdentifierList != nil {
			WalkTok(x.IdentifierList, f)
		}
		if x.ParameterTypeList != nil {
			WalkTok(x.ParameterTypeList, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		if x.TypeQualifiers != nil {
			WalkTok(x.TypeQualifiers, f)
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
	case *cc.EnumSpecifier:
		if x == nil {
			return
		}
		if x.EnumTypeSpecifier != nil {
			WalkTok(x.EnumTypeSpecifier, f)
		}
		if x.EnumeratorList != nil {
			WalkTok(x.EnumeratorList, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Token4)
		f(x.Token5)
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
	case *cc.EnumTypeSpecifier:
		if x == nil {
			return
		}
		if x.SpecifierQualifierList != nil {
			WalkTok(x.SpecifierQualifierList, f)
		}
		f(x.Token)
	case *cc.Enumerator:
		if x == nil {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
	case *cc.EnumeratorList:
		if x == nil {
			return
		}
		if x.Enumerator != nil {
			WalkTok(x.Enumerator, f)
		}
		if x.EnumeratorList != nil {
			WalkTok(x.EnumeratorList, f)
		}
		f(x.Token)
	case *cc.EqualityExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.EqualityExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.RelationalExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.ExclusiveOrExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.AndExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ExclusiveOrExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.ExpressionList:
		if x == nil {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.ExpressionList != nil {
			WalkTok(x.ExpressionList, f)
		}
		f(x.Token)
	case *cc.ExpressionStatement:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.ExternalDeclaration:
		if x == nil {
			return
		}
		if x.AsmStatement != nil {
			WalkTok(x.AsmStatement, f)
		}
		if x.Declaration != nil {
			WalkTok(x.Declaration, f)
		}
		if x.FunctionDefinition != nil {
			WalkTok(x.FunctionDefinition, f)
		}
		f(x.Token)
	case *cc.FunctionDefinition:
		if x == nil {
			return
		}
		if x.CompoundStatement != nil {
			WalkTok(x.CompoundStatement, f)
		}
		if x.DeclarationList != nil {
			WalkTok(x.DeclarationList, f)
		}
		if x.DeclarationSpecifiers != nil {
			WalkTok(x.DeclarationSpecifiers, f)
		}
		if x.Declarator != nil {
			WalkTok(x.Declarator, f)
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
	case *cc.FunctionSpecifier:
		if x == nil {
			return
		}
		f(x.Token)
	case *cc.GenericAssociation:
		if x == nil {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		if x.TypeName != nil {
			WalkTok(x.TypeName, f)
		}
	case *cc.GenericAssociationList:
		if x == nil {
			return
		}
		if x.GenericAssociation != nil {
			WalkTok(x.GenericAssociation, f)
		}
		if x.GenericAssociationList != nil {
			WalkTok(x.GenericAssociationList, f)
		}
		f(x.Token)
	case *cc.GenericSelection:
		if x == nil {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.GenericAssociationList != nil {
			WalkTok(x.GenericAssociationList, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Token4)
	case *cc.IdentifierList:
		if x == nil {
			return
		}
		if x.IdentifierList != nil {
			WalkTok(x.IdentifierList, f)
		}
		f(x.Token)
		f(x.Token2)
	case *cc.InclusiveOrExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.ExclusiveOrExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.InclusiveOrExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.InitDeclarator:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if x.Asm != nil {
			WalkTok(x.Asm, f)
		}
		if x.Declarator != nil {
			WalkTok(x.Declarator, f)
		}
		if x.Initializer != nil {
			WalkTok(x.Initializer, f)
		}
		f(x.Token)
	case *cc.InitDeclaratorList:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if x.InitDeclarator != nil {
			WalkTok(x.InitDeclarator, f)
		}
		if x.InitDeclaratorList != nil {
			WalkTok(x.InitDeclaratorList, f)
		}
		f(x.Token)
	case *cc.Initializer:
		if x == nil {
			return
		}
		if y, ok := any(x.AssignmentExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.InitializerList != nil {
			WalkTok(x.InitializerList, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
	case *cc.InitializerList:
		if x == nil {
			return
		}
		if x.Designation != nil {
			WalkTok(x.Designation, f)
		}
		if x.Initializer != nil {
			WalkTok(x.Initializer, f)
		}
		if x.InitializerList != nil {
			WalkTok(x.InitializerList, f)
		}
		f(x.Token)
	case *cc.IterationStatement:
		if x == nil {
			return
		}
		if x.Declaration != nil {
			WalkTok(x.Declaration, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ExpressionList2).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ExpressionList3).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.Statement != nil {
			WalkTok(x.Statement, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Token4)
		f(x.Token5)
	case *cc.JumpStatement:
		if x == nil {
			return
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
	case *cc.LabelDeclaration:
		if x == nil {
			return
		}
		if x.IdentifierList != nil {
			WalkTok(x.IdentifierList, f)
		}
		f(x.Token)
		f(x.Token2)
	case *cc.LabeledStatement:
		if x == nil {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ConstantExpression2).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.Statement != nil {
			WalkTok(x.Statement, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
	case *cc.LogicalAndExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.InclusiveOrExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.LogicalAndExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.LogicalOrExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.LogicalAndExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.LogicalOrExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.Macro:
		if x == nil {
			return
		}
		f(x.Name)
	case *cc.MultiplicativeExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.CastExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.MultiplicativeExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.Parameter:
		if x == nil {
			return
		}
		if x.Declarator != nil {
			WalkTok(x.Declarator, f)
		}
		if x.AbstractDeclarator != nil {
			WalkTok(x.AbstractDeclarator, f)
		}
	case *cc.ParameterDeclaration:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if x.AbstractDeclarator != nil {
			WalkTok(x.AbstractDeclarator, f)
		}
		if x.DeclarationSpecifiers != nil {
			WalkTok(x.DeclarationSpecifiers, f)
		}
		if x.Declarator != nil {
			WalkTok(x.Declarator, f)
		}
	case *cc.ParameterList:
		if x == nil {
			return
		}
		if x.ParameterDeclaration != nil {
			WalkTok(x.ParameterDeclaration, f)
		}
		if x.ParameterList != nil {
			WalkTok(x.ParameterList, f)
		}
		f(x.Token)
	case *cc.ParameterTypeList:
		if x == nil {
			return
		}
		if x.ParameterList != nil {
			WalkTok(x.ParameterList, f)
		}
		f(x.Token)
		f(x.Token2)
	case *cc.Pointer:
		if x == nil {
			return
		}
		if x.Pointer != nil {
			WalkTok(x.Pointer, f)
		}
		f(x.Token)
		if x.TypeQualifiers != nil {
			WalkTok(x.TypeQualifiers, f)
		}
	case *cc.PostfixExpression:
		if x == nil {
			return
		}
		if x.ArgumentExpressionList != nil {
			WalkTok(x.ArgumentExpressionList, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.InitializerList != nil {
			WalkTok(x.InitializerList, f)
		}
		if y, ok := any(x.PostfixExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.PrimaryExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Token4)
		f(x.Token5)
		if x.TypeName != nil {
			WalkTok(x.TypeName, f)
		}
	case *cc.PrimaryExpression:
		if x == nil {
			return
		}
		if x.CompoundStatement != nil {
			WalkTok(x.CompoundStatement, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.GenericSelection != nil {
			WalkTok(x.GenericSelection, f)
		}
		f(x.Token)
		f(x.Token2)
	case *cc.RelationalExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.RelationalExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ShiftExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.SelectionStatement:
		if x == nil {
			return
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.Statement != nil {
			WalkTok(x.Statement, f)
		}
		if x.Statement2 != nil {
			WalkTok(x.Statement2, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Token4)
	case *cc.ShiftExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.AdditiveExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.ShiftExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
	case *cc.SpecifierQualifierList:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if x.AlignmentSpecifier != nil {
			WalkTok(x.AlignmentSpecifier, f)
		}
		if x.SpecifierQualifierList != nil {
			WalkTok(x.SpecifierQualifierList, f)
		}
		if x.TypeQualifier != nil {
			WalkTok(x.TypeQualifier, f)
		}
		if x.TypeSpecifier != nil {
			WalkTok(x.TypeSpecifier, f)
		}
	case *cc.Statement:
		if x == nil {
			return
		}
		if x.AsmStatement != nil {
			WalkTok(x.AsmStatement, f)
		}
		if x.CompoundStatement != nil {
			WalkTok(x.CompoundStatement, f)
		}
		if x.ExpressionStatement != nil {
			WalkTok(x.ExpressionStatement, f)
		}
		if x.IterationStatement != nil {
			WalkTok(x.IterationStatement, f)
		}
		if x.JumpStatement != nil {
			WalkTok(x.JumpStatement, f)
		}
		if x.LabeledStatement != nil {
			WalkTok(x.LabeledStatement, f)
		}
		if x.SelectionStatement != nil {
			WalkTok(x.SelectionStatement, f)
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
	case *cc.StaticAssertDeclaration:
		if x == nil {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		f(x.Token4)
		f(x.Token5)
	case *cc.StorageClassSpecifier:
		if x == nil {
			return
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
	case *cc.StructDeclaration:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if x.SpecifierQualifierList != nil {
			WalkTok(x.SpecifierQualifierList, f)
		}
		if x.StaticAssertDeclaration != nil {
			WalkTok(x.StaticAssertDeclaration, f)
		}
		if x.StructDeclaratorList != nil {
			WalkTok(x.StructDeclaratorList, f)
		}
		f(x.Token)
	case *cc.StructDeclarationList:
		if x == nil {
			return
		}
		if x.StructDeclaration != nil {
			WalkTok(x.StructDeclaration, f)
		}
		if x.StructDeclarationList != nil {
			WalkTok(x.StructDeclarationList, f)
		}
	case *cc.StructDeclarator:
		if x == nil {
			return
		}
		if y, ok := any(x.ConstantExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.Declarator != nil {
			WalkTok(x.Declarator, f)
		}
		f(x.Token)
	case *cc.StructDeclaratorList:
		if x == nil {
			return
		}
		if x.StructDeclarator != nil {
			WalkTok(x.StructDeclarator, f)
		}
		if x.StructDeclaratorList != nil {
			WalkTok(x.StructDeclaratorList, f)
		}
		f(x.Token)
	case *cc.StructOrUnion:
		if x == nil {
			return
		}
		f(x.Token)
	case *cc.StructOrUnionSpecifier:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		if x.AttributeSpecifierList2 != nil {
			WalkTok(x.AttributeSpecifierList2, f)
		}
		if x.StructDeclarationList != nil {
			WalkTok(x.StructDeclarationList, f)
		}
		if x.StructOrUnion != nil {
			WalkTok(x.StructOrUnion, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
	case *cc.TranslationUnit:
		if x == nil {
			return
		}
		if x.ExternalDeclaration != nil {
			WalkTok(x.ExternalDeclaration, f)
		}
		if x.TranslationUnit != nil {
			WalkTok(x.TranslationUnit, f)
		}
	case *cc.TypeName:
		if x == nil {
			return
		}
		if x.AbstractDeclarator != nil {
			WalkTok(x.AbstractDeclarator, f)
		}
		if x.SpecifierQualifierList != nil {
			WalkTok(x.SpecifierQualifierList, f)
		}
	case *cc.TypeQualifier:
		if x == nil {
			return
		}
		if x.AttributeSpecifierList != nil {
			WalkTok(x.AttributeSpecifierList, f)
		}
		f(x.Token)
	case *cc.TypeQualifiers:
		if x == nil {
			return
		}
		if x.TypeQualifier != nil {
			WalkTok(x.TypeQualifier, f)
		}
		if x.TypeQualifiers != nil {
			WalkTok(x.TypeQualifiers, f)
		}
	case *cc.TypeSpecifier:
		if x == nil {
			return
		}
		if x.AtomicTypeSpecifier != nil {
			WalkTok(x.AtomicTypeSpecifier, f)
		}
		if x.EnumSpecifier != nil {
			WalkTok(x.EnumSpecifier, f)
		}
		if y, ok := any(x.ExpressionList).(cc.Node); ok {
			WalkTok(y, f)
		}
		if x.StructOrUnionSpecifier != nil {
			WalkTok(x.StructOrUnionSpecifier, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		if x.TypeName != nil {
			WalkTok(x.TypeName, f)
		}
	case *cc.UnaryExpression:
		if x == nil {
			return
		}
		if y, ok := any(x.CastExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		if y, ok := any(x.PostfixExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
		f(x.Token)
		f(x.Token2)
		f(x.Token3)
		if x.TypeName != nil {
			WalkTok(x.TypeName, f)
		}
		if y, ok := any(x.UnaryExpression).(cc.Node); ok {
			WalkTok(y, f)
		}
	default:
		walkTokReflect(n, f)
	}
}
