package p037

// Whim phase 37 (formerly 98) -- the character classes, the numbers and the sort.  See GOAL.md.
//
// THE CHARTER SAYS "no musl dependencies in `whim-vim.c` itself".  Phase 36 took the
// strings; this takes everything else that is PURE COMPUTATION -- a function of its
// arguments that asks the operating system nothing -- and defines it in the file, as
// plain C, with no preprocessor and no comment.  Eleven undefined symbols go:
//
// character classes  tolower toupper towlower towupper isalnum iscntrl ispunct
// numbers            atoi atol
// sorting            qsort bsearch
//
// AND `nm -u` IS NOT THE SCOPE, which is the whole reason this phase is bigger than
// that list.  musl spells six more classifiers as FUNCTION-LIKE MACROS in
// <ctype.h> -- `isalpha isdigit isgraph islower isupper`, and `isspace` through
// `__isspace` -- so a source that calls them produces no undefined symbol at all.
// Five of them are live here, at 17 sites, and until they go <ctype.h> cannot.  A
// phase scoped by `nm -u` would look finished and leave record 99 unable to move.
//
// <wctype.h> HAS A THIRD USER AND IT IS A DEAD STATEMENT.  `iswupper` is named once,
// at the line after `return utf_isupper(c);` inside `vim_isupper` -- the residue of
// whim folding `if (enc_utf8)` to always-true.  gcc drops the unreachable block even
// at -O0, which is why the name is in the source and not in `nm -u`.  It is deleted
// rather than vendored, and that is measured rather than asserted: same file name,
// SOURCE_DATE_EPOCH=0, the binary is BYTE-IDENTICAL either side.
//
// NOTHING IN tools/sweep.sh COVERS AN UNREACHABLE STATEMENT, and that is a gap worth
// naming rather than a thing to fix here.  gcc's -Wunreachable-code has been a no-op
// since gcc 4.5 and is not in -Wall -Wextra; tools/deadsweep.py acts on warnings;
// funcreach.py and typereach.py read DEFINITIONS, and `iswupper` is a libc name with
// no definition in this file.  Measured: `whim-vim.c` holds EIGHTEEN statements that
// cannot run, and exactly ONE of them names a libc symbol.  This phase takes that
// one.  The other seventeen are a phase of their own: three of them are the folded
// Latin-1 arms of these same four functions, and deleting those would orphan
// `latin1flags`, `latin1upper` and `latin1lower` -- which would turn a vendoring
// phase into a cut.
//
// WHY towupper AND towlower ARE THE HARD ONES, and what was measured before choosing.
// Their one live arm each is `if (!(cmp_flags & CMP_INTERNAL)) return towupper(a);`
// inside `utf_toupper`/`utf_tolower`, and `'casemap'` defaults to
// "internal,keepascii" -- so the obvious reading is "unreachable unless the user
// types `:set casemap=`".  THAT READING IS WRONG.  An instrumented build marks 104
// of the 106 records of a full recording, 892 times in one trivial session: the
// caller is `utf_islower`/`utf_isupper` from `buf_init_chartab()`, running BEFORE
// 'casemap' has been applied, with `cmp_flags` still its static zero and arguments
// in exactly 128..255.  They classify the whole Latin-1 range at startup.
//
// FOUR ANSWERS WERE BUILT AND RECORDED.  musl implements them with a two-level
// base-6 packed table (src/ctype/casemap.h, 297 lines) and forty lines of bit
// arithmetic: exact, and the opposite of "obvious, simple, idiomatic C".  Routing
// them to vim's own table instead costs 96 upper and 96 lower codepoints above
// U+00FF and is a declared behaviour change.  An ASCII-only fallback misclassifies
// 62 of 128 Latin-1 bytes at startup and EVERY HARNESS HERE SAYS IT IS FINE, because
// 'isprint' ("@,161-255") and 'iskeyword' ("@,48-57,_,192-255") re-cover the same
// bytes by range -- which is why that one is rejected with a number rather than an
// opinion.  What runs is the fourth: musl's mapping RANGE-COMPRESSED INTO THE SHAPE
// THIS FILE ALREADY HAS, 187 + 171 `convertStruct` rows read by `utf_convert()`, the
// same size as vim's own 198 + 183 and read by the same function.  Exact, and in the
// file's own idiom.
//
// THE TWO DATA FILES WERE NOT REMEMBERED CONSTANTS while the test suite stood
// (448e9a8): musl-case.md's table was generated by `muslcase --generate`, which
// read THIS MACHINE'S libc, and `--verify` re-derived every one of the 1,114,112
// codepoints from the same authority; muslctype compiled musl-ctype.md's
// seventeen functions OUT OF THE SOURCE THIS PHASE PRODUCED and ran them beside
// libc's.  Both tools went with the suite; the data is what they last verified.
//
// THREE ANCHORS AND SIXTEEN COUNTED REWRITES.
//
// A  the seventeen functions and two prototypes, at the END OF THE BLOCK PHASE 36
// STARTED -- between the last #include and the enum wall -- so the file has one
// vendored block and not two.  The anchor is the junction itself, the end of
// `musl_fmtptr` and the first enum.  The prototypes are needed only because the
// two DEAD `return towupper(c);` mentions are rewritten too and sit below.
//
// THE SEVENTEEN USE THE FILE'S TWO-LINE DEFINITION STYLE, and that is mechanical
// rather than cosmetic.  tools/funcreach.py finds a definition with
// `^([A-Za-z_]\w*)\(...\)$` -- the NAME at column 0, which is what
// `    static int` on its own line gives.  Phase 36 wrote one-line headers
// (`static void *musl_memcpy(...)`), and MEASURED, funcreach.py sees 1,719
// definitions on this phase's input, exactly as it did before phase 36 ran: not
// one of its nineteen is in the reachability graph.  Nothing is wrong today --
// the block calls nothing funcreach tracks, and gcc's -Wunused-function still
// covers a dead one -- but a function written that way is outside the sweep, so
// these seventeen are written the way the other 1,719 are.
// B  the two tables and their wrappers, after vim's own `toUpper[]` -- so musl's
// sit beside vim's and `utf_convert()` is already declared above them.
// C  `return iswupper(c);`, deleted.
// D  sixteen call-site rewrites, each counted file-wide, applied ONLY to the text
// after the inserted block so that the block's own bodies are never rewritten.
//
// THE DECLARED DELTA IS NOTHING AT ALL, and it is the third kind of empty
// declaration this pipeline has.  Phase 31's was code that could not run; phase 35's
// was a possibility that had never existed; THIS ONE IS AN EQUALITY -- the code runs
// constantly and computes the same answer, so the evidence is equivalence rather
// than unreachability, and every probe is a MUST-NOT-DIFFER.
// The flags are read out of the boundary's makefile rather than written here a
// second time: the core's compile line is the boundary's (GOALS.md core rule 8).  The
// check needs the binary this phase was HANDED, to run its probes on both sides.
//
// ON THE GRAPH (doc/GRAPH-MIGRATION.md, B3c).  The three anchors are the
// graph's: the block goes after musl_fmtptr()'s definition, checked to be
// phase 36's last with the enum wall after it; the tables after toUpper[]'s;
// the dead `return iswupper(c);` is cut as a form.  Section D is no longer
// a regexp over the text below the block: every call of the seventeen is a
// use of a header's declaration, retargeted to its musl_ definition -- the
// block's own bodies call musl_ names and cannot be reached -- and the five
// classifiers musl's <ctype.h> spells as macros are invocations
// `(macro "isupper (c)")`, each made the call `musl_isupper(c)` by MACROX.
// The counts are the text's, on the C view.

import (
	_ "embed"
	"fmt"
	"io"
	"regexp"
	"strings"

	"github.com/arbace/go-whim/crefactor/clisp"
	"github.com/arbace/go-whim/crefactor/edit"
	"github.com/arbace/go-whim/crefactor/graph"
	"github.com/arbace/go-whim/internal/phase"
)

// The two blocks this phase splices in, kept beside it as data (musl-ctype.md,
// musl-case.md): each file's fenced block, byte for byte.
//
//go:embed musl-ctype.md
var muslCtypeMD string

//go:embed musl-case.md
var muslCaseMD string

// fenced is the one fenced block of a data file, byte for byte: everything
// between the opening ```c line and the closing ``` line, its last newline
// included.
func fenced(md string) (string, bool) {
	i := strings.Index(md, "```c\n")
	if i < 0 {
		return "", false
	}
	body := md[i+len("```c\n"):]
	j := strings.Index(body, "\n```\n")
	if j < 0 || strings.Contains(body[j+len("\n```\n"):], "```") {
		return "", false
	}
	return body[:j+1], true
}

func init() { phase.RegisterGraph("whim37", Edit) }

var w37Before = map[string]int{
	"tolower": 2, "toupper": 2, "towlower": 2, "towupper": 2,
	"isalnum": 2, "iscntrl": 1, "ispunct": 1,
	"isalpha": 3, "isdigit": 7, "isgraph": 1, "islower": 1, "isupper": 5,
	"iswupper": 1, "isspace": 0, "isprint": 0,
	"atoi": 7, "atol": 3, "strtol": 0, "qsort": 1, "bsearch": 4,
	"utf_convert": 4, "sort_strings": 3, "sort_compare": 1,
}

// w37Free are the twenty musl_ names this phase defines.  This file is ONE
// namespace and a silent collision between a tentative definition and a vendored
// one is exactly what CLAUDE.md warns about, so each is required to be free.
var w37Free = []string{"musl_isdigit", "musl_isalpha", "musl_isupper", "musl_islower",
	"musl_isgraph", "musl_isspace", "musl_isalnum", "musl_iscntrl",
	"musl_ispunct", "musl_tolower", "musl_toupper", "musl_atoi",
	"musl_atol", "musl_strtol", "musl_bsearch", "musl_qsort", "musl_towupper",
	"musl_towlower", "musl_toUpper", "musl_toLower"}

// w37Rewrite is the seventeen names rewritten BELOW the inserted block.  How
// many call sites each has is READ from the input: w37Before is the input this
// was written against, and upstream moving one atol to strtol (vim 9.2.1122's
// getdigits) made every count there a refusal of a correct phase.
var w37Rewrite = []string{
	"tolower", "toupper", "towlower", "towupper",
	"isalnum", "iscntrl", "ispunct",
	"isalpha", "isdigit", "isgraph", "islower", "isupper",
	"atoi", "atol", "strtol", "qsort", "bsearch",
}

// w37Provided is everything <ctype.h> and <wctype.h> could still be providing.
var w37Provided = strings.Fields(
	"isalnum isalpha isblank iscntrl isdigit isgraph islower isprint " +
		"ispunct isspace isupper isxdigit isascii toascii tolower toupper " +
		"iswalnum iswalpha iswblank iswcntrl iswdigit iswgraph iswlower " +
		"iswprint iswpunct iswspace iswupper iswxdigit towlower towupper " +
		"towctrans wctrans wctype iswctype")

var w37Dead = regexp.MustCompile(`(?m)^ *return utf_is(?:upper|lower)\(c\);\n *if \(c >= 0x100\)$`)

// Edit vendors the character classes, the two ato*, qsort and bsearch.
func Edit(e *graph.Editor, w io.Writer, _ []string) error {
	v := graph.NewVerbs("vendor", e, w)
	text := v.Text()
	nInc := edit.IncludeCount(text) // the headers it was handed (phase 88 drops the unused)

	// ---- 0. the input's calls, READ ---------------------------------------------
	// iswupper's one call is a fact the phase depends on -- section C deletes
	// exactly that statement -- and so is `isspace` and `isprint` having none.
	calls := map[string]int{}
	var shape []string
	for _, name := range edit.SortedKeys(w37Before) {
		calls[name] = edit.CoreCalls(text, name)
		shape = append(shape, fmt.Sprintf("%s %d", name, calls[name]))
	}
	if calls["iswupper"] != 1 || calls["isspace"] != 0 || calls["isprint"] != 0 {
		v.Die("iswupper is called %d times, isspace %d and isprint %d: this phase deletes "+
			"the one iswupper and adds nothing for the other two", calls["iswupper"],
			calls["isspace"], calls["isprint"])
		return v.Done()
	}
	v.Say("the input's calls: " + strings.Join(shape, ", "))

	for _, name := range w37Free {
		if edit.WordPatternCount(text, name) > 0 {
			v.Die("%s already exists in the file", name)
			return v.Done()
		}
	}
	v.Say("the twenty musl_ names this phase defines are all free")

	// ---- THE INVARIANT, COMPUTED BEFORE ANYTHING IS INSERTED ------------------
	if k := len(w37Dead.FindAll(text, -1)); k != 2 {
		v.Die("the two dead `if (c >= 0x100)` arms of vim_isupper/vim_islower are not "+
			"where this phase found them (%d)", k)
		return v.Done()
	}
	v.Say("vim_isupper and vim_islower still open with `return utf_is*(c);` followed by an " +
		"unreachable `if (c >= 0x100)` -- which is the shape that makes iswupper a name " +
		"in the source and not a symbol in the object")

	// The calls section D rewrites, found before anything is inserted: the
	// uses of the header's declarations that are callees, and the
	// invocations of the classifiers that are macros.
	rewrite := map[string]bool{}
	for _, r := range w37Rewrite {
		rewrite[r] = true
	}
	type w37Call struct {
		use  *graph.Node
		name string
	}
	var direct []w37Call
	var macros []*graph.Node
	found := map[string]int{}
	for _, r := range w37Rewrite {
		for _, d := range e.Decls(r) {
			if !d.Is("extern") {
				continue
			}
			for _, u := range e.Uses(d) {
				if c := e.Parent(u); c != nil && c.Is("call") && c.Kids[1] == u {
					direct = append(direct, w37Call{u, r})
					found[r]++
				}
			}
		}
	}
	for _, f := range e.Graph().Forms {
		graph.Walk(f, func(x *graph.Node) bool {
			if name, _, ok := graph.MacroCall(x); ok && rewrite[name] {
				macros = append(macros, x)
				found[name]++
			}
			return true
		})
	}

	// ---- A. the eighteen functions, after phase 36's block ---------------------
	block, ok := fenced(muslCtypeMD)
	if !ok {
		v.Die("musl-ctype.md does not hold exactly one fenced block")
		return v.Done()
	}
	// THE BLOCK JOINS PHASE 36'S RATHER THAN STARTING A SECOND ONE, so the anchor
	// is that JUNCTION -- the end of its last definition and the first enum --
	// and not a line of its own.
	const w37Tail = "    dest[18] = '\\0';\n    return 18;\n}\n"
	const w37Wall = "\nenum { BH_DIRTY = 1 };\n"
	what := "the eighteen functions go at the END OF PHASE 36's BLOCK, before the " +
		"enum wall -- one vendored block and not two -- defined before every " +
		"use, so only the two dead tow* mentions need a prototype"
	last := e.Defn("musl_fmtptr")
	if k := strings.Count(string(text), w37Tail+w37Wall); k != 1 || last == nil ||
		!graph.Matches(clisp.MustPattern("(enum (BH_DIRTY 1))"), e.Sibling(last, 1)) {
		v.Die("%s -- the text occurs %d times, expected 1: %s", what, k, edit.PyRepr(edit.CoreHead(w37Tail+w37Wall, 70)))
		return v.Done()
	}
	if _, err := e.SpliceC(graph.Frag{At: e.SpotAfter(last), Src: block}); err != nil {
		v.Die("%s -- %v", what, err)
		return v.Done()
	}
	v.Say(what)

	// ---- B. the two tables, beside vim's own ----------------------------------
	caseB, ok := fenced(muslCaseMD)
	if !ok {
		v.Die("musl-case.md does not hold exactly one fenced block")
		return v.Done()
	}
	const w37ToUpperEnd = "    {0x1e922, 0x1e943, 1, -34},\n};\n"
	what = "musl's case mapping as 187 + 171 convertStruct rows, after vim's own " +
		"toUpper[] -- the same shape, the same size, and read by the " +
		"utf_convert() that is already declared above them"
	if k := strings.Count(string(text), w37ToUpperEnd); k != 1 {
		v.Die("%s -- the text occurs %d times, expected 1: %s", what, k, edit.PyRepr(edit.CoreHead(w37ToUpperEnd, 70)))
		return v.Done()
	}
	v.TopAfterC("toUpper", caseB, what)

	// ---- C. the dead statement ------------------------------------------------
	v.Cut("(return (call iswupper c))", 1,
		"vim_isupper's `return iswupper(c);`, which cannot run and is "+
			"<wctype.h>'s last user besides the two this phase vendors -- deleting "+
			"it is byte-identical, measured with SOURCE_DATE_EPOCH=0")
	if v.Failed() {
		return v.Done()
	}

	// ---- D. the call sites, counted -------------------------------------------
	// The block's own bodies -- musl_ispunct calls musl_isalnum, musl_atoi
	// calls musl_isdigit -- name musl_ functions and are no use of a header's
	// declaration, so nothing here can rewrite them: what the text got by
	// rewriting only BELOW the block.
	total := 0
	for _, r := range w37Rewrite {
		if found[r] != calls[r] {
			v.Die("%s is called %d times below the inserted block, and %d times in the input",
				r, found[r], calls[r])
			return v.Done()
		}
		total += found[r]
	}
	for _, c := range direct {
		to := e.Defn("musl_" + c.name)
		if to == nil {
			v.Die("musl_%s is not defined", c.name)
			return v.Done()
		}
		if err := e.RetargetAs(c.use, 0, to); err != nil {
			v.Die("%s: %v", c.name, err)
			return v.Done()
		}
		// the call's type is the musl_ function's result now (int, where
		// towupper's is wint_t): typed again, as an import types it
		e.Rederive(e.Parent(c.use))
	}
	// THE WHOLE INVOCATION IS REPLACED, not prefixed: a call written
	// `isupper (c)` is `musl_isupper(c)`, as the text's regexp wrote it.
	quiet := graph.NewVerbs("vendor", e, io.Discard)
	quiet.ExpandMacros(w37Rewrite, func(name string, args []string) (string, error) {
		return "musl_" + name + "(" + strings.Join(args, ", ") + ")", nil
	}, len(macros), "the classifiers <ctype.h> spells as macros")
	if quiet.Err != nil {
		return quiet.Err
	}
	v.Say(fmt.Sprintf("seventeen names rewritten at the counts read above -- %d call sites, every one "+
		"of them BELOW the block, so no vendored body rewrites itself", total))
	text = v.Text()
	if k := edit.CoreCalls(text, "strtol"); k != 0 {
		v.Die("strtol is still called %d times, and <stdlib.h> would keep providing it", k)
		return v.Done()
	}

	// ---- what the collection is handed, as a count rather than as trust -------
	var left []string
	for _, n := range w37Provided {
		if edit.CoreCalls(text, n) > 0 {
			left = append(left, n)
		}
	}
	if len(left) > 0 {
		v.Die("<ctype.h>/<wctype.h> still has a user and record 99 could not remove it: %s",
			strings.Join(left, " "))
		return v.Done()
	}
	for _, tn := range []string{"wint_t", "wctype_t", "wctrans_t"} {
		if regexp.MustCompile(`\b` + tn + `\b`).Match(text) {
			v.Die("%s is still named, and it is <wctype.h>'s", tn)
			return v.Done()
		}
	}
	v.Say("nothing <ctype.h> or <wctype.h> provides is called anywhere, and no wint_t, " +
		"wctype_t or wctrans_t is named -- which is the contract record 99 removes the " +
		"two headers on, asserted here so that a miss fails THIS phase")
	if edit.CoreCalls(text, "iswupper") > 0 || regexp.MustCompile(`\biswupper\b`).Match(text) {
		v.Die("iswupper survives")
		return v.Done()
	}
	var directives, bad []string
	for _, l := range strings.Split(string(text), "\n") {
		if strings.HasPrefix(l, "#") {
			directives = append(directives, l)
			if !strings.HasPrefix(l, "#include <") {
				bad = append(bad, l)
			}
		}
	}
	if len(directives) != nInc || len(bad) > 0 {
		v.Die("the directives are no longer 18 #includes of a system header: %d, %s",
			len(directives), strings.Join(bad, " "))
		return v.Done()
	}
	v.Say("18 directives, every one an #include of a system header -- this phase adds no " +
		"preprocessor and removes none; the two it makes unnecessary are record 99's")
	return v.Done()
}
