package p093

// The multi-line literals internal/phase/093/edit.go matches on, EXTRACTED from the phase's
// heredoc by tools/gocmp/genlits.py rather than retyped.  They carry BLANK
// LINES, which a filtered read of a phase program does not show, and a
// literal that is 90%% right matches nothing.  See that tool for the
// measurement.
const (
	w93lit3  = "    CMD_file,\n"
	w93lit4  = "    if (!(ea.argt & (EX_CMDWIN | EX_LOCK_OK)) && ea.cmdidx != CMD_file && curbuf_locked())\n"
	w93lit5  = "    if (!(ea.argt & (EX_CMDWIN | EX_LOCK_OK)) && curbuf_locked())\n"
	w93lit6  = "    if (ea.cmdidx == CMD_file && *ea.arg != NUL && curbuf_locked())\n    {\n        goto doend;\n    }\n"
	w93lit7  = "static buf_T *buflist_new(char_u *ffname_arg, char_u *sfname_arg, linenr_T lnum, int flags);\n"
	w93lit8  = "static buf_T *buflist_new(linenr_T lnum, int flags);\n"
	w93lit9  = "buflist_new(char_u *ffname_arg, char_u *sfname_arg, linenr_T lnum, int flags)\n"
	w93lit10 = "buflist_new(linenr_T    lnum, int         flags)\n"
	w93lit11 = "    char_u *ffname = ffname_arg;\n    char_u *sfname = sfname_arg;\n    buf_T *buf;\n    stat_T st;\n"
	w93lit12 = "    buf_T       *buf;\n"
	w93lit13 = "    fname_expand(curbuf, &ffname, &sfname);\n    if (sfname == NULL || stat(((char *)sfname), (&st)) < 0)\n    {\n        st.st_dev = (dev_t)-1;\n    }\n    if (ffname != NULL && !(flags & (BLN_DUMMY | BLN_NEW)) && (buf = buflist_findname_stat(ffname, &st)) != NULL)\n    {\n        vim_free(ffname);\n        if (lnum != 0)\n        {\n            buflist_setfpos(buf, (flags & BLN_NOCURWIN) ? NULL : curwin, lnum, (colnr_T)0, FALSE);\n        }\n        if ((flags & BLN_NOOPT) == 0)\n        {\n            buf_copy_options(buf, 0);\n        }\n        return buf;\n    }\n"
	w93lit14 = "        if (buf == NULL)\n        {\n            vim_free(ffname);\n            return NULL;\n        }\n"
	w93lit15 = "        if (buf == NULL)\n        {\n            return NULL;\n        }\n"
	w93lit16 = "    if (ffname != NULL)\n    {\n        buf->b_ffname = ffname;\n        buf->b_sfname = vim_strsave(sfname);\n    }\n"
	w93lit17 = "    if ((ffname != NULL && (buf->b_ffname == NULL || buf->b_sfname == NULL)) || buf->b_wininfo == NULL)\n    {\n        if (buf->b_sfname != buf->b_ffname)\n        {\n            vim_free(buf->b_sfname);\n            (buf->b_sfname) = NULL;\n        }\n        else\n        {\n            buf->b_sfname = NULL;\n        }\n        vim_free(buf->b_ffname);\n        (buf->b_ffname) = NULL;\n        if (buf != curbuf)\n"
	w93lit18 = "    if (buf->b_wininfo == NULL)\n    {\n        if (buf != curbuf)\n"
	w93lit19 = "    buf->b_fname = buf->b_sfname;\n"
	w93lit20 = "    if (st.st_dev == (dev_t)-1)\n    {\n        buf->b_dev_valid = false;\n    }\n    else\n    {\n        buf->b_dev_valid = true;\n        buf->b_dev = st.st_dev;\n        buf->b_ino = st.st_ino;\n    }\n"
	w93lit21 = "    buf->b_dev_valid = false;\n"
	w93lit22 = "    curbuf = buflist_new(NULL, NULL, 1L, BLN_LISTED);\n"
	w93lit23 = "    curbuf = buflist_new(1L, BLN_LISTED);\n"
	w93lit24 = "        char_u *fname = buf->b_fname != NULL ? buf->b_fname : buf->b_ffname;\n        semsg(_(e_attempt_to_delete_buffer_that_is_in_use_str), fname != NULL ? fname : (char_u *)\"[No Name]\");\n"
	w93lit25 = "        semsg(_(e_attempt_to_delete_buffer_that_is_in_use_str), (char_u *)\"[No Name]\");\n"
	w93lit26 = "    char_u *fname;\n    linenr_T dummy;\n    if (buflist_name_nr(0, &fname, &dummy) == FAIL)\n    {\n        if (errmsg)\n        {\n            emsg(_(e_no_alternate_file));\n        }\n        return NULL;\n    }\n    return fname;\n"
	w93lit27 = "    if (errmsg)\n    {\n        emsg(_(e_no_alternate_file));\n    }\n    return NULL;\n"
	w93lit28 = "    if (name != NULL)\n"
	w93lit29 = "buf_spname(buf_T *buf)\n{\n    if (buf->b_fname == NULL)\n    {\n        return buf_get_fname(buf);\n    }\n    return NULL;\n}\n"
	w93lit30 = "buf_spname(buf_T *buf)\n{\n    return buf_get_fname(buf);\n}\n"
	w93lit31 = "buf_get_fname(buf_T *buf)\n{\n    if (buf->b_fname == NULL)\n    {\n        return (char_u *)_(\"[No Name]\");\n    }\n    return buf->b_fname;\n}\n"
	w93lit32 = "buf_get_fname(buf_T *buf)\n{\n    return (char_u *)_(\"[No Name]\");\n}\n"
	w93lit33 = "        if (semsg(_(e_no_write_since_last_change_for_buffer_str), buf_spname(buf) != NULL ? buf_spname(buf) : buf->b_fname))\n"
	w93lit34 = "        if (semsg(_(e_no_write_since_last_change_for_buffer_str), buf_spname(buf)))\n"
	w93lit35 = "check_fname(void)\n{\n    if (curbuf->b_ffname == NULL)\n    {\n        emsg(_(e_no_file_name));\n        return FAIL;\n    }\n    return OK;\n}\n"
	w93lit36 = "check_fname(void)\n{\n    emsg(_(e_no_file_name));\n    return FAIL;\n}\n"
	w93lit37 = "    return file_name_in_line(ml_get_curline(), curwin->w_cursor.col, options, count, curbuf->b_ffname, file_lnum);\n"
	w93lit38 = "    return file_name_in_line(ml_get_curline(), curwin->w_cursor.col, options, count, NULL, file_lnum);\n"
	w93lit39 = "    if (buf->b_ffname == NULL)\n"
	w93lit40 = "        *argp = curbuf->b_fname;\n"
	w93lit41 = "        *argp = NULL;\n"
	w93lit42 = "    if (buf_spname(buf) != NULL)\n"
	w93lit43 = "            if (eap->argt & (EX_CTRLV | EX_XFILE))\n"
	w93lit44 = "            if (eap->argt & EX_CTRLV)\n"
	w93lit45 = "static int readonlymode = FALSE;\n"
	w93lit46 = "    char_u dirname[PATH_MAX];\n    buf_T *buf;\n    mch_dirname(dirname, PATH_MAX);\n    buf = curbuf;\n    shorten_buf_fname(buf, dirname, force);\n"
	w93lit47 = "static void shorten_fnames(int force);\n"
	w93lit48 = "static void shorten_fnames(void);\n"
	w93lit49 = "shorten_fnames(int force)\n"
	w93lit50 = "shorten_fnames(void)\n"
	w93lit51 = "    shorten_fnames(FALSE);\n"
	w93lit52 = "    shorten_fnames();\n"
)
