(* Code generated by `go tool whim skel -ml` from a C translation unit; DO NOT EDIT. *)

(* The core's interface: what a host makes an editor with, and what it
   calls back. *)

(* The C's enumerations whose values are only named, compared and matched:
   variants. *)
type cmd_addr = Addr_lines | Addr_windows | Addr_unsigned | Addr_other | Addr_none
type etype = Etype_top | Etype_args | Etype_internal
type flush_buffers = Flush_minimal | Flush_input
type keyprot = Keyprotocol_none | Keyprotocol_mok2 | Keyprotocol_kitty | Keyprotocol_fail
type optmagic = Option_magic_not_set | Option_magic_on | Option_magic_off
type paste_mode = Paste_insert | Paste_cmdline | Paste_ex | Paste_one_char
type set_op = Op_none | Op_adding | Op_prepending | Op_removing

(* The C's structs no byte of which is ever memory: records. *)
type bufref = { mutable br_buf : int; mutable br_fnum : int; mutable br_buf_free_count : int }
type chartabsize = { mutable cts_win : int; mutable cts_line : int; mutable cts_ptr : int; mutable cts_vcol : int; mutable cts_max_head_vcol : int }
type lineoff = { mutable lnum : int; mutable height : int }
type searchstat = { mutable cur : int; mutable cnt : int; mutable exact_match : bool; mutable incomplete : int; mutable last_maxcount : int }
type ttyinfo = { mutable backspace : int; mutable enter : int; mutable interrupt : int; mutable nl_does_cr : bool }

(* The host's functions, as the core calls them: the editor carries them. *)
type glue = {
  host_alloc : ed -> int -> int;
  host_exit : ed -> int -> unit;
  host_message : ed -> int -> int -> int -> unit;
  host_raise : ed -> int -> unit;
  host_time : ed -> int;
  host_write : ed -> int -> int -> int;
  musl_delay : ed -> int -> int -> unit;
  musl_get_winsize : ed -> int -> int -> int;
  musl_host_init : ed -> unit;
  musl_now_ms : ed -> int;
  musl_read_input : ed -> int -> int -> int;
  musl_suspend : ed -> unit;
  musl_term_start : ed -> unit;
  musl_term_stop : ed -> unit;
  musl_tty_keys : ed -> int -> int -> int -> int -> int -> int;
  musl_wait_for_input : ed -> int -> int;
  vim_snprintf : ed -> int -> int -> int -> int list -> int;
}

(* The C's file-scope objects the editor keeps as its fields. *)
and state

and ed = (glue, state) Rt.ed

(* A new editor on the host's functions. *)
val new_editor : glue -> ed
val vim_main : ed -> int -> int -> int
val deathtrap : ed -> int -> unit
val emsg : ed -> int -> int
val iemsg : ed -> int -> unit
val emsg_iobuff_room : ed -> int
val iobuff_or : ed -> int -> int
val utfc_ptr2len : ed -> int -> int
val utf_ptr2cells : ed -> int -> int
val iobuff : ed -> int
