(* Code generated by `go tool whim skel -ml` from a C translation unit; DO NOT EDIT. *)

(* The core's interface: what a host makes an editor with, and what it
   calls back. *)

(* The host's functions, as the core calls them: the editor carries them. *)
type glue = {
  host_alloc : ed -> int -> int;
  host_exit : ed -> int -> unit;
  host_message : ed -> int -> int -> int -> unit;
  host_raise : ed -> int -> unit;
  host_time : ed -> int;
  host_write : ed -> int -> int -> int;
  musl_delay : ed -> int -> int -> unit;
  musl_get_winsize : ed -> int -> int -> int;
  musl_host_init : ed -> unit;
  musl_now_ms : ed -> int;
  musl_read_input : ed -> int -> int -> int;
  musl_suspend : ed -> unit;
  musl_term_start : ed -> unit;
  musl_term_stop : ed -> unit;
  musl_tty_keys : ed -> int -> int -> int -> int -> int -> int;
  musl_wait_for_input : ed -> int -> int;
  vim_snprintf : ed -> int -> int -> int -> int list -> int;
}

(* The C's file-scope objects the editor keeps as its fields. *)
and state

and ed = (glue, state) Rt.ed

(* A new editor on the host's functions. *)
val new_editor : glue -> ed
val vim_main : ed -> int -> int -> int
val deathtrap : ed -> int -> unit
val emsg : ed -> int -> int
val iemsg : ed -> int -> unit
val emsg_iobuff_room : ed -> int
val iobuff_or : ed -> int -> int
val utfc_ptr2len : ed -> int -> int
val utf_ptr2cells : ed -> int -> int
val iobuff : ed -> int
