(* Code generated by `go tool whim skel -ml` from a C translation unit; DO NOT EDIT. *)

(* The core's interface: what a host makes an editor with, and what it
   calls back. *)

(* The C's enumerations whose values are only named, compared and matched:
   variants. *)
type cmd_addr = Addr_lines | Addr_windows | Addr_unsigned | Addr_other | Addr_none
type etype = Etype_top | Etype_args | Etype_internal
type flush_buffers = Flush_minimal | Flush_input
type keyprot = Keyprotocol_none | Keyprotocol_mok2 | Keyprotocol_kitty | Keyprotocol_fail
type optmagic = Option_magic_not_set | Option_magic_on | Option_magic_off
type paste_mode = Paste_insert | Paste_cmdline | Paste_ex | Paste_one_char
type set_op = Op_none | Op_adding | Op_prepending | Op_removing

(* The C's structs no byte of which is ever memory: records. *)
type bufref = { mutable br_buf : int; mutable br_fnum : int; mutable br_buf_free_count : int }
type chartabsize = { mutable cts_win : int; mutable cts_line : int; mutable cts_ptr : int; mutable cts_vcol : int; mutable cts_max_head_vcol : int }
type cmdarg = { mutable oap : int; mutable cmdchar : int; mutable ncharC1 : int; mutable ncharC2 : int; mutable cmdarg_opcount : int; mutable count0 : int; mutable count1 : int; mutable arg : int; mutable retval : int; mutable searchbuf : int; cmdarg_mem : int }
type exarg = { mutable nextcmd : int; mutable cmdlinep : int; mutable cmdidx : int; mutable argt : int; mutable forceit : bool; mutable addr_count : int; mutable line1 : int; mutable line2 : int; mutable addr_type : cmd_addr; mutable flags : int; mutable do_ecmd_cmd : int; mutable amount : int; mutable regname : int; mutable errmsg : int; mutable ea_getline : int; exarg_mem : int }
type incsearch_state = { mutable did_incsearch : bool; mutable incsearch_postponed : bool; mutable magic_overruled_save : optmagic; incsearch_state_mem : int }
type lineoff = { mutable lnum : int; mutable height : int }
type optset = { mutable os_idx : int; mutable os_flags : int; mutable os_op : set_op; mutable os_value_checked : int; mutable os_restore_chartab : bool; mutable os_errbuf : int; mutable os_errbuflen : int; optset_mem : int }
type save_state = { mutable save_msg_scroll : int; mutable save_restart_edit : int; mutable save_msg_didout : int; mutable save_State : int; mutable save_insertmode : int; mutable save_finish_op : bool; mutable save_opcount : int; mutable save_reg_executing : int; mutable save_pending_end_reg_executing : bool; mutable save_script_version : int; save_state_mem : int }
type searchstat = { mutable cur : int; mutable cnt : int; mutable exact_match : bool; mutable incomplete : int; mutable last_maxcount : int }
type ttyinfo = { mutable backspace : int; mutable enter : int; mutable interrupt : int; mutable nl_does_cr : bool }
type winlinevars = { mutable draw_state : int; mutable winlinevars_lnum : int; mutable startrow : int; mutable row : int; mutable screen_row : int; mutable vcol : int; mutable col : int; mutable vcol_off_tp : int; mutable eol_hl_off : int; mutable off : int; mutable win_attr : int; mutable line_attr : int; mutable screen_line_flags : int; mutable char_attr : int; mutable n_extra : int; mutable p_extra : int; mutable p_extra_free : int; mutable extra_attr : int; mutable n_attr_skip : int; mutable c_extra : int; mutable c_final : int; mutable extra_for_textprop : bool; mutable saved_n_extra : int; mutable saved_p_extra : int; mutable saved_p_extra_free : int; mutable saved_extra_attr : int; mutable saved_n_attr_skip : int; mutable saved_extra_for_textprop : bool; mutable saved_c_extra : int; mutable saved_c_final : int; mutable saved_char_attr : int; mutable filler_lines : int; winlinevars_mem : int }

(* The host's functions, as the core calls them: the editor carries them. *)
type glue = {
  host_alloc : ed -> int -> int;
  host_exit : ed -> int -> unit;
  host_message : ed -> int -> int -> int -> unit;
  host_raise : ed -> int -> unit;
  host_time : ed -> int;
  host_write : ed -> int -> int -> int;
  musl_delay : ed -> int -> int -> unit;
  musl_get_winsize : ed -> int -> int -> int;
  musl_host_init : ed -> unit;
  musl_now_ms : ed -> int;
  musl_read_input : ed -> int -> int -> int;
  musl_suspend : ed -> unit;
  musl_term_start : ed -> unit;
  musl_term_stop : ed -> unit;
  musl_tty_keys : ed -> int -> int -> int -> int -> int -> int;
  musl_wait_for_input : ed -> int -> int;
  vim_snprintf : ed -> int -> int -> int -> int list -> int;
}

(* The C's file-scope objects the editor keeps as its fields. *)
and state

and ed = (glue, state) Rt.ed

(* A new editor on the host's functions. *)
val new_editor : glue -> ed
val vim_main : ed -> int -> int -> int
val deathtrap : ed -> int -> unit
val emsg : ed -> int -> int
val iemsg : ed -> int -> unit
val emsg_iobuff_room : ed -> int
val iobuff_or : ed -> int -> int
val utfc_ptr2len : ed -> int -> int
val utf_ptr2cells : ed -> int -> int
val iobuff : ed -> int
