package togo

// hs.go is the Haskell backend's frame (doc/HASKELL.md): the module a
// translation unit becomes -- caprice's, the fourth translation.  Where the
// Go, the Java and the Clojure model C's memory in managed objects, the
// Haskell keeps it: every object in raw memory, laid out as the C lays it
// out on amd64 (the C front end's sizes and offsets), and a pointer an
// address (caprice/rt/Caprice/Rt.hs).  So nothing of the pointer analysis
// is needed, and the functions are the lowered form (lower.go) printed as
// Haskell (hs_fn.go, hs_expr.go):
//
//   - the file-scope objects, and the block-scope statics, are one segment
//     per editor, each at its offset; their initial values are written into
//     it when the editor is made (initGlobals);
//   - a function is a top-level function of the editor and the C's
//     parameters, in IO; its blocks are local functions of the variables
//     live at their start -- join points, a jump a tail call -- and a local
//     that is an array, a struct or a union, or whose address is taken,
//     lives in the call's frame;
//   - a function pointer is an index into the table of the functions whose
//     address is taken, at an address no object has;
//   - a function declared and not defined is the host's, called in the host
//     module with the editor first.

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/arbace/go-whim/crefactor/cc"
)

// hgen is the Haskell backend's state for one translation unit.
type hgen struct {
	g        *gen
	module   string
	host     string
	defined  map[string]*cc.FunctionDefinition
	hostFns  map[string]*cc.Declarator
	segOff   map[string]int // an object's key -> its offset in the segment
	segSize  int
	fnIdx    map[string]int // a function whose address is taken -> its index
	fnOrder  []string
	names    map[string]string // a C function -> its Haskell name
	variadic map[string]bool   // the host's variadic functions
}

// hsReserved are the names the generated code uses, and Haskell's keywords:
// a C name among them takes a trailing prime.
var hsReserved = map[string]bool{}

func init() {
	for _, w := range strings.Fields(`case class data default deriving do else foreign if import in infix infixl
	infixr instance let module newtype of then type where forall mdo rec proc family pattern role qualified as hiding
	pure fromIntegral not quot rem negate fmap return id max min otherwise True False
	xor complement shiftL shiftR
	rdI8 rdW8 rdI16 rdW16 rdI32 rdW32 rdI64 rdW64 rdP rdB wrI8 wrW8 wrI16 wrW16 wrI32 wrW32 wrI64 wrW64 wrP wrB
	copyMem fillMem copyMemNo b2i p2i i2p pAdd pSub frame fnPtr fnIndex toRaw fromRaw nullPtr edSeg newEd
	cBytes castPtr plusPtr minusPtr main newEditor initGlobals fnTable callPtr segSize listArray`) {
		hsReserved[w] = true
	}
}

// hsName is a C name as a Haskell variable or function: a name Haskell
// could not start with or reserves is changed, the rest kept.
func hsName(s string) string {
	if s == "" {
		return "anon'"
	}
	if c := s[0]; c >= 'A' && c <= 'Z' || c == '_' {
		s = "c'" + s
	}
	if hsReserved[s] {
		s += "'"
	}
	return s
}

// writeHs writes the translation unit as the Haskell module path, and beside
// it path.refused: the functions it could not write, with the reason.
func (g *gen) writeHs(path string) error {
	h := &hgen{g: g, module: g.p.HsModule, host: g.p.HsHost, defined: map[string]*cc.FunctionDefinition{},
		hostFns: map[string]*cc.Declarator{}, segOff: map[string]int{}, fnIdx: map[string]int{},
		names: map[string]string{}, variadic: map[string]bool{}}
	if h.module == "" {
		h.module = "Editor"
	}
	if h.host == "" {
		h.host = "Host"
	}
	var fds []*cc.FunctionDefinition
	for tu := g.ast.TranslationUnit; tu != nil; tu = tu.TranslationUnit {
		if ed := tu.ExternalDeclaration; ed.Case == cc.ExternalDeclarationFuncDef {
			fd := ed.FunctionDefinition
			h.defined[fd.Declarator.Name()] = fd
			fds = append(fds, fd)
		}
	}
	for name, d := range g.a.fnDecls {
		if h.defined[name] == nil && !strings.HasPrefix(name, "__") {
			h.hostFns[name] = d
			if ft, ok := d.Type().(*cc.FunctionType); ok && ft.IsVariadic() {
				h.variadic[name] = true
			}
		}
	}
	for name := range h.defined {
		h.names[name] = hsName(name)
	}
	h.layout()

	var report strings.Builder
	var funcs []string
	written := 0
	for _, fd := range fds {
		src, why := h.function(fd)
		if why != "" {
			fmt.Fprintf(&report, "%s: %s\n", fd.Declarator.Name(), why)
			funcs = append(funcs, h.stub(fd, why))
			continue
		}
		written++
		funcs = append(funcs, src)
	}
	inits, failed := h.initializers()
	for _, f := range failed {
		fmt.Fprintf(&report, "initial value of %s\n", f)
	}

	var b strings.Builder
	b.WriteString("{-# LANGUAGE BangPatterns, MagicHash #-}\n{-# OPTIONS_GHC -w #-}\n")
	fmt.Fprintf(&b, "-- Code generated by `go tool whim skel -hs` from a C translation unit; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "-- %d of %d functions written; the rest are stubs that fail, with the reason.\n", written, len(fds))
	fmt.Fprintf(&b, "module %s where\n\n", h.module)
	b.WriteString("import Prelude (IO, Int, Bool (..), pure, fromIntegral, not, quot, rem, negate, fmap, return, id, max, min,\n")
	b.WriteString("  (.), ($), (+), (-), (*), (==), (/=), (<), (<=), (>), (>=), (&&), (||), (<$>), (>>=), (>>), error, otherwise)\n")
	b.WriteString("import Data.Bits ((.&.), (.|.), xor, complement, shiftL, shiftR)\n")
	b.WriteString("import Data.Array (Array, listArray, (!))\n")
	b.WriteString("import Caprice.Rt\n")
	fmt.Fprintf(&b, "import qualified %s\n\n", h.host)
	fmt.Fprintf(&b, "-- | The bytes of the segment the file-scope objects are in.\nsegSize :: Int\nsegSize = %d\n\n", h.segSize)
	b.WriteString("-- | A new editor: its segment, with the objects' initial values.\nnewEditor :: IO Ed\nnewEditor = do\n  ed' <- newEd segSize\n  initGlobals ed'\n  pure ed'\n\n")
	b.WriteString("initGlobals :: Ed -> IO ()\ninitGlobals ed' = do\n")
	for _, l := range inits {
		b.WriteString("  " + l + "\n")
	}
	b.WriteString("  pure ()\n\n")
	b.WriteString(h.table())
	boot, accessors, err := h.exports()
	if err != nil {
		return err
	}
	b.WriteString(accessors)
	for _, f := range funcs {
		b.WriteString(f)
		b.WriteString("\n")
	}
	fmt.Fprintf(logw, "hs: %d of %d functions written, %d refused\n", written, len(fds), len(fds)-written)
	if err := os.WriteFile(path+".host", []byte(h.hostSigs()), 0o644); err != nil {
		return err
	}
	if boot != "" {
		if err := os.WriteFile(strings.TrimSuffix(path, ".hs")+".hs-boot", []byte(boot), 0o644); err != nil {
			return err
		}
	}
	if err := os.WriteFile(path+".refused", []byte(report.String()), 0o644); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// layout gives each file-scope object and each block-scope static its
// offset in the segment, aligned as C aligns it.
func (h *hgen) layout() {
	type obj struct {
		key string
		t   cc.Type
	}
	var objs []obj
	seen := map[string]bool{}
	add := func(key string, t cc.Type) {
		if seen[key] || t == nil {
			return
		}
		seen[key] = true
		objs = append(objs, obj{key, t})
	}
	for tu := h.g.ast.TranslationUnit; tu != nil; tu = tu.TranslationUnit {
		ed := tu.ExternalDeclaration
		if ed.Case != cc.ExternalDeclarationDecl || ed.Declaration == nil {
			continue
		}
		for l := ed.Declaration.InitDeclaratorList; l != nil; l = l.InitDeclaratorList {
			d := l.InitDeclarator.Declarator
			if d == nil || d.IsTypename() || d.Type() == nil || d.Type().Kind() == cc.Function {
				continue
			}
			add(h.g.a.declKey(d), d.Type())
		}
	}
	for _, s := range h.g.a.statics {
		add(h.g.a.declKey(s.d), s.d.Type())
	}
	off := 0
	for _, o := range objs {
		al := max(o.t.Align(), 1)
		off = (off + al - 1) / al * al
		h.segOff[o.key] = off
		off += int(max(o.t.Size(), 0))
	}
	h.segSize = off
}

// anon is room in the segment for an object of type t that has no name: a
// compound literal in a file-scope object's initializer.
func (h *hgen) anon(t cc.Type) int {
	al := max(t.Align(), 1)
	off := (h.segSize + al - 1) / al * al
	h.segSize = off + int(max(t.Size(), 1))
	return off
}

// exports is the hs-boot interface of what the host calls back
// (Profile.HsExports), and the accessors of the objects among them.
func (h *hgen) exports() (boot, accessors string, err error) {
	if len(h.g.p.HsExports) == 0 {
		return "", "", nil
	}
	var bb, ab strings.Builder
	fmt.Fprintf(&bb, "module %s where\n\nimport Caprice.Rt\n\n", h.module)
	for _, name := range h.g.p.HsExports {
		if fd := h.defined[name]; fd != nil {
			sig, _ := h.signature(fd.Declarator, nil)
			bb.WriteString(sig + "\n")
			continue
		}
		off, ok := h.segOff["global:"+name]
		if !ok {
			return "", "", fmt.Errorf("HsExports: %s is neither a function nor a file-scope object of the unit", name)
		}
		fmt.Fprintf(&ab, "-- | The address of %s, for the host.\naddr'%s :: Ed -> P\naddr'%s ed' = pAdd (edSeg ed') %d\n\n", name, name, name, off)
		fmt.Fprintf(&bb, "addr'%s :: Ed -> P\n", name)
	}
	return bb.String(), ab.String(), nil
}

// hostSigs is the type of each function the module calls in the host:
// what the host module must define.
func (h *hgen) hostSigs() string {
	var names []string
	for n := range h.hostFns {
		names = append(names, n)
	}
	sort.Strings(names)
	var b strings.Builder
	for _, n := range names {
		d := h.hostFns[n]
		ft, ok := d.Type().(*cc.FunctionType)
		if !ok {
			continue
		}
		ts := []string{"Ed"}
		for _, p := range ft.Parameters() {
			if p.Type() == nil || p.Type().Kind() == cc.Void {
				continue
			}
			t := p.Type()
			if t.Kind() == cc.Array {
				t = t.Decay()
			}
			ts = append(ts, hsParamType(t))
		}
		if ft.IsVariadic() {
			ts = append(ts, "[VArg]")
		}
		fmt.Fprintf(&b, "%s :: %s -> IO %s\n", hsName(n), strings.Join(ts, " -> "), hsType(ft.Result()))
	}
	return b.String()
}

// fnPtrOf is the index of a function whose address is taken, given the
// first time it is asked.
func (h *hgen) fnPtrOf(name string) int {
	if i, ok := h.fnIdx[name]; ok {
		return i
	}
	i := len(h.fnOrder)
	h.fnIdx[name] = i
	h.fnOrder = append(h.fnOrder, name)
	return i
}

// table is the functions whose address is taken, each as a function of the
// editor and its arguments' bits, and the call through a pointer.
func (h *hgen) table() string {
	var b strings.Builder
	b.WriteString("-- | The functions whose address is taken: a function pointer is an index here.\n")
	b.WriteString("fnTable :: Array Int (Ed -> [Word64] -> IO Word64)\n")
	fmt.Fprintf(&b, "fnTable = listArray (0, %d)\n  [", max(len(h.fnOrder)-1, 0))
	if len(h.fnOrder) == 0 {
		b.WriteString(" \\_ _ -> error \"no function\"")
	}
	for i, name := range h.fnOrder {
		if i > 0 {
			b.WriteString("\n  ,")
		}
		d := h.defined[name]
		var ft *cc.FunctionType
		call := ""
		if d != nil {
			ft, _ = d.Declarator.Type().(*cc.FunctionType)
			call = h.names[name]
		} else if hd := h.hostFns[name]; hd != nil {
			ft, _ = hd.Type().(*cc.FunctionType)
			call = h.host + "." + hsName(name)
		}
		if ft == nil {
			fmt.Fprintf(&b, " \\_ _ -> error %q", "no function "+name)
			continue
		}
		var ps, as []string
		n := 0
		for _, p := range ft.Parameters() {
			if p.Type() == nil || p.Type().Kind() == cc.Void {
				continue
			}
			ps = append(ps, fmt.Sprintf("a%d", n))
			as = append(as, fmt.Sprintf("(fromRaw a%d)", n))
			n++
		}
		fmt.Fprintf(&b, " \\ed' [%s] -> toRaw <$> %s ed' %s", strings.Join(ps, ", "), call, strings.Join(as, " "))
	}
	b.WriteString("\n  ]\n\n")
	b.WriteString("-- | A call through a function pointer.\ncallPtr :: Ed -> P -> [Word64] -> IO Word64\ncallPtr ed' p args = (fnTable ! fnIndex p) ed' args\n\n")
	return b.String()
}

// stub is a refused function: its type, and a body that fails.
func (h *hgen) stub(fd *cc.FunctionDefinition, why string) string {
	name := h.names[fd.Declarator.Name()]
	sig, params := h.signature(fd.Declarator, nil)
	return fmt.Sprintf("-- REFUSED: %s\n%s\n%s ed' %s= error %q\n", why, sig, name, strings.Join(append(params, ""), " "), fd.Declarator.Name()+": "+why)
}

// signature is a function's type line, and its parameters' names: the
// editor, each C parameter, and the result in IO -- a struct result
// written through a pointer the caller gives, first.
func (h *hgen) signature(d *cc.Declarator, lf *lfn) (string, []string) {
	ft, _ := d.Type().(*cc.FunctionType)
	name := h.names[d.Name()]
	var ts, ps []string
	ts = append(ts, "Ed")
	if isAggr(ft.Result()) {
		ts = append(ts, "P")
		ps = append(ps, "sret'")
	}
	i := 0
	for _, p := range ft.Parameters() {
		if p.Type() == nil || p.Type().Kind() == cc.Void {
			continue
		}
		t := p.Type()
		if t.Kind() == cc.Array {
			t = t.Decay()
		}
		ts = append(ts, hsParamType(t))
		if lf != nil && i < len(lf.params) {
			ps = append(ps, lf.params[i].name)
		} else {
			ps = append(ps, fmt.Sprintf("p%d'", i))
		}
		i++
	}
	rt := hsType(ft.Result())
	if isAggr(ft.Result()) {
		rt = "()"
	}
	return fmt.Sprintf("%s :: %s -> IO %s", name, strings.Join(ts, " -> "), rt), ps
}

// hsParamType is a parameter's Haskell type: a struct passed by value is
// its address, which the callee copies.
func hsParamType(t cc.Type) string {
	if isAggr(t) {
		return "P"
	}
	return hsType(t)
}

// hsType is the Haskell type of a C scalar type's values; "agg" for a
// struct or union (whose value is its address), "()" for void.
func hsType(t cc.Type) string {
	if t == nil {
		return "()"
	}
	switch t.Kind() {
	case cc.Void:
		return "()"
	case cc.Ptr, cc.Array, cc.Function:
		return "P"
	case cc.Struct, cc.Union:
		return "agg"
	}
	k, ok := scalarKind(t)
	if !ok {
		return "?" + t.String()
	}
	return hsKindType(k)
}

func hsKindType(k jk) string {
	if k.boolean {
		return "Bool"
	}
	if k.signed {
		return fmt.Sprintf("Int%d", k.size*8)
	}
	return fmt.Sprintf("Word%d", k.size*8)
}

// hsAccess is the suffix of the runtime's reader and writer of a type:
// rdI32, wrP, rdB.
func hsAccess(ht string) string {
	switch ht {
	case "Bool":
		return "B"
	case "P":
		return "P"
	}
	return string(ht[0]) + strings.TrimPrefix(strings.TrimPrefix(ht, "Int"), "Word")
}

// initializers are the steps that write the objects' initial values into
// the segment, and the objects whose initializer it cannot write.
func (h *hgen) initializers() ([]string, []string) {
	var lines, failed []string
	f := &hfn{h: h, name: "initGlobals"}
	one := func(key, name string, t cc.Type, in *cc.Initializer) {
		if in == nil {
			return
		}
		off, ok := h.segOff[key]
		if !ok {
			failed = append(failed, name)
			return
		}
		ls, err := f.catchInit(func() { f.initInto(fmt.Sprintf("(edSeg ed')"), off, t, in) })
		if err != "" {
			failed = append(failed, name+": "+err)
			return
		}
		lines = append(lines, ls...)
	}
	for tu := h.g.ast.TranslationUnit; tu != nil; tu = tu.TranslationUnit {
		ed := tu.ExternalDeclaration
		if ed.Case != cc.ExternalDeclarationDecl || ed.Declaration == nil {
			continue
		}
		for l := ed.Declaration.InitDeclaratorList; l != nil; l = l.InitDeclaratorList {
			d := l.InitDeclarator.Declarator
			if d == nil || d.IsTypename() || d.Type() == nil || d.Type().Kind() == cc.Function {
				continue
			}
			one(h.g.a.declKey(d), d.Name(), d.Type(), l.InitDeclarator.Initializer)
		}
	}
	for _, s := range h.g.a.statics {
		one(h.g.a.declKey(s.d), s.fn+"."+s.d.Name(), s.d.Type(), s.init)
	}
	return lines, failed
}

// catchInit runs fn, which writes lines, and returns them, or why it
// refused.
func (f *hfn) catchInit(fn func()) (lines []string, why string) {
	defer func() {
		if r := recover(); r != nil {
			u, ok := r.(unsupported)
			if !ok {
				panic(r)
			}
			lines, why = nil, u.why
		}
	}()
	f.lines = nil
	fn()
	return f.lines, ""
}
