package togo

// java_files.go writes the Java class as a package of files
// (Profile.JavaFiles; doc/JAVA-IDIOMS.md, item 11): the class's own file
// holds its fields, their initial values and its methods; Constants.java
// the C's constants, which every file that names one imports statically;
// and each struct class and function interface is a file of its own, a
// top-level class of the package.  Nothing is renamed: the class names what
// it named, and the package makes them the same classes.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var constName = regexp.MustCompile(`static final \S+ (\w+) =`)

// writeJavaFiles writes the files beside path, the class's own file.
func (j *jgen) writeJavaFiles(path, class string, abstract bool, written, total, replaced int, classes []string, fields string, inits []string, host, methods string) error {
	pkg := j.g.p.JavaPackage
	if pkg == "" {
		return fmt.Errorf("-java: JavaFiles needs a JavaPackage")
	}
	dir := filepath.Dir(path)
	gen := "// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.\n"
	var enums []string
	consts := map[string]bool{}
	for _, e := range j.enums {
		enums = append(enums, e)
		for _, m := range constName.FindAllStringSubmatch(e, -1) {
			consts[m[1]] = true
		}
	}
	sort.Strings(enums)
	// head is a file's first lines: what generated it, its package, and
	// the imports its text needs
	head := func(text string, extra string) string {
		var b strings.Builder
		b.WriteString(gen)
		b.WriteString(extra)
		fmt.Fprintf(&b, "\npackage %s;\n\n", pkg)
		if namesAny(text, consts) {
			fmt.Fprintf(&b, "import static %s.Constants.*;\n\n", pkg)
		}
		b.WriteString("import whim.rt.*;\n\n")
		return b.String()
	}
	files := map[string]string{}

	// the constants
	var cb strings.Builder
	cb.WriteString(gen)
	fmt.Fprintf(&cb, "\npackage %s;\n\n", pkg)
	b := func(s string) { cb.WriteString(s) }
	b("/** The C's constants: its enumerators and the values its macros were. */\n")
	b("final class Constants {\n    private Constants() {\n    }\n\n")
	for _, e := range enums {
		b(e)
	}
	b("}\n")
	files["Constants.java"] = cb.String()

	// the struct classes and the function interfaces, a file each
	for i, name := range j.classOrder {
		text := dedent(classes[i])
		text = strings.Replace(text, "static final class ", "final class ", 1)
		files[name+".java"] = head(text, "") + text
	}
	for _, f := range j.ifaceList() {
		var ps []string
		for i, p := range f.params {
			ps = append(ps, fmt.Sprintf("%s a%d", p, i))
		}
		text := fmt.Sprintf("@FunctionalInterface\ninterface %s {\n    %s call(%s);\n}\n", f.name, f.result, strings.Join(ps, ", "))
		files[f.name+".java"] = head(text, "") + text
	}

	// the class: its fields, their initial values, its methods
	var eb strings.Builder
	abs := ""
	if abstract {
		abs = "abstract "
	}
	fmt.Fprintf(&eb, "@SuppressWarnings({\"unchecked\", \"rawtypes\"})\npublic %sclass %s {\n", abs, class)
	eb.WriteString(fields)
	for _, k := range j.fnRefOrder {
		eb.WriteString(j.fnRefText[k])
	}
	fmt.Fprintf(&eb, "\n    public %s() {\n", class)
	for i := range inits {
		fmt.Fprintf(&eb, "        initGlobals%d();\n", i)
	}
	eb.WriteString("    }\n")
	for i, in := range inits {
		fmt.Fprintf(&eb, "\n    private void initGlobals%d() {\n%s    }\n", i, in)
	}
	if host != "" {
		eb.WriteString("\n    // the host: declared, and not defined here\n")
		eb.WriteString(host)
	}
	eb.WriteString(j.gaHelpers())
	eb.WriteString(methods)
	eb.WriteString("}\n")
	body := eb.String()
	files[class+".java"] = head(body, fmt.Sprintf("// %d of %d functions written, %d the runtime's; the rest are stubs that throw, with the reason.\n", written, total, replaced)) + body

	for name, text := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(jtidyFile(text)), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// ifaceList is the function interfaces in the order ifaceDecls writes them.
func (j *jgen) ifaceList() []*jiface {
	fs := make([]*jiface, 0, len(j.ifaces))
	for _, f := range j.ifaces {
		fs = append(fs, f)
	}
	sort.Slice(fs, func(a, b int) bool {
		return len(fs[a].name) < len(fs[b].name) || len(fs[a].name) == len(fs[b].name) && fs[a].name < fs[b].name
	})
	return fs
}

// dedent is a nested class's text as a top-level one: four spaces less.
func dedent(s string) string {
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		lines[i] = strings.TrimPrefix(l, "    ")
	}
	return strings.Join(lines, "\n")
}

// namesAny says text has an identifier among names.
func namesAny(text string, names map[string]bool) bool {
	start := -1
	for i := 0; i <= len(text); i++ {
		if i < len(text) && isWordByte(text[i]) {
			if start < 0 {
				start = i
			}
			continue
		}
		if start >= 0 && names[text[start:i]] && (start == 0 || text[start-1] != '.') {
			return true
		}
		start = -1
	}
	return false
}
