// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class A_1 implements Struct<A_1> {
    BytePtr start;
    BytePtr stop;

    @Override
    public A_1 set(A_1 o) {
        start = o.start;
        stop = o.stop;
        return this;
    }

    A_1 copy() {
        return new A_1().set(this);
    }

    @Override
    public A_1 zero() {
        return set(new A_1());
    }

    static A_1[] array(int n) {
        A_1[] a = new A_1[n];
        for (int k = 0; k < n; k++) {
            a[k] = new A_1();
        }
        return a;
    }
}
