// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class A_2 implements Struct<A_2> {
    // C union: every member is its own field here
    final A_1 term = new A_1();
    final A_3 cterm = new A_3();

    public A_2 set(A_2 o$) {
        term.set(o$.term);
        cterm.set(o$.cterm);
        return this;
    }

    A_2 copy() {
        return new A_2().set(this);
    }

    public A_2 zero() {
        return set(new A_2());
    }

    static A_2[] array(int n) {
        A_2[] a = new A_2[n];
        for (int k = 0; k < n; k++) {
            a[k] = new A_2();
        }
        return a;
    }
}
