// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class A_3 implements Struct<A_3> {
    short fg_color;
    short bg_color;
    short ul_color;
    short font;

    @Override
    public A_3 set(A_3 o) {
        fg_color = o.fg_color;
        bg_color = o.bg_color;
        ul_color = o.ul_color;
        font = o.font;
        return this;
    }

    A_3 copy() {
        return new A_3().set(this);
    }

    @Override
    public A_3 zero() {
        return set(new A_3());
    }

    static A_3[] array(int n) {
        A_3[] a = new A_3[n];
        for (int k = 0; k < n; k++) {
            a[k] = new A_3();
        }
        return a;
    }
}
