// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class A_4 implements Struct<A_4> {
    // C union: every member is its own field here
    long number;
    int boolean_;
    BytePtr string;

    @Override
    public A_4 set(A_4 o) {
        number = o.number;
        boolean_ = o.boolean_;
        string = o.string;
        return this;
    }

    A_4 copy() {
        return new A_4().set(this);
    }

    @Override
    public A_4 zero() {
        return set(new A_4());
    }

    static A_4[] array(int n) {
        A_4[] a = new A_4[n];
        for (int k = 0; k < n; k++) {
            a[k] = new A_4();
        }
        return a;
    }
}
