// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class A_5 implements Struct<A_5> {
    // C union: every member is its own field here
    BytePtr ptr;
    final T_lpos_T pos = new T_lpos_T();

    public A_5 set(A_5 o$) {
        ptr = o$.ptr;
        pos.set(o$.pos);
        return this;
    }

    A_5 copy() {
        return new A_5().set(this);
    }

    public A_5 zero() {
        return set(new A_5());
    }

    static A_5[] array(int n) {
        A_5[] a = new A_5[n];
        for (int k = 0; k < n; k++) {
            a[k] = new A_5();
        }
        return a;
    }
}
