// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class A_6 implements Struct<A_6> {
    // C union: every member is its own field here
    final T_save_se_T sesave = new T_save_se_T();
    final T_regsave_T regsave = new T_regsave_T();

    @Override
    public A_6 set(A_6 o) {
        sesave.set(o.sesave);
        regsave.set(o.regsave);
        return this;
    }

    A_6 copy() {
        return new A_6().set(this);
    }

    @Override
    public A_6 zero() {
        return set(new A_6());
    }

    static A_6[] array(int n) {
        A_6[] a = new A_6[n];
        for (int k = 0; k < n; k++) {
            a[k] = new A_6();
        }
        return a;
    }
}
