// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

@FunctionalInterface
interface Fn10 {
    void call(IntPtr a0, int a1);
}
