// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

@FunctionalInterface
interface Fn3 {
    int call(T_keyvalue_T a0, T_keyvalue_T a1);
}
