// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

@FunctionalInterface
interface Fn4 {
    int call(S_key_name_entry a0, S_key_name_entry a1);
}
