// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

@FunctionalInterface
interface Fn7 {
    int call(long a0, IntPtr a1, int a2);
}
