// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

@FunctionalInterface
interface Fn9 {
    int call(T_keyvalue_T a0, Ptr<T_keyvalue_T> a1);
}
