// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_attr_entry implements Struct<S_attr_entry> {
    short ae_attr;
    final A_2 ae_u = new A_2();

    @Override
    public S_attr_entry set(S_attr_entry o) {
        ae_attr = o.ae_attr;
        ae_u.set(o.ae_u);
        return this;
    }

    S_attr_entry copy() {
        return new S_attr_entry().set(this);
    }

    @Override
    public S_attr_entry zero() {
        return set(new S_attr_entry());
    }

    static S_attr_entry[] array(int n) {
        S_attr_entry[] a = new S_attr_entry[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_attr_entry();
        }
        return a;
    }
}
