// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_backpos_S implements Struct<S_backpos_S> {
    BytePtr bp_scan;
    final T_regsave_T bp_pos = new T_regsave_T();

    public S_backpos_S set(S_backpos_S o$) {
        bp_scan = o$.bp_scan;
        bp_pos.set(o$.bp_pos);
        return this;
    }

    S_backpos_S copy() {
        return new S_backpos_S().set(this);
    }

    public S_backpos_S zero() {
        return set(new S_backpos_S());
    }

    static S_backpos_S[] array(int n) {
        S_backpos_S[] a = new S_backpos_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_backpos_S();
        }
        return a;
    }
}
