// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_block_def implements Struct<S_block_def> {
    int startspaces;
    int endspaces;
    int textlen;
    BytePtr textstart;
    int textcol;
    int start_vcol;
    int end_vcol;
    boolean is_short;
    boolean is_MAX;
    boolean is_oneChar;
    int pre_whitesp;
    int pre_whitesp_c;
    int end_char_vcols;
    int start_char_vcols;

    @Override
    public S_block_def set(S_block_def o) {
        startspaces = o.startspaces;
        endspaces = o.endspaces;
        textlen = o.textlen;
        textstart = o.textstart;
        textcol = o.textcol;
        start_vcol = o.start_vcol;
        end_vcol = o.end_vcol;
        is_short = o.is_short;
        is_MAX = o.is_MAX;
        is_oneChar = o.is_oneChar;
        pre_whitesp = o.pre_whitesp;
        pre_whitesp_c = o.pre_whitesp_c;
        end_char_vcols = o.end_char_vcols;
        start_char_vcols = o.start_char_vcols;
        return this;
    }

    S_block_def copy() {
        return new S_block_def().set(this);
    }

    @Override
    public S_block_def zero() {
        return set(new S_block_def());
    }

    static S_block_def[] array(int n) {
        S_block_def[] a = new S_block_def[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_block_def();
        }
        return a;
    }
}
