// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_block_hdr implements Struct<S_block_hdr> {
    short bh_id;
    S_pointer_block bh_ptr;
    S_data_block bh_data;

    @Override
    public S_block_hdr set(S_block_hdr o) {
        bh_id = o.bh_id;
        bh_ptr = o.bh_ptr;
        bh_data = o.bh_data;
        return this;
    }

    S_block_hdr copy() {
        return new S_block_hdr().set(this);
    }

    @Override
    public S_block_hdr zero() {
        return set(new S_block_hdr());
    }

    static S_block_hdr[] array(int n) {
        S_block_hdr[] a = new S_block_hdr[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_block_hdr();
        }
        return a;
    }
}
