// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_buffheader implements Struct<S_buffheader> {
    final S_buffblock bh_first = new S_buffblock();
    S_buffblock bh_curr;
    int bh_index;
    int bh_space;
    int bh_create_newblock;

    public S_buffheader set(S_buffheader o$) {
        bh_first.set(o$.bh_first);
        bh_curr = o$.bh_curr;
        bh_index = o$.bh_index;
        bh_space = o$.bh_space;
        bh_create_newblock = o$.bh_create_newblock;
        return this;
    }

    S_buffheader copy() {
        return new S_buffheader().set(this);
    }

    public S_buffheader zero() {
        return set(new S_buffheader());
    }

    static S_buffheader[] array(int n) {
        S_buffheader[] a = new S_buffheader[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_buffheader();
        }
        return a;
    }
}
