// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_buffblock implements Struct<S_buffblock> {
    S_buffblock b_next;
    long b_strlen;
    BytePtr b_str;

    @Override
    public S_buffblock set(S_buffblock o) {
        b_next = o.b_next;
        b_strlen = o.b_strlen;
        b_str = o.b_str;
        return this;
    }

    S_buffblock copy() {
        return new S_buffblock().set(this);
    }

    @Override
    public S_buffblock zero() {
        return set(new S_buffblock());
    }

    static S_buffblock[] array(int n) {
        S_buffblock[] a = new S_buffblock[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_buffblock();
        }
        return a;
    }
}
