// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_charstab implements Struct<S_charstab> {
    IntPtr cp;
    final T_string_T name = new T_string_T();

    S_charstab() {
    }

    S_charstab(IntPtr cp, T_string_T name) {
        this.cp = cp;
        this.name.set(name);
    }

    @Override
    public S_charstab set(S_charstab o) {
        cp = o.cp;
        name.set(o.name);
        return this;
    }

    S_charstab copy() {
        return new S_charstab().set(this);
    }

    @Override
    public S_charstab zero() {
        return set(new S_charstab());
    }

    static S_charstab[] array(int n) {
        S_charstab[] a = new S_charstab[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_charstab();
        }
        return a;
    }
}
