// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_clinterval implements Struct<S_clinterval> {
    int first;
    int last;
    int class_;

    S_clinterval() {
    }

    S_clinterval(int first, int last, int class_) {
        this.first = first;
        this.last = last;
        this.class_ = class_;
    }

    @Override
    public S_clinterval set(S_clinterval o) {
        first = o.first;
        last = o.last;
        class_ = o.class_;
        return this;
    }

    S_clinterval copy() {
        return new S_clinterval().set(this);
    }

    @Override
    public S_clinterval zero() {
        return set(new S_clinterval());
    }

    static S_clinterval[] array(int n) {
        S_clinterval[] a = new S_clinterval[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_clinterval();
        }
        return a;
    }
}
