// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_cmdarg_S implements Struct<S_cmdarg_S> {
    S_oparg_S oap;
    int cmdchar;
    final int[] nchar = new int[1];
    int ncharC1;
    int ncharC2;
    final int[] extra_char = new int[1];
    long opcount;
    long count0;
    long count1;
    int arg;
    int retval;
    BytePtr searchbuf;

    @Override
    public S_cmdarg_S set(S_cmdarg_S o) {
        oap = o.oap;
        cmdchar = o.cmdchar;
        nchar[0] = o.nchar[0];
        ncharC1 = o.ncharC1;
        ncharC2 = o.ncharC2;
        extra_char[0] = o.extra_char[0];
        opcount = o.opcount;
        count0 = o.count0;
        count1 = o.count1;
        arg = o.arg;
        retval = o.retval;
        searchbuf = o.searchbuf;
        return this;
    }

    S_cmdarg_S copy() {
        return new S_cmdarg_S().set(this);
    }

    @Override
    public S_cmdarg_S zero() {
        return set(new S_cmdarg_S());
    }

    static S_cmdarg_S[] array(int n) {
        S_cmdarg_S[] a = new S_cmdarg_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_cmdarg_S();
        }
        return a;
    }
}
