// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_cmdname implements Struct<S_cmdname> {
    BytePtr cmd_name;
    int cmd_minlen;
    Fn2 cmd_func;
    long cmd_argt;
    int cmd_addr_type;

    S_cmdname() {
    }

    S_cmdname(BytePtr cmd_name, int cmd_minlen, Fn2 cmd_func, long cmd_argt, int cmd_addr_type) {
        this.cmd_name = cmd_name;
        this.cmd_minlen = cmd_minlen;
        this.cmd_func = cmd_func;
        this.cmd_argt = cmd_argt;
        this.cmd_addr_type = cmd_addr_type;
    }

    @Override
    public S_cmdname set(S_cmdname o) {
        cmd_name = o.cmd_name;
        cmd_minlen = o.cmd_minlen;
        cmd_func = o.cmd_func;
        cmd_argt = o.cmd_argt;
        cmd_addr_type = o.cmd_addr_type;
        return this;
    }

    S_cmdname copy() {
        return new S_cmdname().set(this);
    }

    @Override
    public S_cmdname zero() {
        return set(new S_cmdname());
    }

    static S_cmdname[] array(int n) {
        S_cmdname[] a = new S_cmdname[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_cmdname();
        }
        return a;
    }
}
