// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_data_line implements Struct<S_data_line> {
    BytePtr dl_text;
    int dl_len;
    byte dl_marked;

    public S_data_line set(S_data_line o$) {
        dl_text = o$.dl_text;
        dl_len = o$.dl_len;
        dl_marked = o$.dl_marked;
        return this;
    }

    S_data_line copy() {
        return new S_data_line().set(this);
    }

    public S_data_line zero() {
        return set(new S_data_line());
    }

    static S_data_line[] array(int n) {
        S_data_line[] a = new S_data_line[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_data_line();
        }
        return a;
    }
}
