// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_data_block implements Struct<S_data_block> {
    long db_line_count;
    final S_data_line[] db_line = S_data_line.array(64);

    @Override
    public S_data_block set(S_data_block o) {
        db_line_count = o.db_line_count;
        for (int k$0 = 0; k$0 < 64; k$0++) {
            db_line[k$0].set(o.db_line[k$0]);
        }
        return this;
    }

    S_data_block copy() {
        return new S_data_block().set(this);
    }

    @Override
    public S_data_block zero() {
        return set(new S_data_block());
    }

    static S_data_block[] array(int n) {
        S_data_block[] a = new S_data_block[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_data_block();
        }
        return a;
    }
}
