// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_expand implements Struct<S_expand> {
    BytePtr xp_pattern;
    int xp_context;
    int xp_prefix;
    int xp_backslash;
    boolean xp_shell;
    int xp_numfiles;
    BytePtr xp_orig;
    Ptr<BytePtr> xp_files;
    Ptr<BytePtr> xp_files_abbr;
    Ptr<BytePtr> xp_files_kind;
    Ptr<BytePtr> xp_files_menu;
    Ptr<BytePtr> xp_files_info;

    public S_expand set(S_expand o$) {
        xp_pattern = o$.xp_pattern;
        xp_context = o$.xp_context;
        xp_prefix = o$.xp_prefix;
        xp_backslash = o$.xp_backslash;
        xp_shell = o$.xp_shell;
        xp_numfiles = o$.xp_numfiles;
        xp_orig = o$.xp_orig;
        xp_files = o$.xp_files;
        xp_files_abbr = o$.xp_files_abbr;
        xp_files_kind = o$.xp_files_kind;
        xp_files_menu = o$.xp_files_menu;
        xp_files_info = o$.xp_files_info;
        return this;
    }

    S_expand copy() {
        return new S_expand().set(this);
    }

    public S_expand zero() {
        return set(new S_expand());
    }

    static S_expand[] array(int n) {
        S_expand[] a = new S_expand[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_expand();
        }
        return a;
    }
}
