// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_exarg implements Struct<S_exarg> {
    final BytePtr[] arg = new BytePtr[1];
    BytePtr nextcmd;
    final BytePtr[] cmd = new BytePtr[1];
    Ptr<BytePtr> cmdlinep;
    int cmdidx;
    long argt;
    boolean forceit;
    int addr_count;
    long line1;
    long line2;
    int addr_type;
    int flags;
    BytePtr do_ecmd_cmd;
    int amount;
    int regname;
    BytePtr errmsg;
    Fn1 ea_getline;

    @Override
    public S_exarg set(S_exarg o) {
        arg[0] = o.arg[0];
        nextcmd = o.nextcmd;
        cmd[0] = o.cmd[0];
        cmdlinep = o.cmdlinep;
        cmdidx = o.cmdidx;
        argt = o.argt;
        forceit = o.forceit;
        addr_count = o.addr_count;
        line1 = o.line1;
        line2 = o.line2;
        addr_type = o.addr_type;
        flags = o.flags;
        do_ecmd_cmd = o.do_ecmd_cmd;
        amount = o.amount;
        regname = o.regname;
        errmsg = o.errmsg;
        ea_getline = o.ea_getline;
        return this;
    }

    S_exarg copy() {
        return new S_exarg().set(this);
    }

    @Override
    public S_exarg zero() {
        return set(new S_exarg());
    }

    static S_exarg[] array(int n) {
        S_exarg[] a = new S_exarg[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_exarg();
        }
        return a;
    }
}
