// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_filemark implements Struct<S_filemark> {
    final T_pos_T mark = new T_pos_T();
    int fnum;

    public S_filemark set(S_filemark o$) {
        mark.set(o$.mark);
        fnum = o$.fnum;
        return this;
    }

    S_filemark copy() {
        return new S_filemark().set(this);
    }

    public S_filemark zero() {
        return set(new S_filemark());
    }

    static S_filemark[] array(int n) {
        S_filemark[] a = new S_filemark[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_filemark();
        }
        return a;
    }
}
