// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_file_buffer implements Struct<S_file_buffer> {
    final S_memline b_ml = new S_memline();
    int b_nwindows;
    int b_flags;
    int b_locked;
    int b_locked_split;
    int b_fnum;
    final int[] b_changed = new int[1];
    long b_changedtick;
    long b_last_changedtick;
    long b_last_changedtick_pum;
    long b_last_changedtick_i;
    boolean b_saving;
    boolean b_mod_set;
    long b_mod_top;
    long b_mod_bot;
    long b_mod_xlines;
    S_wininfo_S b_wininfo;
    final T_pos_T[] b_namedm = T_pos_T.array(26);
    final T_visualinfo_T b_visual = new T_visualinfo_T();
    final T_pos_T b_last_cursor = new T_pos_T();
    final T_pos_T b_last_insert = new T_pos_T();
    final T_pos_T b_last_change = new T_pos_T();
    final T_pos_T[] b_changelist = T_pos_T.array(100);
    int b_changelistlen;
    boolean b_new_change;
    final byte[] b_chartab = new byte[32];
    final S_mapblock[] b_maphash = new S_mapblock[256];
    final S_mapblock[] b_first_abbr = new S_mapblock[1];
    final T_pos_T b_op_start = new T_pos_T();
    final T_pos_T b_op_start_orig = new T_pos_T();
    final T_pos_T b_op_end = new T_pos_T();
    boolean b_modified_was_set;
    S_u_header b_u_oldhead;
    S_u_header b_u_newhead;
    S_u_header b_u_curhead;
    int b_u_numhead;
    boolean b_u_synced;
    long b_u_seq_last;
    long b_u_save_nr_last;
    long b_u_seq_cur;
    long b_u_time_cur;
    long b_u_save_nr_cur;
    final T_undoline_T b_u_line_ptr = new T_undoline_T();
    long b_u_line_lnum;
    int b_u_line_colnr;
    boolean b_p_initialized;
    final int[] b_p_ai = new int[1];
    int b_p_ai_nopaste;
    int b_bkc_flags;
    final int[] b_p_ci = new int[1];
    int b_cot_flags;
    final int[] b_p_et = new int[1];
    int b_p_et_nopaste;
    final BytePtr[] b_p_isk = new BytePtr[1];
    final BytePtr[] b_p_mps = new BytePtr[1];
    final int[] b_p_ma = new int[1];
    final BytePtr[] b_p_nf = new BytePtr[1];
    final int[] b_p_pi = new int[1];
    final BytePtr[] b_p_qe = new BytePtr[1];
    final long[] b_p_sw = new long[1];
    final int[] b_p_si = new int[1];
    final long[] b_p_sts = new long[1];
    long b_p_sts_nopaste;
    final long[] b_p_ts = new long[1];
    final long[] b_p_tw = new long[1];
    long b_p_tw_nopaste;
    final long[] b_p_wm = new long[1];
    long b_p_wm_nopaste;
    int b_tc_flags;
    final long[] b_p_ul = new long[1];
    boolean b_help;
    boolean b_shortname;
    int b_mapped_ctrl_c;

    public S_file_buffer set(S_file_buffer o$) {
        b_ml.set(o$.b_ml);
        b_nwindows = o$.b_nwindows;
        b_flags = o$.b_flags;
        b_locked = o$.b_locked;
        b_locked_split = o$.b_locked_split;
        b_fnum = o$.b_fnum;
        b_changed[0] = o$.b_changed[0];
        b_changedtick = o$.b_changedtick;
        b_last_changedtick = o$.b_last_changedtick;
        b_last_changedtick_pum = o$.b_last_changedtick_pum;
        b_last_changedtick_i = o$.b_last_changedtick_i;
        b_saving = o$.b_saving;
        b_mod_set = o$.b_mod_set;
        b_mod_top = o$.b_mod_top;
        b_mod_bot = o$.b_mod_bot;
        b_mod_xlines = o$.b_mod_xlines;
        b_wininfo = o$.b_wininfo;
        for (int k$0 = 0; k$0 < 26; k$0++) {
            b_namedm[k$0].set(o$.b_namedm[k$0]);
        }
        b_visual.set(o$.b_visual);
        b_last_cursor.set(o$.b_last_cursor);
        b_last_insert.set(o$.b_last_insert);
        b_last_change.set(o$.b_last_change);
        for (int k$0 = 0; k$0 < 100; k$0++) {
            b_changelist[k$0].set(o$.b_changelist[k$0]);
        }
        b_changelistlen = o$.b_changelistlen;
        b_new_change = o$.b_new_change;
        System.arraycopy(o$.b_chartab, 0, b_chartab, 0, 32);
        System.arraycopy(o$.b_maphash, 0, b_maphash, 0, 256);
        b_first_abbr[0] = o$.b_first_abbr[0];
        b_op_start.set(o$.b_op_start);
        b_op_start_orig.set(o$.b_op_start_orig);
        b_op_end.set(o$.b_op_end);
        b_modified_was_set = o$.b_modified_was_set;
        b_u_oldhead = o$.b_u_oldhead;
        b_u_newhead = o$.b_u_newhead;
        b_u_curhead = o$.b_u_curhead;
        b_u_numhead = o$.b_u_numhead;
        b_u_synced = o$.b_u_synced;
        b_u_seq_last = o$.b_u_seq_last;
        b_u_save_nr_last = o$.b_u_save_nr_last;
        b_u_seq_cur = o$.b_u_seq_cur;
        b_u_time_cur = o$.b_u_time_cur;
        b_u_save_nr_cur = o$.b_u_save_nr_cur;
        b_u_line_ptr.set(o$.b_u_line_ptr);
        b_u_line_lnum = o$.b_u_line_lnum;
        b_u_line_colnr = o$.b_u_line_colnr;
        b_p_initialized = o$.b_p_initialized;
        b_p_ai[0] = o$.b_p_ai[0];
        b_p_ai_nopaste = o$.b_p_ai_nopaste;
        b_bkc_flags = o$.b_bkc_flags;
        b_p_ci[0] = o$.b_p_ci[0];
        b_cot_flags = o$.b_cot_flags;
        b_p_et[0] = o$.b_p_et[0];
        b_p_et_nopaste = o$.b_p_et_nopaste;
        b_p_isk[0] = o$.b_p_isk[0];
        b_p_mps[0] = o$.b_p_mps[0];
        b_p_ma[0] = o$.b_p_ma[0];
        b_p_nf[0] = o$.b_p_nf[0];
        b_p_pi[0] = o$.b_p_pi[0];
        b_p_qe[0] = o$.b_p_qe[0];
        b_p_sw[0] = o$.b_p_sw[0];
        b_p_si[0] = o$.b_p_si[0];
        b_p_sts[0] = o$.b_p_sts[0];
        b_p_sts_nopaste = o$.b_p_sts_nopaste;
        b_p_ts[0] = o$.b_p_ts[0];
        b_p_tw[0] = o$.b_p_tw[0];
        b_p_tw_nopaste = o$.b_p_tw_nopaste;
        b_p_wm[0] = o$.b_p_wm[0];
        b_p_wm_nopaste = o$.b_p_wm_nopaste;
        b_tc_flags = o$.b_tc_flags;
        b_p_ul[0] = o$.b_p_ul[0];
        b_help = o$.b_help;
        b_shortname = o$.b_shortname;
        b_mapped_ctrl_c = o$.b_mapped_ctrl_c;
        return this;
    }

    S_file_buffer copy() {
        return new S_file_buffer().set(this);
    }

    public S_file_buffer zero() {
        return set(new S_file_buffer());
    }

    static S_file_buffer[] array(int n) {
        S_file_buffer[] a = new S_file_buffer[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_file_buffer();
        }
        return a;
    }
}
