// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_frame_S implements Struct<S_frame_S> {
    byte fr_layout;
    int fr_width;
    int fr_height;
    S_window_S fr_win;

    public S_frame_S set(S_frame_S o$) {
        fr_layout = o$.fr_layout;
        fr_width = o$.fr_width;
        fr_height = o$.fr_height;
        fr_win = o$.fr_win;
        return this;
    }

    S_frame_S copy() {
        return new S_frame_S().set(this);
    }

    public S_frame_S zero() {
        return set(new S_frame_S());
    }

    static S_frame_S[] array(int n) {
        S_frame_S[] a = new S_frame_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_frame_S();
        }
        return a;
    }
}
