// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_growarray implements Struct<S_growarray> {
    int ga_len;
    int ga_maxlen;
    int ga_itemsize;
    int ga_growsize;
    Object ga_data;

    public S_growarray set(S_growarray o$) {
        ga_len = o$.ga_len;
        ga_maxlen = o$.ga_maxlen;
        ga_itemsize = o$.ga_itemsize;
        ga_growsize = o$.ga_growsize;
        ga_data = o$.ga_data;
        return this;
    }

    S_growarray copy() {
        return new S_growarray().set(this);
    }

    public S_growarray zero() {
        return set(new S_growarray());
    }

    static S_growarray[] array(int n) {
        S_growarray[] a = new S_growarray[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_growarray();
        }
        return a;
    }
}
