// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_hist_entry implements Struct<S_hist_entry> {
    int hisnum;
    int viminfo;
    BytePtr hisstr;
    long hisstrlen;
    long time_set;

    @Override
    public S_hist_entry set(S_hist_entry o) {
        hisnum = o.hisnum;
        viminfo = o.viminfo;
        hisstr = o.hisstr;
        hisstrlen = o.hisstrlen;
        time_set = o.time_set;
        return this;
    }

    S_hist_entry copy() {
        return new S_hist_entry().set(this);
    }

    @Override
    public S_hist_entry zero() {
        return set(new S_hist_entry());
    }

    static S_hist_entry[] array(int n) {
        S_hist_entry[] a = new S_hist_entry[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_hist_entry();
        }
        return a;
    }
}
