// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_hl_overrides_S implements Struct<S_hl_overrides_S> {
    Ptr<T_hl_override_T> arr;
    int len;
    S_hl_overrides_S next;
    final int[] attr = new int[70];

    public S_hl_overrides_S set(S_hl_overrides_S o$) {
        arr = o$.arr;
        len = o$.len;
        next = o$.next;
        System.arraycopy(o$.attr, 0, attr, 0, 70);
        return this;
    }

    S_hl_overrides_S copy() {
        return new S_hl_overrides_S().set(this);
    }

    public S_hl_overrides_S zero() {
        return set(new S_hl_overrides_S());
    }

    static S_hl_overrides_S[] array(int n) {
        S_hl_overrides_S[] a = new S_hl_overrides_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_hl_overrides_S();
        }
        return a;
    }
}
