// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_initmap implements Struct<S_initmap> {
    BytePtr arg;
    int mode;

    S_initmap() {
    }

    S_initmap(BytePtr arg, int mode) {
        this.arg = arg;
        this.mode = mode;
    }

    @Override
    public S_initmap set(S_initmap o) {
        arg = o.arg;
        mode = o.mode;
        return this;
    }

    S_initmap copy() {
        return new S_initmap().set(this);
    }

    @Override
    public S_initmap zero() {
        return set(new S_initmap());
    }

    static S_initmap[] array(int n) {
        S_initmap[] a = new S_initmap[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_initmap();
        }
        return a;
    }
}
