// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_info_pointer implements Struct<S_info_pointer> {
    S_block_hdr ip_block;
    long ip_low;
    long ip_high;
    int ip_index;

    public S_info_pointer set(S_info_pointer o$) {
        ip_block = o$.ip_block;
        ip_low = o$.ip_low;
        ip_high = o$.ip_high;
        ip_index = o$.ip_index;
        return this;
    }

    S_info_pointer copy() {
        return new S_info_pointer().set(this);
    }

    public S_info_pointer zero() {
        return set(new S_info_pointer());
    }

    static S_info_pointer[] array(int n) {
        S_info_pointer[] a = new S_info_pointer[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_info_pointer();
        }
        return a;
    }
}
