// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_interval implements Struct<S_interval> {
    long first;
    long last;

    S_interval() {
    }

    S_interval(long first, long last) {
        this.first = first;
        this.last = last;
    }

    @Override
    public S_interval set(S_interval o) {
        first = o.first;
        last = o.last;
        return this;
    }

    S_interval copy() {
        return new S_interval().set(this);
    }

    @Override
    public S_interval zero() {
        return set(new S_interval());
    }

    static S_interval[] array(int n) {
        S_interval[] a = new S_interval[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_interval();
        }
        return a;
    }
}
