// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_key_name_entry implements Struct<S_key_name_entry> {
    int enabled;
    int key;
    final T_string_T name = new T_string_T();
    int is_alt;

    S_key_name_entry() {
    }

    S_key_name_entry(int enabled, int key, T_string_T name, int is_alt) {
        this.enabled = enabled;
        this.key = key;
        this.name.set(name);
        this.is_alt = is_alt;
    }

    @Override
    public S_key_name_entry set(S_key_name_entry o) {
        enabled = o.enabled;
        key = o.key;
        name.set(o.name);
        is_alt = o.is_alt;
        return this;
    }

    S_key_name_entry copy() {
        return new S_key_name_entry().set(this);
    }

    @Override
    public S_key_name_entry zero() {
        return set(new S_key_name_entry());
    }

    static S_key_name_entry[] array(int n) {
        S_key_name_entry[] a = new S_key_name_entry[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_key_name_entry();
        }
        return a;
    }
}
