// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_mapblock implements Struct<S_mapblock> {
    final S_mapblock[] m_next = new S_mapblock[1];
    S_mapblock m_alt;
    BytePtr m_keys;
    BytePtr m_str;
    BytePtr m_orig_str;
    int m_keylen;
    int m_mode;
    boolean m_simplified;
    int m_noremap;
    byte m_silent;
    byte m_nowait;

    public S_mapblock set(S_mapblock o$) {
        m_next[0] = o$.m_next[0];
        m_alt = o$.m_alt;
        m_keys = o$.m_keys;
        m_str = o$.m_str;
        m_orig_str = o$.m_orig_str;
        m_keylen = o$.m_keylen;
        m_mode = o$.m_mode;
        m_simplified = o$.m_simplified;
        m_noremap = o$.m_noremap;
        m_silent = o$.m_silent;
        m_nowait = o$.m_nowait;
        return this;
    }

    S_mapblock copy() {
        return new S_mapblock().set(this);
    }

    public S_mapblock zero() {
        return set(new S_mapblock());
    }

    static S_mapblock[] array(int n) {
        S_mapblock[] a = new S_mapblock[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_mapblock();
        }
        return a;
    }
}
