// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_matchitem implements Struct<S_matchitem> {
    S_matchitem mit_next;
    int mit_id;
    int mit_priority;
    BytePtr mit_pattern;
    final T_regmmatch_T mit_match = new T_regmmatch_T();
    Ptr<T_llpos_T> mit_pos_array;
    int mit_pos_count;
    int mit_pos_cur;
    long mit_toplnum;
    long mit_botlnum;
    final T_match_T mit_hl = new T_match_T();
    int mit_hlg_id;

    public S_matchitem set(S_matchitem o$) {
        mit_next = o$.mit_next;
        mit_id = o$.mit_id;
        mit_priority = o$.mit_priority;
        mit_pattern = o$.mit_pattern;
        mit_match.set(o$.mit_match);
        mit_pos_array = o$.mit_pos_array;
        mit_pos_count = o$.mit_pos_count;
        mit_pos_cur = o$.mit_pos_cur;
        mit_toplnum = o$.mit_toplnum;
        mit_botlnum = o$.mit_botlnum;
        mit_hl.set(o$.mit_hl);
        mit_hlg_id = o$.mit_hlg_id;
        return this;
    }

    S_matchitem copy() {
        return new S_matchitem().set(this);
    }

    public S_matchitem zero() {
        return set(new S_matchitem());
    }

    static S_matchitem[] array(int n) {
        S_matchitem[] a = new S_matchitem[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_matchitem();
        }
        return a;
    }
}
