// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_memline implements Struct<S_memline> {
    long ml_line_count;
    S_block_hdr ml_root;
    Ptr<S_info_pointer> ml_stack;
    int ml_stack_top;
    int ml_stack_size;
    int ml_flags;
    int ml_line_len;
    int ml_line_textlen;
    long ml_line_lnum;
    BytePtr ml_line_ptr;
    S_block_hdr ml_locked;
    long ml_locked_low;
    long ml_locked_high;
    int ml_locked_lineadd;

    public S_memline set(S_memline o$) {
        ml_line_count = o$.ml_line_count;
        ml_root = o$.ml_root;
        ml_stack = o$.ml_stack;
        ml_stack_top = o$.ml_stack_top;
        ml_stack_size = o$.ml_stack_size;
        ml_flags = o$.ml_flags;
        ml_line_len = o$.ml_line_len;
        ml_line_textlen = o$.ml_line_textlen;
        ml_line_lnum = o$.ml_line_lnum;
        ml_line_ptr = o$.ml_line_ptr;
        ml_locked = o$.ml_locked;
        ml_locked_low = o$.ml_locked_low;
        ml_locked_high = o$.ml_locked_high;
        ml_locked_lineadd = o$.ml_locked_lineadd;
        return this;
    }

    S_memline copy() {
        return new S_memline().set(this);
    }

    public S_memline zero() {
        return set(new S_memline());
    }

    static S_memline[] array(int n) {
        S_memline[] a = new S_memline[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_memline();
        }
        return a;
    }
}
