// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_modmasktable implements Struct<S_modmasktable> {
    short mod_mask;
    short mod_flag;
    byte name;

    S_modmasktable() {
    }

    S_modmasktable(int mod_mask, int mod_flag, int name) {
        this.mod_mask = (short) mod_mask;
        this.mod_flag = (short) mod_flag;
        this.name = (byte) name;
    }

    @Override
    public S_modmasktable set(S_modmasktable o) {
        mod_mask = o.mod_mask;
        mod_flag = o.mod_flag;
        name = o.name;
        return this;
    }

    S_modmasktable copy() {
        return new S_modmasktable().set(this);
    }

    @Override
    public S_modmasktable zero() {
        return set(new S_modmasktable());
    }

    static S_modmasktable[] array(int n) {
        S_modmasktable[] a = new S_modmasktable[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_modmasktable();
        }
        return a;
    }
}
