// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_msg_hist implements Struct<S_msg_hist> {
    S_msg_hist next;
    BytePtr msg;
    int attr;

    @Override
    public S_msg_hist set(S_msg_hist o) {
        next = o.next;
        msg = o.msg;
        attr = o.attr;
        return this;
    }

    S_msg_hist copy() {
        return new S_msg_hist().set(this);
    }

    @Override
    public S_msg_hist zero() {
        return set(new S_msg_hist());
    }

    static S_msg_hist[] array(int n) {
        S_msg_hist[] a = new S_msg_hist[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_msg_hist();
        }
        return a;
    }
}
