// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_msgchunk_S implements Struct<S_msgchunk_S> {
    S_msgchunk_S sb_next;
    final S_msgchunk_S[] sb_prev = new S_msgchunk_S[1];
    byte sb_eol;
    int sb_msg_col;
    int sb_attr;
    BytePtr sb_text;

    public S_msgchunk_S set(S_msgchunk_S o$) {
        sb_next = o$.sb_next;
        sb_prev[0] = o$.sb_prev[0];
        sb_eol = o$.sb_eol;
        sb_msg_col = o$.sb_msg_col;
        sb_attr = o$.sb_attr;
        sb_text = o$.sb_text;
        return this;
    }

    S_msgchunk_S copy() {
        return new S_msgchunk_S().set(this);
    }

    public S_msgchunk_S zero() {
        return set(new S_msgchunk_S());
    }

    static S_msgchunk_S[] array(int n) {
        S_msgchunk_S[] a = new S_msgchunk_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_msgchunk_S();
        }
        return a;
    }
}
