// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_nv_cmd implements Struct<S_nv_cmd> {
    int cmd_char;
    Fn5 cmd_func;
    short cmd_flags;
    short cmd_arg;

    S_nv_cmd() {
    }

    S_nv_cmd(int cmd_char, Fn5 cmd_func, int cmd_flags, int cmd_arg) {
        this.cmd_char = cmd_char;
        this.cmd_func = cmd_func;
        this.cmd_flags = (short) cmd_flags;
        this.cmd_arg = (short) cmd_arg;
    }

    public S_nv_cmd set(S_nv_cmd o$) {
        cmd_char = o$.cmd_char;
        cmd_func = o$.cmd_func;
        cmd_flags = o$.cmd_flags;
        cmd_arg = o$.cmd_arg;
        return this;
    }

    S_nv_cmd copy() {
        return new S_nv_cmd().set(this);
    }

    public S_nv_cmd zero() {
        return set(new S_nv_cmd());
    }

    static S_nv_cmd[] array(int n) {
        S_nv_cmd[] a = new S_nv_cmd[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_nv_cmd();
        }
        return a;
    }
}
