// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_oparg_S implements Struct<S_oparg_S> {
    int op_type;
    int regname;
    int motion_type;
    int motion_force;
    int use_reg_one;
    int inclusive;
    int end_adjusted;
    final T_pos_T start = new T_pos_T();
    final T_pos_T end = new T_pos_T();
    long line_count;
    int empty;
    int is_VIsual;
    int block_mode;
    final int[] start_vcol = new int[1];
    final int[] end_vcol = new int[1];
    long prev_opcount;
    long prev_count0;
    int excl_tr_ws;

    public S_oparg_S set(S_oparg_S o$) {
        op_type = o$.op_type;
        regname = o$.regname;
        motion_type = o$.motion_type;
        motion_force = o$.motion_force;
        use_reg_one = o$.use_reg_one;
        inclusive = o$.inclusive;
        end_adjusted = o$.end_adjusted;
        start.set(o$.start);
        end.set(o$.end);
        line_count = o$.line_count;
        empty = o$.empty;
        is_VIsual = o$.is_VIsual;
        block_mode = o$.block_mode;
        start_vcol[0] = o$.start_vcol[0];
        end_vcol[0] = o$.end_vcol[0];
        prev_opcount = o$.prev_opcount;
        prev_count0 = o$.prev_count0;
        excl_tr_ws = o$.excl_tr_ws;
        return this;
    }

    S_oparg_S copy() {
        return new S_oparg_S().set(this);
    }

    public S_oparg_S zero() {
        return set(new S_oparg_S());
    }

    static S_oparg_S[] array(int n) {
        S_oparg_S[] a = new S_oparg_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_oparg_S();
        }
        return a;
    }
}
