// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_pointer_entry implements Struct<S_pointer_entry> {
    S_block_hdr pe_block;
    long pe_line_count;

    public S_pointer_entry set(S_pointer_entry o$) {
        pe_block = o$.pe_block;
        pe_line_count = o$.pe_line_count;
        return this;
    }

    S_pointer_entry copy() {
        return new S_pointer_entry().set(this);
    }

    public S_pointer_entry zero() {
        return set(new S_pointer_entry());
    }

    static S_pointer_entry[] array(int n) {
        S_pointer_entry[] a = new S_pointer_entry[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_pointer_entry();
        }
        return a;
    }
}
