// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_pointer_block implements Struct<S_pointer_block> {
    short pb_count;
    final S_pointer_entry[] pb_pointer = S_pointer_entry.array(255);

    public S_pointer_block set(S_pointer_block o$) {
        pb_count = o$.pb_count;
        for (int k$0 = 0; k$0 < 255; k$0++) {
            pb_pointer[k$0].set(o$.pb_pointer[k$0]);
        }
        return this;
    }

    S_pointer_block copy() {
        return new S_pointer_block().set(this);
    }

    public S_pointer_block zero() {
        return set(new S_pointer_block());
    }

    static S_pointer_block[] array(int n) {
        S_pointer_block[] a = new S_pointer_block[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_pointer_block();
        }
        return a;
    }
}
