// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_regbehind_S implements Struct<S_regbehind_S> {
    final T_regsave_T save_after = new T_regsave_T();
    final T_regsave_T save_behind = new T_regsave_T();
    boolean save_need_clear_subexpr;
    final T_save_se_T[] save_start = T_save_se_T.array(10);
    final T_save_se_T[] save_end = T_save_se_T.array(10);

    @Override
    public S_regbehind_S set(S_regbehind_S o) {
        save_after.set(o.save_after);
        save_behind.set(o.save_behind);
        save_need_clear_subexpr = o.save_need_clear_subexpr;
        for (int k$0 = 0; k$0 < 10; k$0++) {
            save_start[k$0].set(o.save_start[k$0]);
        }
        for (int k$0 = 0; k$0 < 10; k$0++) {
            save_end[k$0].set(o.save_end[k$0]);
        }
        return this;
    }

    S_regbehind_S copy() {
        return new S_regbehind_S().set(this);
    }

    @Override
    public S_regbehind_S zero() {
        return set(new S_regbehind_S());
    }

    static S_regbehind_S[] array(int n) {
        S_regbehind_S[] a = new S_regbehind_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_regbehind_S();
        }
        return a;
    }
}
