// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_regprog implements Struct<S_regprog> {
    int regflags;
    int re_engine;
    int re_flags;
    boolean re_in_use;
    int regstart;
    byte reganch;
    BytePtr regmust;
    int regmlen;
    BytePtr program;

    @Override
    public S_regprog set(S_regprog o) {
        regflags = o.regflags;
        re_engine = o.re_engine;
        re_flags = o.re_flags;
        re_in_use = o.re_in_use;
        regstart = o.regstart;
        reganch = o.reganch;
        regmust = o.regmust;
        regmlen = o.regmlen;
        program = o.program;
        return this;
    }

    S_regprog copy() {
        return new S_regprog().set(this);
    }

    @Override
    public S_regprog zero() {
        return set(new S_regprog());
    }

    static S_regprog[] array(int n) {
        S_regprog[] a = new S_regprog[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_regprog();
        }
        return a;
    }
}
