// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_regitem_S implements Struct<S_regitem_S> {
    int rs_state;
    short rs_no;
    BytePtr rs_scan;
    final A_6 rs_un = new A_6();

    @Override
    public S_regitem_S set(S_regitem_S o) {
        rs_state = o.rs_state;
        rs_no = o.rs_no;
        rs_scan = o.rs_scan;
        rs_un.set(o.rs_un);
        return this;
    }

    S_regitem_S copy() {
        return new S_regitem_S().set(this);
    }

    @Override
    public S_regitem_S zero() {
        return set(new S_regitem_S());
    }

    static S_regitem_S[] array(int n) {
        S_regitem_S[] a = new S_regitem_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_regitem_S();
        }
        return a;
    }
}
