// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_regengine_S implements Struct<S_regengine_S> {
    final T_regexec_T rex = new T_regexec_T();
    int rex_in_use;
    final S_growarray regstack = new S_growarray();
    final S_growarray regstack_star = new S_growarray();
    final S_growarray regstack_behind = new S_growarray();
    final S_growarray backpos = new S_growarray();
    int regstack_bytes;
    final T_regsave_T behind_pos = new T_regsave_T();
    long bl_minval;
    long bl_maxval;
    final long[] brace_min = new long[10];
    final long[] brace_max = new long[10];
    final int[] brace_count = new int[10];
    BytePtr reg_tofree;
    int reg_tofreelen;
    boolean reg_toolong;
    final T_string_T alone = new T_string_T();
    boolean failed;

    @Override
    public S_regengine_S set(S_regengine_S o) {
        rex.set(o.rex);
        rex_in_use = o.rex_in_use;
        regstack.set(o.regstack);
        regstack_star.set(o.regstack_star);
        regstack_behind.set(o.regstack_behind);
        backpos.set(o.backpos);
        regstack_bytes = o.regstack_bytes;
        behind_pos.set(o.behind_pos);
        bl_minval = o.bl_minval;
        bl_maxval = o.bl_maxval;
        System.arraycopy(o.brace_min, 0, brace_min, 0, 10);
        System.arraycopy(o.brace_max, 0, brace_max, 0, 10);
        System.arraycopy(o.brace_count, 0, brace_count, 0, 10);
        reg_tofree = o.reg_tofree;
        reg_tofreelen = o.reg_tofreelen;
        reg_toolong = o.reg_toolong;
        alone.set(o.alone);
        failed = o.failed;
        return this;
    }

    S_regengine_S copy() {
        return new S_regengine_S().set(this);
    }

    @Override
    public S_regengine_S zero() {
        return set(new S_regengine_S());
    }

    static S_regengine_S[] array(int n) {
        S_regengine_S[] a = new S_regengine_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_regengine_S();
        }
        return a;
    }
}
