// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_regstar_S implements Struct<S_regstar_S> {
    int nextb;
    int nextb_ic;
    long count;
    long minval;
    long maxval;

    public S_regstar_S set(S_regstar_S o$) {
        nextb = o$.nextb;
        nextb_ic = o$.nextb_ic;
        count = o$.count;
        minval = o$.minval;
        maxval = o$.maxval;
        return this;
    }

    S_regstar_S copy() {
        return new S_regstar_S().set(this);
    }

    public S_regstar_S zero() {
        return set(new S_regstar_S());
    }

    static S_regstar_S[] array(int n) {
        S_regstar_S[] a = new S_regstar_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_regstar_S();
        }
        return a;
    }
}
