// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_searchstat implements Struct<S_searchstat> {
    int cur;
    int cnt;
    boolean exact_match;
    int incomplete;
    int last_maxcount;

    public S_searchstat set(S_searchstat o$) {
        cur = o$.cur;
        cnt = o$.cnt;
        exact_match = o$.exact_match;
        incomplete = o$.incomplete;
        last_maxcount = o$.last_maxcount;
        return this;
    }

    S_searchstat copy() {
        return new S_searchstat().set(this);
    }

    public S_searchstat zero() {
        return set(new S_searchstat());
    }

    static S_searchstat[] array(int n) {
        S_searchstat[] a = new S_searchstat[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_searchstat();
        }
        return a;
    }
}
