// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_signalinfo implements Struct<S_signalinfo> {
    int sig;
    BytePtr name;

    S_signalinfo() {
    }

    S_signalinfo(int sig, BytePtr name) {
        this.sig = sig;
        this.name = name;
    }

    public S_signalinfo set(S_signalinfo o$) {
        sig = o$.sig;
        name = o$.name;
        return this;
    }

    S_signalinfo copy() {
        return new S_signalinfo().set(this);
    }

    public S_signalinfo zero() {
        return set(new S_signalinfo());
    }

    static S_signalinfo[] array(int n) {
        S_signalinfo[] a = new S_signalinfo[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_signalinfo();
        }
        return a;
    }
}
