// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_soffset implements Struct<S_soffset> {
    int dir;
    int line;
    int end;
    long off;

    S_soffset() {
    }

    S_soffset(int dir, int line, int end, long off) {
        this.dir = dir;
        this.line = line;
        this.end = end;
        this.off = off;
    }

    @Override
    public S_soffset set(S_soffset o) {
        dir = o.dir;
        line = o.line;
        end = o.end;
        off = o.off;
        return this;
    }

    S_soffset copy() {
        return new S_soffset().set(this);
    }

    @Override
    public S_soffset zero() {
        return set(new S_soffset());
    }

    static S_soffset[] array(int n) {
        S_soffset[] a = new S_soffset[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_soffset();
        }
        return a;
    }
}
