// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_spat implements Struct<S_spat> {
    BytePtr pat;
    long patlen;
    int magic;
    int no_scs;
    final S_soffset off = new S_soffset();

    S_spat() {
    }

    S_spat(BytePtr pat, long patlen, int magic, int no_scs, S_soffset off) {
        this.pat = pat;
        this.patlen = patlen;
        this.magic = magic;
        this.no_scs = no_scs;
        this.off.set(off);
    }

    public S_spat set(S_spat o$) {
        pat = o$.pat;
        patlen = o$.patlen;
        magic = o$.magic;
        no_scs = o$.no_scs;
        off.set(o$.off);
        return this;
    }

    S_spat copy() {
        return new S_spat().set(this);
    }

    public S_spat zero() {
        return set(new S_spat());
    }

    static S_spat[] array(int n) {
        S_spat[] a = new S_spat[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_spat();
        }
        return a;
    }
}
