// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_taggy implements Struct<S_taggy> {
    final S_filemark fmark = new S_filemark();

    public S_taggy set(S_taggy o$) {
        fmark.set(o$.fmark);
        return this;
    }

    S_taggy copy() {
        return new S_taggy().set(this);
    }

    public S_taggy zero() {
        return set(new S_taggy());
    }

    static S_taggy[] array(int n) {
        S_taggy[] a = new S_taggy[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_taggy();
        }
        return a;
    }
}
