// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_tabpage_S implements Struct<S_tabpage_S> {
    S_frame_S tp_topframe;
    S_window_S tp_curwin;
    long tp_ch_used;

    @Override
    public S_tabpage_S set(S_tabpage_S o) {
        tp_topframe = o.tp_topframe;
        tp_curwin = o.tp_curwin;
        tp_ch_used = o.tp_ch_used;
        return this;
    }

    S_tabpage_S copy() {
        return new S_tabpage_S().set(this);
    }

    @Override
    public S_tabpage_S zero() {
        return set(new S_tabpage_S());
    }

    static S_tabpage_S[] array(int n) {
        S_tabpage_S[] a = new S_tabpage_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_tabpage_S();
        }
        return a;
    }
}
