// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_termcode implements Struct<S_termcode> {
    final byte[] name = new byte[2];
    BytePtr code;
    int len;
    int modlen;

    @Override
    public S_termcode set(S_termcode o) {
        System.arraycopy(o.name, 0, name, 0, 2);
        code = o.code;
        len = o.len;
        modlen = o.modlen;
        return this;
    }

    S_termcode copy() {
        return new S_termcode().set(this);
    }

    @Override
    public S_termcode zero() {
        return set(new S_termcode());
    }

    static S_termcode[] array(int n) {
        S_termcode[] a = new S_termcode[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_termcode();
        }
        return a;
    }
}
