// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_u_entry implements Struct<S_u_entry> {
    S_u_entry ue_next;
    long ue_top;
    long ue_bot;
    long ue_lcount;
    Ptr<T_undoline_T> ue_array;
    long ue_size;

    public S_u_entry set(S_u_entry o$) {
        ue_next = o$.ue_next;
        ue_top = o$.ue_top;
        ue_bot = o$.ue_bot;
        ue_lcount = o$.ue_lcount;
        ue_array = o$.ue_array;
        ue_size = o$.ue_size;
        return this;
    }

    S_u_entry copy() {
        return new S_u_entry().set(this);
    }

    public S_u_entry zero() {
        return set(new S_u_entry());
    }

    static S_u_entry[] array(int n) {
        S_u_entry[] a = new S_u_entry[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_u_entry();
        }
        return a;
    }
}
