// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_u_header implements Struct<S_u_header> {
    S_u_header uh_next;
    S_u_header uh_prev;
    S_u_header uh_alt_next;
    S_u_header uh_alt_prev;
    long uh_seq;
    int uh_walk;
    S_u_entry uh_entry;
    S_u_entry uh_getbot_entry;
    final T_pos_T uh_cursor = new T_pos_T();
    long uh_cursor_vcol;
    int uh_flags;
    final T_pos_T[] uh_namedm = T_pos_T.array(26);
    final T_visualinfo_T uh_visual = new T_visualinfo_T();
    long uh_time;
    long uh_save_nr;

    public S_u_header set(S_u_header o$) {
        uh_next = o$.uh_next;
        uh_prev = o$.uh_prev;
        uh_alt_next = o$.uh_alt_next;
        uh_alt_prev = o$.uh_alt_prev;
        uh_seq = o$.uh_seq;
        uh_walk = o$.uh_walk;
        uh_entry = o$.uh_entry;
        uh_getbot_entry = o$.uh_getbot_entry;
        uh_cursor.set(o$.uh_cursor);
        uh_cursor_vcol = o$.uh_cursor_vcol;
        uh_flags = o$.uh_flags;
        for (int k$0 = 0; k$0 < 26; k$0++) {
            uh_namedm[k$0].set(o$.uh_namedm[k$0]);
        }
        uh_visual.set(o$.uh_visual);
        uh_time = o$.uh_time;
        uh_save_nr = o$.uh_save_nr;
        return this;
    }

    S_u_header copy() {
        return new S_u_header().set(this);
    }

    public S_u_header zero() {
        return set(new S_u_header());
    }

    static S_u_header[] array(int n) {
        S_u_header[] a = new S_u_header[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_u_header();
        }
        return a;
    }
}
