// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_vimoption implements Struct<S_vimoption> {
    BytePtr fullname;
    BytePtr shortname;
    final long[] flags = new long[1];
    final T_optvar_T var_ = new T_optvar_T();
    int indir;
    Fn6 opt_did_set_cb;
    Fn11 opt_expand_cb;
    final BytePtr[] def_str = new BytePtr[2];
    final long[] def_num = new long[2];

    S_vimoption() {
    }

    S_vimoption(BytePtr fullname, BytePtr shortname, long flags, T_optvar_T var_, int indir, Fn6 opt_did_set_cb,
            Fn11 opt_expand_cb, BytePtr[] def_str, long[] def_num) {
        this.fullname = fullname;
        this.shortname = shortname;
        this.flags[0] = flags;
        this.var_.set(var_);
        this.indir = indir;
        this.opt_did_set_cb = opt_did_set_cb;
        this.opt_expand_cb = opt_expand_cb;
        System.arraycopy(def_str, 0, this.def_str, 0, def_str.length);
        System.arraycopy(def_num, 0, this.def_num, 0, def_num.length);
    }

    public S_vimoption set(S_vimoption o$) {
        fullname = o$.fullname;
        shortname = o$.shortname;
        flags[0] = o$.flags[0];
        var_.set(o$.var_);
        indir = o$.indir;
        opt_did_set_cb = o$.opt_did_set_cb;
        opt_expand_cb = o$.opt_expand_cb;
        System.arraycopy(o$.def_str, 0, def_str, 0, 2);
        System.arraycopy(o$.def_num, 0, def_num, 0, 2);
        return this;
    }

    S_vimoption copy() {
        return new S_vimoption().set(this);
    }

    public S_vimoption zero() {
        return set(new S_vimoption());
    }

    static S_vimoption[] array(int n) {
        S_vimoption[] a = new S_vimoption[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_vimoption();
        }
        return a;
    }
}
