// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_w_line implements Struct<S_w_line> {
    long wl_lnum;
    short wl_size;
    byte wl_valid;

    public S_w_line set(S_w_line o$) {
        wl_lnum = o$.wl_lnum;
        wl_size = o$.wl_size;
        wl_valid = o$.wl_valid;
        return this;
    }

    S_w_line copy() {
        return new S_w_line().set(this);
    }

    public S_w_line zero() {
        return set(new S_w_line());
    }

    static S_w_line[] array(int n) {
        S_w_line[] a = new S_w_line[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_w_line();
        }
        return a;
    }
}
