// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_wininfo_S implements Struct<S_wininfo_S> {
    S_wininfo_S wi_next;
    S_wininfo_S wi_prev;
    S_window_S wi_win;
    final T_pos_T wi_fpos = new T_pos_T();
    final T_winopt_T wi_opt = new T_winopt_T();
    boolean wi_optset;

    @Override
    public S_wininfo_S set(S_wininfo_S o) {
        wi_next = o.wi_next;
        wi_prev = o.wi_prev;
        wi_win = o.wi_win;
        wi_fpos.set(o.wi_fpos);
        wi_opt.set(o.wi_opt);
        wi_optset = o.wi_optset;
        return this;
    }

    S_wininfo_S copy() {
        return new S_wininfo_S().set(this);
    }

    @Override
    public S_wininfo_S zero() {
        return set(new S_wininfo_S());
    }

    static S_wininfo_S[] array(int n) {
        S_wininfo_S[] a = new S_wininfo_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_wininfo_S();
        }
        return a;
    }
}
