// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class S_window_S implements Struct<S_window_S> {
    S_file_buffer w_buffer;
    S_frame_S w_frame;
    final T_pos_T w_cursor = new T_pos_T();
    int w_curswant;
    boolean w_set_curswant;
    byte w_old_visual_mode;
    long w_old_cursor_lnum;
    int w_old_cursor_fcol;
    int w_old_cursor_lcol;
    long w_old_visual_lnum;
    int w_old_visual_col;
    int w_old_curswant;
    long w_last_cursor_lnum_rnu;
    final T_lcs_chars_T w_lcs_chars = new T_lcs_chars_T();
    final T_fill_chars_T w_fill_chars = new T_fill_chars_T();
    long w_topline;
    long w_botline;
    int w_leftcol;
    int w_skipcol;
    int w_empty_rows;
    long w_last_topline;
    int w_last_leftcol;
    int w_last_skipcol;
    int w_last_width;
    int w_last_height;
    int w_winrow;
    int w_height;
    int w_prev_winrow;
    int w_prev_height;
    int w_status_height;
    int w_wincol;
    int w_width;
    int w_vsep_width;
    boolean w_do_win_fix_cursor;
    int w_valid;
    final T_pos_T w_valid_cursor = new T_pos_T();
    int w_valid_leftcol;
    int w_valid_skipcol;
    int w_cline_height;
    int w_cline_row;
    final int[] w_virtcol = new int[1];
    int w_wrow;
    int w_wcol;
    int w_lines_valid;
    Ptr<S_w_line> w_lines;
    int w_redr_type;
    int w_upd_rows;
    long w_redraw_top;
    long w_redraw_bot;
    boolean w_redr_status;
    final T_pos_T w_ru_cursor = new T_pos_T();
    int w_ru_virtcol;
    long w_ru_topline;
    long w_ru_line_count;
    boolean w_ru_empty;
    final T_winopt_T w_onebuf_opt = new T_winopt_T();
    final T_winopt_T w_allbuf_opt = new T_winopt_T();
    long w_scbind_pos;
    final T_pos_T w_pcmark = new T_pos_T();
    final T_pos_T w_prev_pcmark = new T_pos_T();
    int w_changelistidx;
    S_matchitem w_match_head;
    int w_next_match_id;
    final S_taggy[] w_tagstack = S_taggy.array(20);
    int w_tagstacklen;
    int w_fraction;
    int w_prev_fraction_row;
    Ptr<T_hl_override_T> w_hl;
    int w_hl_len;
    int w_hlfwin_id;

    public S_window_S set(S_window_S o$) {
        w_buffer = o$.w_buffer;
        w_frame = o$.w_frame;
        w_cursor.set(o$.w_cursor);
        w_curswant = o$.w_curswant;
        w_set_curswant = o$.w_set_curswant;
        w_old_visual_mode = o$.w_old_visual_mode;
        w_old_cursor_lnum = o$.w_old_cursor_lnum;
        w_old_cursor_fcol = o$.w_old_cursor_fcol;
        w_old_cursor_lcol = o$.w_old_cursor_lcol;
        w_old_visual_lnum = o$.w_old_visual_lnum;
        w_old_visual_col = o$.w_old_visual_col;
        w_old_curswant = o$.w_old_curswant;
        w_last_cursor_lnum_rnu = o$.w_last_cursor_lnum_rnu;
        w_lcs_chars.set(o$.w_lcs_chars);
        w_fill_chars.set(o$.w_fill_chars);
        w_topline = o$.w_topline;
        w_botline = o$.w_botline;
        w_leftcol = o$.w_leftcol;
        w_skipcol = o$.w_skipcol;
        w_empty_rows = o$.w_empty_rows;
        w_last_topline = o$.w_last_topline;
        w_last_leftcol = o$.w_last_leftcol;
        w_last_skipcol = o$.w_last_skipcol;
        w_last_width = o$.w_last_width;
        w_last_height = o$.w_last_height;
        w_winrow = o$.w_winrow;
        w_height = o$.w_height;
        w_prev_winrow = o$.w_prev_winrow;
        w_prev_height = o$.w_prev_height;
        w_status_height = o$.w_status_height;
        w_wincol = o$.w_wincol;
        w_width = o$.w_width;
        w_vsep_width = o$.w_vsep_width;
        w_do_win_fix_cursor = o$.w_do_win_fix_cursor;
        w_valid = o$.w_valid;
        w_valid_cursor.set(o$.w_valid_cursor);
        w_valid_leftcol = o$.w_valid_leftcol;
        w_valid_skipcol = o$.w_valid_skipcol;
        w_cline_height = o$.w_cline_height;
        w_cline_row = o$.w_cline_row;
        w_virtcol[0] = o$.w_virtcol[0];
        w_wrow = o$.w_wrow;
        w_wcol = o$.w_wcol;
        w_lines_valid = o$.w_lines_valid;
        w_lines = o$.w_lines;
        w_redr_type = o$.w_redr_type;
        w_upd_rows = o$.w_upd_rows;
        w_redraw_top = o$.w_redraw_top;
        w_redraw_bot = o$.w_redraw_bot;
        w_redr_status = o$.w_redr_status;
        w_ru_cursor.set(o$.w_ru_cursor);
        w_ru_virtcol = o$.w_ru_virtcol;
        w_ru_topline = o$.w_ru_topline;
        w_ru_line_count = o$.w_ru_line_count;
        w_ru_empty = o$.w_ru_empty;
        w_onebuf_opt.set(o$.w_onebuf_opt);
        w_allbuf_opt.set(o$.w_allbuf_opt);
        w_scbind_pos = o$.w_scbind_pos;
        w_pcmark.set(o$.w_pcmark);
        w_prev_pcmark.set(o$.w_prev_pcmark);
        w_changelistidx = o$.w_changelistidx;
        w_match_head = o$.w_match_head;
        w_next_match_id = o$.w_next_match_id;
        for (int k$0 = 0; k$0 < 20; k$0++) {
            w_tagstack[k$0].set(o$.w_tagstack[k$0]);
        }
        w_tagstacklen = o$.w_tagstacklen;
        w_fraction = o$.w_fraction;
        w_prev_fraction_row = o$.w_prev_fraction_row;
        w_hl = o$.w_hl;
        w_hl_len = o$.w_hl_len;
        w_hlfwin_id = o$.w_hlfwin_id;
        return this;
    }

    S_window_S copy() {
        return new S_window_S().set(this);
    }

    public S_window_S zero() {
        return set(new S_window_S());
    }

    static S_window_S[] array(int n) {
        S_window_S[] a = new S_window_S[n];
        for (int k = 0; k < n; k++) {
            a[k] = new S_window_S();
        }
        return a;
    }
}
