// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_builtin_tcap_T implements Struct<T_builtin_tcap_T> {
    BytePtr bitc_name;
    Ptr<T_tcap_entry_T> bitc_table;

    T_builtin_tcap_T() {
    }

    T_builtin_tcap_T(BytePtr bitc_name, Ptr<T_tcap_entry_T> bitc_table) {
        this.bitc_name = bitc_name;
        this.bitc_table = bitc_table;
    }

    public T_builtin_tcap_T set(T_builtin_tcap_T o$) {
        bitc_name = o$.bitc_name;
        bitc_table = o$.bitc_table;
        return this;
    }

    T_builtin_tcap_T copy() {
        return new T_builtin_tcap_T().set(this);
    }

    public T_builtin_tcap_T zero() {
        return set(new T_builtin_tcap_T());
    }

    static T_builtin_tcap_T[] array(int n) {
        T_builtin_tcap_T[] a = new T_builtin_tcap_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_builtin_tcap_T();
        }
        return a;
    }
}
