// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_bufref_T implements Struct<T_bufref_T> {
    S_file_buffer br_buf;
    int br_fnum;
    int br_buf_free_count;

    @Override
    public T_bufref_T set(T_bufref_T o) {
        br_buf = o.br_buf;
        br_fnum = o.br_fnum;
        br_buf_free_count = o.br_buf_free_count;
        return this;
    }

    T_bufref_T copy() {
        return new T_bufref_T().set(this);
    }

    @Override
    public T_bufref_T zero() {
        return set(new T_bufref_T());
    }

    static T_bufref_T[] array(int n) {
        T_bufref_T[] a = new T_bufref_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_bufref_T();
        }
        return a;
    }
}
