// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_chartabsize_T implements Struct<T_chartabsize_T> {
    S_window_S cts_win;
    BytePtr cts_line;
    BytePtr cts_ptr;
    int cts_vcol;
    int cts_max_head_vcol;

    public T_chartabsize_T set(T_chartabsize_T o$) {
        cts_win = o$.cts_win;
        cts_line = o$.cts_line;
        cts_ptr = o$.cts_ptr;
        cts_vcol = o$.cts_vcol;
        cts_max_head_vcol = o$.cts_max_head_vcol;
        return this;
    }

    T_chartabsize_T copy() {
        return new T_chartabsize_T().set(this);
    }

    public T_chartabsize_T zero() {
        return set(new T_chartabsize_T());
    }

    static T_chartabsize_T[] array(int n) {
        T_chartabsize_T[] a = new T_chartabsize_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_chartabsize_T();
        }
        return a;
    }
}
