// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_cmdline_browse_history__out_T implements Struct<T_cmdline_browse_history__out_T> {
    int r__;
    BytePtr curcmdstr;
    long curcmdstrlen;
    int hiscnt_p;

    public T_cmdline_browse_history__out_T set(T_cmdline_browse_history__out_T o$) {
        r__ = o$.r__;
        curcmdstr = o$.curcmdstr;
        curcmdstrlen = o$.curcmdstrlen;
        hiscnt_p = o$.hiscnt_p;
        return this;
    }

    T_cmdline_browse_history__out_T copy() {
        return new T_cmdline_browse_history__out_T().set(this);
    }

    public T_cmdline_browse_history__out_T zero() {
        return set(new T_cmdline_browse_history__out_T());
    }

    static T_cmdline_browse_history__out_T[] array(int n) {
        T_cmdline_browse_history__out_T[] a = new T_cmdline_browse_history__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_cmdline_browse_history__out_T();
        }
        return a;
    }
}
