// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_cmdmod_T implements Struct<T_cmdmod_T> {
    int cmod_flags;
    final T_regmatch_T cmod_filter_regmatch = new T_regmatch_T();
    boolean cmod_filter_force;
    int cmod_verbose;
    long cmod_verbose_save;
    int cmod_save_msg_silent;
    int cmod_save_msg_scroll;
    int cmod_did_esilent;

    @Override
    public T_cmdmod_T set(T_cmdmod_T o) {
        cmod_flags = o.cmod_flags;
        cmod_filter_regmatch.set(o.cmod_filter_regmatch);
        cmod_filter_force = o.cmod_filter_force;
        cmod_verbose = o.cmod_verbose;
        cmod_verbose_save = o.cmod_verbose_save;
        cmod_save_msg_silent = o.cmod_save_msg_silent;
        cmod_save_msg_scroll = o.cmod_save_msg_scroll;
        cmod_did_esilent = o.cmod_did_esilent;
        return this;
    }

    T_cmdmod_T copy() {
        return new T_cmdmod_T().set(this);
    }

    @Override
    public T_cmdmod_T zero() {
        return set(new T_cmdmod_T());
    }

    static T_cmdmod_T[] array(int n) {
        T_cmdmod_T[] a = new T_cmdmod_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_cmdmod_T();
        }
        return a;
    }
}
