// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_cmdline_info_T implements Struct<T_cmdline_info_T> {
    BytePtr cmdbuff;
    int cmdbufflen;
    int cmdlen;
    int cmdpos;
    int cmdspos;
    int cmdfirstc;
    int cmdindent;
    BytePtr cmdprompt;
    int cmdattr;
    boolean overstrike;
    S_expand xpc;
    int xp_context;
    boolean cmdbuff_replaced;

    public T_cmdline_info_T set(T_cmdline_info_T o$) {
        cmdbuff = o$.cmdbuff;
        cmdbufflen = o$.cmdbufflen;
        cmdlen = o$.cmdlen;
        cmdpos = o$.cmdpos;
        cmdspos = o$.cmdspos;
        cmdfirstc = o$.cmdfirstc;
        cmdindent = o$.cmdindent;
        cmdprompt = o$.cmdprompt;
        cmdattr = o$.cmdattr;
        overstrike = o$.overstrike;
        xpc = o$.xpc;
        xp_context = o$.xp_context;
        cmdbuff_replaced = o$.cmdbuff_replaced;
        return this;
    }

    T_cmdline_info_T copy() {
        return new T_cmdline_info_T().set(this);
    }

    public T_cmdline_info_T zero() {
        return set(new T_cmdline_info_T());
    }

    static T_cmdline_info_T[] array(int n) {
        T_cmdline_info_T[] a = new T_cmdline_info_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_cmdline_info_T();
        }
        return a;
    }
}
