// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_copy_option_part__out_T implements Struct<T_copy_option_part__out_T> {
    int r__;
    BytePtr option;

    public T_copy_option_part__out_T set(T_copy_option_part__out_T o$) {
        r__ = o$.r__;
        option = o$.option;
        return this;
    }

    T_copy_option_part__out_T copy() {
        return new T_copy_option_part__out_T().set(this);
    }

    public T_copy_option_part__out_T zero() {
        return set(new T_copy_option_part__out_T());
    }

    static T_copy_option_part__out_T[] array(int n) {
        T_copy_option_part__out_T[] a = new T_copy_option_part__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_copy_option_part__out_T();
        }
        return a;
    }
}
