// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_convertStruct implements Struct<T_convertStruct> {
    int rangeStart;
    int rangeEnd;
    int step;
    int offset;

    T_convertStruct() {
    }

    T_convertStruct(int rangeStart, int rangeEnd, int step, int offset) {
        this.rangeStart = rangeStart;
        this.rangeEnd = rangeEnd;
        this.step = step;
        this.offset = offset;
    }

    public T_convertStruct set(T_convertStruct o$) {
        rangeStart = o$.rangeStart;
        rangeEnd = o$.rangeEnd;
        step = o$.step;
        offset = o$.offset;
        return this;
    }

    T_convertStruct copy() {
        return new T_convertStruct().set(this);
    }

    public T_convertStruct zero() {
        return set(new T_convertStruct());
    }

    static T_convertStruct[] array(int n) {
        T_convertStruct[] a = new T_convertStruct[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_convertStruct();
        }
        return a;
    }
}
