// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_decomp_T implements Struct<T_decomp_T> {
    int a;
    int b;
    int c;

    T_decomp_T() {
    }

    T_decomp_T(int a, int b, int c) {
        this.a = a;
        this.b = b;
        this.c = c;
    }

    public T_decomp_T set(T_decomp_T o$) {
        a = o$.a;
        b = o$.b;
        c = o$.c;
        return this;
    }

    T_decomp_T copy() {
        return new T_decomp_T().set(this);
    }

    public T_decomp_T zero() {
        return set(new T_decomp_T());
    }

    static T_decomp_T[] array(int n) {
        T_decomp_T[] a = new T_decomp_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_decomp_T();
        }
        return a;
    }
}
