// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_do_set_option_value__out_T implements Struct<T_do_set_option_value__out_T> {
    BytePtr r__;
    BytePtr argp;

    public T_do_set_option_value__out_T set(T_do_set_option_value__out_T o$) {
        r__ = o$.r__;
        argp = o$.argp;
        return this;
    }

    T_do_set_option_value__out_T copy() {
        return new T_do_set_option_value__out_T().set(this);
    }

    public T_do_set_option_value__out_T zero() {
        return set(new T_do_set_option_value__out_T());
    }

    static T_do_set_option_value__out_T[] array(int n) {
        T_do_set_option_value__out_T[] a = new T_do_set_option_value__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_do_set_option_value__out_T();
        }
        return a;
    }
}
