// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_do_set_option__out_T implements Struct<T_do_set_option__out_T> {
    BytePtr r__;
    int did_show;

    @Override
    public T_do_set_option__out_T set(T_do_set_option__out_T o) {
        r__ = o.r__;
        did_show = o.did_show;
        return this;
    }

    T_do_set_option__out_T copy() {
        return new T_do_set_option__out_T().set(this);
    }

    @Override
    public T_do_set_option__out_T zero() {
        return set(new T_do_set_option__out_T());
    }

    static T_do_set_option__out_T[] array(int n) {
        T_do_set_option__out_T[] a = new T_do_set_option__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_do_set_option__out_T();
        }
        return a;
    }
}
