// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_estack_T implements Struct<T_estack_T> {
    long es_lnum;
    BytePtr es_name;
    int es_type;

    public T_estack_T set(T_estack_T o$) {
        es_lnum = o$.es_lnum;
        es_name = o$.es_name;
        es_type = o$.es_type;
        return this;
    }

    T_estack_T copy() {
        return new T_estack_T().set(this);
    }

    public T_estack_T zero() {
        return set(new T_estack_T());
    }

    static T_estack_T[] array(int n) {
        T_estack_T[] a = new T_estack_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_estack_T();
        }
        return a;
    }
}
