// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_execreg_line_continuation__out_T implements Struct<T_execreg_line_continuation__out_T> {
    BytePtr r__;
    long idx;

    public T_execreg_line_continuation__out_T set(T_execreg_line_continuation__out_T o$) {
        r__ = o$.r__;
        idx = o$.idx;
        return this;
    }

    T_execreg_line_continuation__out_T copy() {
        return new T_execreg_line_continuation__out_T().set(this);
    }

    public T_execreg_line_continuation__out_T zero() {
        return set(new T_execreg_line_continuation__out_T());
    }

    static T_execreg_line_continuation__out_T[] array(int n) {
        T_execreg_line_continuation__out_T[] a = new T_execreg_line_continuation__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_execreg_line_continuation__out_T();
        }
        return a;
    }
}
