// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_fillchar_status__out_T implements Struct<T_fillchar_status__out_T> {
    int r__;
    int attr;

    @Override
    public T_fillchar_status__out_T set(T_fillchar_status__out_T o) {
        r__ = o.r__;
        attr = o.attr;
        return this;
    }

    T_fillchar_status__out_T copy() {
        return new T_fillchar_status__out_T().set(this);
    }

    @Override
    public T_fillchar_status__out_T zero() {
        return set(new T_fillchar_status__out_T());
    }

    static T_fillchar_status__out_T[] array(int n) {
        T_fillchar_status__out_T[] a = new T_fillchar_status__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_fillchar_status__out_T();
        }
        return a;
    }
}
