// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_find_key_item__out_T implements Struct<T_find_key_item__out_T> {
    BytePtr r__;
    int itemlenp;

    @Override
    public T_find_key_item__out_T set(T_find_key_item__out_T o) {
        r__ = o.r__;
        itemlenp = o.itemlenp;
        return this;
    }

    T_find_key_item__out_T copy() {
        return new T_find_key_item__out_T().set(this);
    }

    @Override
    public T_find_key_item__out_T zero() {
        return set(new T_find_key_item__out_T());
    }

    static T_find_key_item__out_T[] array(int n) {
        T_find_key_item__out_T[] a = new T_find_key_item__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_find_key_item__out_T();
        }
        return a;
    }
}
