// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_find_special_key__out_T implements Struct<T_find_special_key__out_T> {
    int r__;
    int modp;

    public T_find_special_key__out_T set(T_find_special_key__out_T o$) {
        r__ = o$.r__;
        modp = o$.modp;
        return this;
    }

    T_find_special_key__out_T copy() {
        return new T_find_special_key__out_T().set(this);
    }

    public T_find_special_key__out_T zero() {
        return set(new T_find_special_key__out_T());
    }

    static T_find_special_key__out_T[] array(int n) {
        T_find_special_key__out_T[] a = new T_find_special_key__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_find_special_key__out_T();
        }
        return a;
    }
}
