// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_fill_chars_T implements Struct<T_fill_chars_T> {
    final int[] stl = new int[1];
    final int[] stlnc = new int[1];
    final int[] vert = new int[1];
    final int[] fold = new int[1];
    final int[] foldopen = new int[1];
    final int[] foldclosed = new int[1];
    final int[] foldsep = new int[1];
    final int[] foldinner = new int[1];
    final int[] diff = new int[1];
    final int[] eob = new int[1];
    final int[] lastline = new int[1];
    final int[] trunc = new int[1];
    final int[] truncrl = new int[1];

    public T_fill_chars_T set(T_fill_chars_T o$) {
        stl[0] = o$.stl[0];
        stlnc[0] = o$.stlnc[0];
        vert[0] = o$.vert[0];
        fold[0] = o$.fold[0];
        foldopen[0] = o$.foldopen[0];
        foldclosed[0] = o$.foldclosed[0];
        foldsep[0] = o$.foldsep[0];
        foldinner[0] = o$.foldinner[0];
        diff[0] = o$.diff[0];
        eob[0] = o$.eob[0];
        lastline[0] = o$.lastline[0];
        trunc[0] = o$.trunc[0];
        truncrl[0] = o$.truncrl[0];
        return this;
    }

    T_fill_chars_T copy() {
        return new T_fill_chars_T().set(this);
    }

    public T_fill_chars_T zero() {
        return set(new T_fill_chars_T());
    }

    static T_fill_chars_T[] array(int n) {
        T_fill_chars_T[] a = new T_fill_chars_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_fill_chars_T();
        }
        return a;
    }
}
