// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_frame_comp_pos__out_T implements Struct<T_frame_comp_pos__out_T> {
    int row;
    int col;

    @Override
    public T_frame_comp_pos__out_T set(T_frame_comp_pos__out_T o) {
        row = o.row;
        col = o.col;
        return this;
    }

    T_frame_comp_pos__out_T copy() {
        return new T_frame_comp_pos__out_T().set(this);
    }

    @Override
    public T_frame_comp_pos__out_T zero() {
        return set(new T_frame_comp_pos__out_T());
    }

    static T_frame_comp_pos__out_T[] array(int n) {
        T_frame_comp_pos__out_T[] a = new T_frame_comp_pos__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_frame_comp_pos__out_T();
        }
        return a;
    }
}
