// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_get_list_range__out_T implements Struct<T_get_list_range__out_T> {
    boolean r__;
    BytePtr str;
    int num1;
    int num2;

    public T_get_list_range__out_T set(T_get_list_range__out_T o$) {
        r__ = o$.r__;
        str = o$.str;
        num1 = o$.num1;
        num2 = o$.num2;
        return this;
    }

    T_get_list_range__out_T copy() {
        return new T_get_list_range__out_T().set(this);
    }

    public T_get_list_range__out_T zero() {
        return set(new T_get_list_range__out_T());
    }

    static T_get_list_range__out_T[] array(int n) {
        T_get_list_range__out_T[] a = new T_get_list_range__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_get_list_range__out_T();
        }
        return a;
    }
}
