// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_gotchars_state_T implements Struct<T_gotchars_state_T> {
    final byte[] buf = new byte[67];
    int prev_c;
    long buflen;
    int pending_special;
    int pending_mbyte;

    @Override
    public T_gotchars_state_T set(T_gotchars_state_T o) {
        System.arraycopy(o.buf, 0, buf, 0, 67);
        prev_c = o.prev_c;
        buflen = o.buflen;
        pending_special = o.pending_special;
        pending_mbyte = o.pending_mbyte;
        return this;
    }

    T_gotchars_state_T copy() {
        return new T_gotchars_state_T().set(this);
    }

    @Override
    public T_gotchars_state_T zero() {
        return set(new T_gotchars_state_T());
    }

    static T_gotchars_state_T[] array(int n) {
        T_gotchars_state_T[] a = new T_gotchars_state_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_gotchars_state_T();
        }
        return a;
    }
}
