// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_handle_csi__out_T implements Struct<T_handle_csi__out_T> {
    int r__;
    int slen;

    public T_handle_csi__out_T set(T_handle_csi__out_T o$) {
        r__ = o$.r__;
        slen = o$.slen;
        return this;
    }

    T_handle_csi__out_T copy() {
        return new T_handle_csi__out_T().set(this);
    }

    public T_handle_csi__out_T zero() {
        return set(new T_handle_csi__out_T());
    }

    static T_handle_csi__out_T[] array(int n) {
        T_handle_csi__out_T[] a = new T_handle_csi__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_handle_csi__out_T();
        }
        return a;
    }
}
