// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_hl_group_T implements Struct<T_hl_group_T> {
    BytePtr sg_name;
    BytePtr sg_name_u;
    boolean sg_cleared;
    int sg_term;
    BytePtr sg_start;
    BytePtr sg_stop;
    int sg_term_attr;
    int sg_cterm;
    boolean sg_cterm_bold;
    int sg_cterm_fg;
    int sg_cterm_bg;
    int sg_cterm_ul;
    int sg_cterm_attr;
    int sg_cterm_font;
    int sg_link;
    int sg_deflink;
    int sg_set;

    @Override
    public T_hl_group_T set(T_hl_group_T o) {
        sg_name = o.sg_name;
        sg_name_u = o.sg_name_u;
        sg_cleared = o.sg_cleared;
        sg_term = o.sg_term;
        sg_start = o.sg_start;
        sg_stop = o.sg_stop;
        sg_term_attr = o.sg_term_attr;
        sg_cterm = o.sg_cterm;
        sg_cterm_bold = o.sg_cterm_bold;
        sg_cterm_fg = o.sg_cterm_fg;
        sg_cterm_bg = o.sg_cterm_bg;
        sg_cterm_ul = o.sg_cterm_ul;
        sg_cterm_attr = o.sg_cterm_attr;
        sg_cterm_font = o.sg_cterm_font;
        sg_link = o.sg_link;
        sg_deflink = o.sg_deflink;
        sg_set = o.sg_set;
        return this;
    }

    T_hl_group_T copy() {
        return new T_hl_group_T().set(this);
    }

    @Override
    public T_hl_group_T zero() {
        return set(new T_hl_group_T());
    }

    static T_hl_group_T[] array(int n) {
        T_hl_group_T[] a = new T_hl_group_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_hl_group_T();
        }
        return a;
    }

    boolean eq(T_hl_group_T o) {
        if (!BytePtr.eq(sg_name, o.sg_name)) {
            return false;
        }
        if (!BytePtr.eq(sg_name_u, o.sg_name_u)) {
            return false;
        }
        if (sg_cleared != o.sg_cleared) {
            return false;
        }
        if (sg_term != o.sg_term) {
            return false;
        }
        if (!BytePtr.eq(sg_start, o.sg_start)) {
            return false;
        }
        if (!BytePtr.eq(sg_stop, o.sg_stop)) {
            return false;
        }
        if (sg_term_attr != o.sg_term_attr) {
            return false;
        }
        if (sg_cterm != o.sg_cterm) {
            return false;
        }
        if (sg_cterm_bold != o.sg_cterm_bold) {
            return false;
        }
        if (sg_cterm_fg != o.sg_cterm_fg) {
            return false;
        }
        if (sg_cterm_bg != o.sg_cterm_bg) {
            return false;
        }
        if (sg_cterm_ul != o.sg_cterm_ul) {
            return false;
        }
        if (sg_cterm_attr != o.sg_cterm_attr) {
            return false;
        }
        if (sg_cterm_font != o.sg_cterm_font) {
            return false;
        }
        if (sg_link != o.sg_link) {
            return false;
        }
        if (sg_deflink != o.sg_deflink) {
            return false;
        }
        if (sg_set != o.sg_set) {
            return false;
        }
        return true;
    }
}
