// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_hl_override_T implements Struct<T_hl_override_T> {
    int from;
    int to_;

    public T_hl_override_T set(T_hl_override_T o$) {
        from = o$.from;
        to_ = o$.to_;
        return this;
    }

    T_hl_override_T copy() {
        return new T_hl_override_T().set(this);
    }

    public T_hl_override_T zero() {
        return set(new T_hl_override_T());
    }

    static T_hl_override_T[] array(int n) {
        T_hl_override_T[] a = new T_hl_override_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_hl_override_T();
        }
        return a;
    }
}
