// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_incsearch_state_T implements Struct<T_incsearch_state_T> {
    final T_pos_T search_start = new T_pos_T();
    final T_pos_T save_cursor = new T_pos_T();
    final T_viewstate_T init_viewstate = new T_viewstate_T();
    final T_viewstate_T old_viewstate = new T_viewstate_T();
    final T_pos_T match_start = new T_pos_T();
    final T_pos_T match_end = new T_pos_T();
    boolean did_incsearch;
    boolean incsearch_postponed;
    int magic_overruled_save;

    @Override
    public T_incsearch_state_T set(T_incsearch_state_T o) {
        search_start.set(o.search_start);
        save_cursor.set(o.save_cursor);
        init_viewstate.set(o.init_viewstate);
        old_viewstate.set(o.old_viewstate);
        match_start.set(o.match_start);
        match_end.set(o.match_end);
        did_incsearch = o.did_incsearch;
        incsearch_postponed = o.incsearch_postponed;
        magic_overruled_save = o.magic_overruled_save;
        return this;
    }

    T_incsearch_state_T copy() {
        return new T_incsearch_state_T().set(this);
    }

    @Override
    public T_incsearch_state_T zero() {
        return set(new T_incsearch_state_T());
    }

    static T_incsearch_state_T[] array(int n) {
        T_incsearch_state_T[] a = new T_incsearch_state_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_incsearch_state_T();
        }
        return a;
    }
}
