// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_ins_bs__out_T implements Struct<T_ins_bs__out_T> {
    boolean r__;
    boolean inserted_space_p;

    @Override
    public T_ins_bs__out_T set(T_ins_bs__out_T o) {
        r__ = o.r__;
        inserted_space_p = o.inserted_space_p;
        return this;
    }

    T_ins_bs__out_T copy() {
        return new T_ins_bs__out_T().set(this);
    }

    @Override
    public T_ins_bs__out_T zero() {
        return set(new T_ins_bs__out_T());
    }

    static T_ins_bs__out_T[] array(int n) {
        T_ins_bs__out_T[] a = new T_ins_bs__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_ins_bs__out_T();
        }
        return a;
    }
}
