// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_keyvalue_T implements Struct<T_keyvalue_T> {
    int key;
    final T_string_T value = new T_string_T();

    T_keyvalue_T() {
    }

    T_keyvalue_T(int key, T_string_T value) {
        this.key = key;
        this.value.set(value);
    }

    @Override
    public T_keyvalue_T set(T_keyvalue_T o) {
        key = o.key;
        value.set(o.value);
        return this;
    }

    T_keyvalue_T copy() {
        return new T_keyvalue_T().set(this);
    }

    @Override
    public T_keyvalue_T zero() {
        return set(new T_keyvalue_T());
    }

    static T_keyvalue_T[] array(int n) {
        T_keyvalue_T[] a = new T_keyvalue_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_keyvalue_T();
        }
        return a;
    }
}
