// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_lcs_chars_T implements Struct<T_lcs_chars_T> {
    final int[] eol = new int[1];
    final int[] ext = new int[1];
    final int[] prec = new int[1];
    final int[] nbsp = new int[1];
    final int[] space = new int[1];
    int tab1;
    final int[] tab2 = new int[1];
    int tab3;
    final int[] trail = new int[1];
    final int[] lead = new int[1];
    int leadtab1;
    final int[] leadtab2 = new int[1];
    int leadtab3;
    IntPtr multispace;
    IntPtr leadmultispace;

    @Override
    public T_lcs_chars_T set(T_lcs_chars_T o) {
        eol[0] = o.eol[0];
        ext[0] = o.ext[0];
        prec[0] = o.prec[0];
        nbsp[0] = o.nbsp[0];
        space[0] = o.space[0];
        tab1 = o.tab1;
        tab2[0] = o.tab2[0];
        tab3 = o.tab3;
        trail[0] = o.trail[0];
        lead[0] = o.lead[0];
        leadtab1 = o.leadtab1;
        leadtab2[0] = o.leadtab2[0];
        leadtab3 = o.leadtab3;
        multispace = o.multispace;
        leadmultispace = o.leadmultispace;
        return this;
    }

    T_lcs_chars_T copy() {
        return new T_lcs_chars_T().set(this);
    }

    @Override
    public T_lcs_chars_T zero() {
        return set(new T_lcs_chars_T());
    }

    static T_lcs_chars_T[] array(int n) {
        T_lcs_chars_T[] a = new T_lcs_chars_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_lcs_chars_T();
        }
        return a;
    }
}
