// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_lineoff_T implements Struct<T_lineoff_T> {
    long lnum;
    int height;

    public T_lineoff_T set(T_lineoff_T o$) {
        lnum = o$.lnum;
        height = o$.height;
        return this;
    }

    T_lineoff_T copy() {
        return new T_lineoff_T().set(this);
    }

    public T_lineoff_T zero() {
        return set(new T_lineoff_T());
    }

    static T_lineoff_T[] array(int n) {
        T_lineoff_T[] a = new T_lineoff_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_lineoff_T();
        }
        return a;
    }
}
