// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_linefound_T implements Struct<T_linefound_T> {
    Ptr<T_regsearch_T> searches;
    Ptr<T_lpos_T> pos;
    int n;
    int next;

    public T_linefound_T set(T_linefound_T o$) {
        searches = o$.searches;
        pos = o$.pos;
        n = o$.n;
        next = o$.next;
        return this;
    }

    T_linefound_T copy() {
        return new T_linefound_T().set(this);
    }

    public T_linefound_T zero() {
        return set(new T_linefound_T());
    }

    static T_linefound_T[] array(int n) {
        T_linefound_T[] a = new T_linefound_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_linefound_T();
        }
        return a;
    }
}
