// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_line_count_info__out_T implements Struct<T_line_count_info__out_T> {
    long r__;
    long wc;
    long cc;

    @Override
    public T_line_count_info__out_T set(T_line_count_info__out_T o) {
        r__ = o.r__;
        wc = o.wc;
        cc = o.cc;
        return this;
    }

    T_line_count_info__out_T copy() {
        return new T_line_count_info__out_T().set(this);
    }

    @Override
    public T_line_count_info__out_T zero() {
        return set(new T_line_count_info__out_T());
    }

    static T_line_count_info__out_T[] array(int n) {
        T_line_count_info__out_T[] a = new T_line_count_info__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_line_count_info__out_T();
        }
        return a;
    }
}
