// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_llpos_T implements Struct<T_llpos_T> {
    long lnum;
    int col;
    int len;

    public T_llpos_T set(T_llpos_T o$) {
        lnum = o$.lnum;
        col = o$.col;
        len = o$.len;
        return this;
    }

    T_llpos_T copy() {
        return new T_llpos_T().set(this);
    }

    public T_llpos_T zero() {
        return set(new T_llpos_T());
    }

    static T_llpos_T[] array(int n) {
        T_llpos_T[] a = new T_llpos_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_llpos_T();
        }
        return a;
    }
}
