// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_lpos_T implements Struct<T_lpos_T> {
    long lnum;
    int col;

    public T_lpos_T set(T_lpos_T o$) {
        lnum = o$.lnum;
        col = o$.col;
        return this;
    }

    T_lpos_T copy() {
        return new T_lpos_T().set(this);
    }

    public T_lpos_T zero() {
        return set(new T_lpos_T());
    }

    static T_lpos_T[] array(int n) {
        T_lpos_T[] a = new T_lpos_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_lpos_T();
        }
        return a;
    }
}
