// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_may_add_char_to_search__out_T implements Struct<T_may_add_char_to_search__out_T> {
    boolean r__;
    int c;

    public T_may_add_char_to_search__out_T set(T_may_add_char_to_search__out_T o$) {
        r__ = o$.r__;
        c = o$.c;
        return this;
    }

    T_may_add_char_to_search__out_T copy() {
        return new T_may_add_char_to_search__out_T().set(this);
    }

    public T_may_add_char_to_search__out_T zero() {
        return set(new T_may_add_char_to_search__out_T());
    }

    static T_may_add_char_to_search__out_T[] array(int n) {
        T_may_add_char_to_search__out_T[] a = new T_may_add_char_to_search__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_may_add_char_to_search__out_T();
        }
        return a;
    }
}
