// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_match_T implements Struct<T_match_T> {
    final T_regmmatch_T rm = new T_regmmatch_T();
    S_file_buffer buf;
    long lnum;
    int attr;
    int attr_cur;
    long first_lnum;
    int startcol;
    int endcol;
    byte is_addpos;
    byte has_cursor;

    @Override
    public T_match_T set(T_match_T o) {
        rm.set(o.rm);
        buf = o.buf;
        lnum = o.lnum;
        attr = o.attr;
        attr_cur = o.attr_cur;
        first_lnum = o.first_lnum;
        startcol = o.startcol;
        endcol = o.endcol;
        is_addpos = o.is_addpos;
        has_cursor = o.has_cursor;
        return this;
    }

    T_match_T copy() {
        return new T_match_T().set(this);
    }

    @Override
    public T_match_T zero() {
        return set(new T_match_T());
    }

    static T_match_T[] array(int n) {
        T_match_T[] a = new T_match_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_match_T();
        }
        return a;
    }
}
