// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_match_with_backref__out_T implements Struct<T_match_with_backref__out_T> {
    int r__;
    int bytelen;

    @Override
    public T_match_with_backref__out_T set(T_match_with_backref__out_T o) {
        r__ = o.r__;
        bytelen = o.bytelen;
        return this;
    }

    T_match_with_backref__out_T copy() {
        return new T_match_with_backref__out_T().set(this);
    }

    @Override
    public T_match_with_backref__out_T zero() {
        return set(new T_match_with_backref__out_T());
    }

    static T_match_with_backref__out_T[] array(int n) {
        T_match_with_backref__out_T[] a = new T_match_with_backref__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_match_with_backref__out_T();
        }
        return a;
    }
}
