// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_mb_copy_char__out_T implements Struct<T_mb_copy_char__out_T> {
    BytePtr fp;
    BytePtr tp;

    public T_mb_copy_char__out_T set(T_mb_copy_char__out_T o$) {
        fp = o$.fp;
        tp = o$.tp;
        return this;
    }

    T_mb_copy_char__out_T copy() {
        return new T_mb_copy_char__out_T().set(this);
    }

    public T_mb_copy_char__out_T zero() {
        return set(new T_mb_copy_char__out_T());
    }

    static T_mb_copy_char__out_T[] array(int n) {
        T_mb_copy_char__out_T[] a = new T_mb_copy_char__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_mb_copy_char__out_T();
        }
        return a;
    }
}
