// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_mparm_T implements Struct<T_mparm_T> {
    int argc;
    Ptr<BytePtr> argv;
    int n_commands;
    final BytePtr[] commands = new BytePtr[10];
    boolean want_full_screen;

    public T_mparm_T set(T_mparm_T o$) {
        argc = o$.argc;
        argv = o$.argv;
        n_commands = o$.n_commands;
        System.arraycopy(o$.commands, 0, commands, 0, 10);
        want_full_screen = o$.want_full_screen;
        return this;
    }

    T_mparm_T copy() {
        return new T_mparm_T().set(this);
    }

    public T_mparm_T zero() {
        return set(new T_mparm_T());
    }

    static T_mparm_T[] array(int n) {
        T_mparm_T[] a = new T_mparm_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_mparm_T();
        }
        return a;
    }
}
