// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_normal_cmd_get_count__out_T implements Struct<T_normal_cmd_get_count__out_T> {
    int r__;
    int ctrl_w;
    int need_flushbuf;

    @Override
    public T_normal_cmd_get_count__out_T set(T_normal_cmd_get_count__out_T o) {
        r__ = o.r__;
        ctrl_w = o.ctrl_w;
        need_flushbuf = o.need_flushbuf;
        return this;
    }

    T_normal_cmd_get_count__out_T copy() {
        return new T_normal_cmd_get_count__out_T().set(this);
    }

    @Override
    public T_normal_cmd_get_count__out_T zero() {
        return set(new T_normal_cmd_get_count__out_T());
    }

    static T_normal_cmd_get_count__out_T[] array(int n) {
        T_normal_cmd_get_count__out_T[] a = new T_normal_cmd_get_count__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_normal_cmd_get_count__out_T();
        }
        return a;
    }
}
