// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_one_letter_cmd__out_T implements Struct<T_one_letter_cmd__out_T> {
    boolean r__;
    int idx;

    @Override
    public T_one_letter_cmd__out_T set(T_one_letter_cmd__out_T o) {
        r__ = o.r__;
        idx = o.idx;
        return this;
    }

    T_one_letter_cmd__out_T copy() {
        return new T_one_letter_cmd__out_T().set(this);
    }

    @Override
    public T_one_letter_cmd__out_T zero() {
        return set(new T_one_letter_cmd__out_T());
    }

    static T_one_letter_cmd__out_T[] array(int n) {
        T_one_letter_cmd__out_T[] a = new T_one_letter_cmd__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_one_letter_cmd__out_T();
        }
        return a;
    }
}
