// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_optvar_T implements Struct<T_optvar_T> {
    IntPtr ov_int;
    LongPtr ov_long;
    Ptr<BytePtr> ov_str;
    int ov_win;

    T_optvar_T() {
    }

    T_optvar_T(IntPtr ov_int, LongPtr ov_long, Ptr<BytePtr> ov_str, int ov_win) {
        this.ov_int = ov_int;
        this.ov_long = ov_long;
        this.ov_str = ov_str;
        this.ov_win = ov_win;
    }

    @Override
    public T_optvar_T set(T_optvar_T o) {
        ov_int = o.ov_int;
        ov_long = o.ov_long;
        ov_str = o.ov_str;
        ov_win = o.ov_win;
        return this;
    }

    T_optvar_T copy() {
        return new T_optvar_T().set(this);
    }

    @Override
    public T_optvar_T zero() {
        return set(new T_optvar_T());
    }

    static T_optvar_T[] array(int n) {
        T_optvar_T[] a = new T_optvar_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_optvar_T();
        }
        return a;
    }
}
