// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_optset_T implements Struct<T_optset_T> {
    final T_optvar_T os_varp = new T_optvar_T();
    int os_idx;
    int os_flags;
    int os_op;
    final A_4 os_oldval = new A_4();
    final A_4 os_newval = new A_4();
    int os_value_checked;
    boolean os_restore_chartab;
    BytePtr os_errbuf;
    long os_errbuflen;

    public T_optset_T set(T_optset_T o$) {
        os_varp.set(o$.os_varp);
        os_idx = o$.os_idx;
        os_flags = o$.os_flags;
        os_op = o$.os_op;
        os_oldval.set(o$.os_oldval);
        os_newval.set(o$.os_newval);
        os_value_checked = o$.os_value_checked;
        os_restore_chartab = o$.os_restore_chartab;
        os_errbuf = o$.os_errbuf;
        os_errbuflen = o$.os_errbuflen;
        return this;
    }

    T_optset_T copy() {
        return new T_optset_T().set(this);
    }

    public T_optset_T zero() {
        return set(new T_optset_T());
    }

    static T_optset_T[] array(int n) {
        T_optset_T[] a = new T_optset_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_optset_T();
        }
        return a;
    }
}
