// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_opt_backspace_nr2str__out_T implements Struct<T_opt_backspace_nr2str__out_T> {
    BytePtr origval_p;
    BytePtr origval_l_p;
    BytePtr origval_g_p;
    BytePtr oldval_p;

    @Override
    public T_opt_backspace_nr2str__out_T set(T_opt_backspace_nr2str__out_T o) {
        origval_p = o.origval_p;
        origval_l_p = o.origval_l_p;
        origval_g_p = o.origval_g_p;
        oldval_p = o.oldval_p;
        return this;
    }

    T_opt_backspace_nr2str__out_T copy() {
        return new T_opt_backspace_nr2str__out_T().set(this);
    }

    @Override
    public T_opt_backspace_nr2str__out_T zero() {
        return set(new T_opt_backspace_nr2str__out_T());
    }

    static T_opt_backspace_nr2str__out_T[] array(int n) {
        T_opt_backspace_nr2str__out_T[] a = new T_opt_backspace_nr2str__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_opt_backspace_nr2str__out_T();
        }
        return a;
    }
}
