// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_optexpand_T implements Struct<T_optexpand_T> {
    BytePtr oe_varp;
    BytePtr oe_opt_value;
    int oe_append;
    int oe_include_orig_val;
    T_regmatch_T oe_regmatch;
    S_expand oe_xp;
    BytePtr oe_set_arg;

    public T_optexpand_T set(T_optexpand_T o$) {
        oe_varp = o$.oe_varp;
        oe_opt_value = o$.oe_opt_value;
        oe_append = o$.oe_append;
        oe_include_orig_val = o$.oe_include_orig_val;
        oe_regmatch = o$.oe_regmatch;
        oe_xp = o$.oe_xp;
        oe_set_arg = o$.oe_set_arg;
        return this;
    }

    T_optexpand_T copy() {
        return new T_optexpand_T().set(this);
    }

    public T_optexpand_T zero() {
        return set(new T_optexpand_T());
    }

    static T_optexpand_T[] array(int n) {
        T_optexpand_T[] a = new T_optexpand_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_optexpand_T();
        }
        return a;
    }
}
