// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_oscstate_T implements Struct<T_oscstate_T> {
    boolean processing;
    byte start_char;
    final S_growarray buf = new S_growarray();
    long start_tv;

    public T_oscstate_T set(T_oscstate_T o$) {
        processing = o$.processing;
        start_char = o$.start_char;
        buf.set(o$.buf);
        start_tv = o$.start_tv;
        return this;
    }

    T_oscstate_T copy() {
        return new T_oscstate_T().set(this);
    }

    public T_oscstate_T zero() {
        return set(new T_oscstate_T());
    }

    static T_oscstate_T[] array(int n) {
        T_oscstate_T[] a = new T_oscstate_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_oscstate_T();
        }
        return a;
    }
}
