// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_parse_winhighlight__out_T implements Struct<T_parse_winhighlight__out_T> {
    Ptr<T_hl_override_T> r__;
    int len;
    BytePtr errmsg;

    public T_parse_winhighlight__out_T set(T_parse_winhighlight__out_T o$) {
        r__ = o$.r__;
        len = o$.len;
        errmsg = o$.errmsg;
        return this;
    }

    T_parse_winhighlight__out_T copy() {
        return new T_parse_winhighlight__out_T().set(this);
    }

    public T_parse_winhighlight__out_T zero() {
        return set(new T_parse_winhighlight__out_T());
    }

    static T_parse_winhighlight__out_T[] array(int n) {
        T_parse_winhighlight__out_T[] a = new T_parse_winhighlight__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_parse_winhighlight__out_T();
        }
        return a;
    }
}
