// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_pos_T implements Struct<T_pos_T> {
    long lnum;
    int col;
    int coladd;

    @Override
    public T_pos_T set(T_pos_T o) {
        lnum = o.lnum;
        col = o.col;
        coladd = o.coladd;
        return this;
    }

    T_pos_T copy() {
        return new T_pos_T().set(this);
    }

    @Override
    public T_pos_T zero() {
        return set(new T_pos_T());
    }

    static T_pos_T[] array(int n) {
        T_pos_T[] a = new T_pos_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_pos_T();
        }
        return a;
    }
}
