// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_prepare_search_hl_line__out_T implements Struct<T_prepare_search_hl_line__out_T> {
    boolean r__;
    BytePtr line;
    int search_attr;

    @Override
    public T_prepare_search_hl_line__out_T set(T_prepare_search_hl_line__out_T o) {
        r__ = o.r__;
        line = o.line;
        search_attr = o.search_attr;
        return this;
    }

    T_prepare_search_hl_line__out_T copy() {
        return new T_prepare_search_hl_line__out_T().set(this);
    }

    @Override
    public T_prepare_search_hl_line__out_T zero() {
        return set(new T_prepare_search_hl_line__out_T());
    }

    static T_prepare_search_hl_line__out_T[] array(int n) {
        T_prepare_search_hl_line__out_T[] a = new T_prepare_search_hl_line__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_prepare_search_hl_line__out_T();
        }
        return a;
    }
}
