// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_redo_VIsual_T implements Struct<T_redo_VIsual_T> {
    int rv_mode;
    long rv_line_count;
    int rv_vcol;
    long rv_count;
    int rv_arg;

    public T_redo_VIsual_T set(T_redo_VIsual_T o$) {
        rv_mode = o$.rv_mode;
        rv_line_count = o$.rv_line_count;
        rv_vcol = o$.rv_vcol;
        rv_count = o$.rv_count;
        rv_arg = o$.rv_arg;
        return this;
    }

    T_redo_VIsual_T copy() {
        return new T_redo_VIsual_T().set(this);
    }

    public T_redo_VIsual_T zero() {
        return set(new T_redo_VIsual_T());
    }

    static T_redo_VIsual_T[] array(int n) {
        T_redo_VIsual_T[] a = new T_redo_VIsual_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_redo_VIsual_T();
        }
        return a;
    }
}
