// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_regconcat__out_T implements Struct<T_regconcat__out_T> {
    BytePtr r__;
    int flagp;

    public T_regconcat__out_T set(T_regconcat__out_T o$) {
        r__ = o$.r__;
        flagp = o$.flagp;
        return this;
    }

    T_regconcat__out_T copy() {
        return new T_regconcat__out_T().set(this);
    }

    public T_regconcat__out_T zero() {
        return set(new T_regconcat__out_T());
    }

    static T_regconcat__out_T[] array(int n) {
        T_regconcat__out_T[] a = new T_regconcat__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_regconcat__out_T();
        }
        return a;
    }
}
