// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_regmmatch_T implements Struct<T_regmmatch_T> {
    S_regprog regprog;
    final T_lpos_T[] startpos = T_lpos_T.array(10);
    final T_lpos_T[] endpos = T_lpos_T.array(10);
    int rmm_matchcol;
    int rmm_ic;
    int rmm_maxcol;

    public T_regmmatch_T set(T_regmmatch_T o$) {
        regprog = o$.regprog;
        for (int k$0 = 0; k$0 < 10; k$0++) {
            startpos[k$0].set(o$.startpos[k$0]);
        }
        for (int k$0 = 0; k$0 < 10; k$0++) {
            endpos[k$0].set(o$.endpos[k$0]);
        }
        rmm_matchcol = o$.rmm_matchcol;
        rmm_ic = o$.rmm_ic;
        rmm_maxcol = o$.rmm_maxcol;
        return this;
    }

    T_regmmatch_T copy() {
        return new T_regmmatch_T().set(this);
    }

    public T_regmmatch_T zero() {
        return set(new T_regmmatch_T());
    }

    static T_regmmatch_T[] array(int n) {
        T_regmmatch_T[] a = new T_regmmatch_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_regmmatch_T();
        }
        return a;
    }
}
