// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_regsave_T implements Struct<T_regsave_T> {
    final A_5 rs_u = new A_5();
    int rs_len;

    public T_regsave_T set(T_regsave_T o$) {
        rs_u.set(o$.rs_u);
        rs_len = o$.rs_len;
        return this;
    }

    T_regsave_T copy() {
        return new T_regsave_T().set(this);
    }

    public T_regsave_T zero() {
        return set(new T_regsave_T());
    }

    static T_regsave_T[] array(int n) {
        T_regsave_T[] a = new T_regsave_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_regsave_T();
        }
        return a;
    }
}
