// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_regmatch_T implements Struct<T_regmatch_T> {
    S_regprog regprog;
    final BytePtr[] startp = new BytePtr[10];
    final BytePtr[] endp = new BytePtr[10];
    int rm_matchcol;
    boolean rm_ic;

    public T_regmatch_T set(T_regmatch_T o$) {
        regprog = o$.regprog;
        System.arraycopy(o$.startp, 0, startp, 0, 10);
        System.arraycopy(o$.endp, 0, endp, 0, 10);
        rm_matchcol = o$.rm_matchcol;
        rm_ic = o$.rm_ic;
        return this;
    }

    T_regmatch_T copy() {
        return new T_regmatch_T().set(this);
    }

    public T_regmatch_T zero() {
        return set(new T_regmatch_T());
    }

    static T_regmatch_T[] array(int n) {
        T_regmatch_T[] a = new T_regmatch_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_regmatch_T();
        }
        return a;
    }
}
