// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_regsearch_T implements Struct<T_regsearch_T> {
    int col;
    long nmatch;
    int matchcol;
    int nsub;
    int pos;

    @Override
    public T_regsearch_T set(T_regsearch_T o) {
        col = o.col;
        nmatch = o.nmatch;
        matchcol = o.matchcol;
        nsub = o.nsub;
        pos = o.pos;
        return this;
    }

    T_regsearch_T copy() {
        return new T_regsearch_T().set(this);
    }

    @Override
    public T_regsearch_T zero() {
        return set(new T_regsearch_T());
    }

    static T_regsearch_T[] array(int n) {
        T_regsearch_T[] a = new T_regsearch_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_regsearch_T();
        }
        return a;
    }
}
