// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_regexec_T implements Struct<T_regexec_T> {
    T_regmatch_T reg_match;
    T_regmmatch_T reg_mmatch;
    Ptr<BytePtr> reg_startp;
    Ptr<BytePtr> reg_endp;
    Ptr<T_lpos_T> reg_startpos;
    Ptr<T_lpos_T> reg_endpos;
    S_window_S reg_win;
    S_file_buffer reg_buf;
    long reg_firstlnum;
    long reg_maxline;
    boolean reg_line_lbr;
    long lnum;
    BytePtr line;
    BytePtr input;
    int need_clear_subexpr;
    int reg_ic;
    boolean reg_icombine;
    int reg_maxcol;

    public T_regexec_T set(T_regexec_T o$) {
        reg_match = o$.reg_match;
        reg_mmatch = o$.reg_mmatch;
        reg_startp = o$.reg_startp;
        reg_endp = o$.reg_endp;
        reg_startpos = o$.reg_startpos;
        reg_endpos = o$.reg_endpos;
        reg_win = o$.reg_win;
        reg_buf = o$.reg_buf;
        reg_firstlnum = o$.reg_firstlnum;
        reg_maxline = o$.reg_maxline;
        reg_line_lbr = o$.reg_line_lbr;
        lnum = o$.lnum;
        line = o$.line;
        input = o$.input;
        need_clear_subexpr = o$.need_clear_subexpr;
        reg_ic = o$.reg_ic;
        reg_icombine = o$.reg_icombine;
        reg_maxcol = o$.reg_maxcol;
        return this;
    }

    T_regexec_T copy() {
        return new T_regexec_T().set(this);
    }

    public T_regexec_T zero() {
        return set(new T_regexec_T());
    }

    static T_regexec_T[] array(int n) {
        T_regexec_T[] a = new T_regexec_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_regexec_T();
        }
        return a;
    }
}
