// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_save_se_T implements Struct<T_save_se_T> {
    final A_5 se_u = new A_5();

    public T_save_se_T set(T_save_se_T o$) {
        se_u.set(o$.se_u);
        return this;
    }

    T_save_se_T copy() {
        return new T_save_se_T().set(this);
    }

    public T_save_se_T zero() {
        return set(new T_save_se_T());
    }

    static T_save_se_T[] array(int n) {
        T_save_se_T[] a = new T_save_se_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_save_se_T();
        }
        return a;
    }
}
