// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_save_state_T implements Struct<T_save_state_T> {
    int save_msg_scroll;
    int save_restart_edit;
    int save_msg_didout;
    int save_State;
    int save_insertmode;
    int save_finish_op;
    int save_opcount;
    int save_reg_executing;
    int save_pending_end_reg_executing;
    int save_script_version;
    final T_tasave_T tabuf = new T_tasave_T();

    public T_save_state_T set(T_save_state_T o$) {
        save_msg_scroll = o$.save_msg_scroll;
        save_restart_edit = o$.save_restart_edit;
        save_msg_didout = o$.save_msg_didout;
        save_State = o$.save_State;
        save_insertmode = o$.save_insertmode;
        save_finish_op = o$.save_finish_op;
        save_opcount = o$.save_opcount;
        save_reg_executing = o$.save_reg_executing;
        save_pending_end_reg_executing = o$.save_pending_end_reg_executing;
        save_script_version = o$.save_script_version;
        tabuf.set(o$.tabuf);
        return this;
    }

    T_save_state_T copy() {
        return new T_save_state_T().set(this);
    }

    public T_save_state_T zero() {
        return set(new T_save_state_T());
    }

    static T_save_state_T[] array(int n) {
        T_save_state_T[] a = new T_save_state_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_save_state_T();
        }
        return a;
    }
}
