// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_sctx_T implements Struct<T_sctx_T> {
    int sc_version;

    @Override
    public T_sctx_T set(T_sctx_T o) {
        sc_version = o.sc_version;
        return this;
    }

    T_sctx_T copy() {
        return new T_sctx_T().set(this);
    }

    @Override
    public T_sctx_T zero() {
        return set(new T_sctx_T());
    }

    static T_sctx_T[] array(int n) {
        T_sctx_T[] a = new T_sctx_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_sctx_T();
        }
        return a;
    }
}
