// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_searchit_arg_T implements Struct<T_searchit_arg_T> {
    long sa_stop_lnum;
    boolean sa_wrapped;

    @Override
    public T_searchit_arg_T set(T_searchit_arg_T o) {
        sa_stop_lnum = o.sa_stop_lnum;
        sa_wrapped = o.sa_wrapped;
        return this;
    }

    T_searchit_arg_T copy() {
        return new T_searchit_arg_T().set(this);
    }

    @Override
    public T_searchit_arg_T zero() {
        return set(new T_searchit_arg_T());
    }

    static T_searchit_arg_T[] array(int n) {
        T_searchit_arg_T[] a = new T_searchit_arg_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_searchit_arg_T();
        }
        return a;
    }
}
