// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_stropt_get_newval__out_T implements Struct<T_stropt_get_newval__out_T> {
    BytePtr r__;
    BytePtr argp;
    BytePtr origval_arg;
    BytePtr origval_l_arg;
    BytePtr origval_g_arg;
    BytePtr oldval_arg;
    int op_arg;

    @Override
    public T_stropt_get_newval__out_T set(T_stropt_get_newval__out_T o) {
        r__ = o.r__;
        argp = o.argp;
        origval_arg = o.origval_arg;
        origval_l_arg = o.origval_l_arg;
        origval_g_arg = o.origval_g_arg;
        oldval_arg = o.oldval_arg;
        op_arg = o.op_arg;
        return this;
    }

    T_stropt_get_newval__out_T copy() {
        return new T_stropt_get_newval__out_T().set(this);
    }

    @Override
    public T_stropt_get_newval__out_T zero() {
        return set(new T_stropt_get_newval__out_T());
    }

    static T_stropt_get_newval__out_T[] array(int n) {
        T_stropt_get_newval__out_T[] a = new T_stropt_get_newval__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_stropt_get_newval__out_T();
        }
        return a;
    }
}
