// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_store_sb_text__out_T implements Struct<T_store_sb_text__out_T> {
    BytePtr sb_str;
    int sb_col;

    @Override
    public T_store_sb_text__out_T set(T_store_sb_text__out_T o) {
        sb_str = o.sb_str;
        sb_col = o.sb_col;
        return this;
    }

    T_store_sb_text__out_T copy() {
        return new T_store_sb_text__out_T().set(this);
    }

    @Override
    public T_store_sb_text__out_T zero() {
        return set(new T_store_sb_text__out_T());
    }

    static T_store_sb_text__out_T[] array(int n) {
        T_store_sb_text__out_T[] a = new T_store_sb_text__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_store_sb_text__out_T();
        }
        return a;
    }
}
