// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_string_T implements Struct<T_string_T> {
    final BytePtr[] string = new BytePtr[1];
    long length;

    T_string_T() {
    }

    T_string_T(BytePtr string, long length) {
        this.string[0] = string;
        this.length = length;
    }

    @Override
    public T_string_T set(T_string_T o) {
        string[0] = o.string[0];
        length = o.length;
        return this;
    }

    T_string_T copy() {
        return new T_string_T().set(this);
    }

    @Override
    public T_string_T zero() {
        return set(new T_string_T());
    }

    static T_string_T[] array(int n) {
        T_string_T[] a = new T_string_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_string_T();
        }
        return a;
    }
}
