// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_subflags_T implements Struct<T_subflags_T> {
    int do_all;
    int do_ask;
    int do_count;
    int do_error;
    int do_print;
    int do_list;
    int do_number;
    int do_ic;

    @Override
    public T_subflags_T set(T_subflags_T o) {
        do_all = o.do_all;
        do_ask = o.do_ask;
        do_count = o.do_count;
        do_error = o.do_error;
        do_print = o.do_print;
        do_list = o.do_list;
        do_number = o.do_number;
        do_ic = o.do_ic;
        return this;
    }

    T_subflags_T copy() {
        return new T_subflags_T().set(this);
    }

    @Override
    public T_subflags_T zero() {
        return set(new T_subflags_T());
    }

    static T_subflags_T[] array(int n) {
        T_subflags_T[] a = new T_subflags_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_subflags_T();
        }
        return a;
    }
}
