// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_tasave_T implements Struct<T_tasave_T> {
    final T_typebuf_T save_typebuf = new T_typebuf_T();
    boolean typebuf_valid;
    int old_char;
    int old_mod_mask;
    final S_buffheader save_readbuf1 = new S_buffheader();
    final S_buffheader save_readbuf2 = new S_buffheader();
    S_growarray save_inputbuf;

    @Override
    public T_tasave_T set(T_tasave_T o) {
        save_typebuf.set(o.save_typebuf);
        typebuf_valid = o.typebuf_valid;
        old_char = o.old_char;
        old_mod_mask = o.old_mod_mask;
        save_readbuf1.set(o.save_readbuf1);
        save_readbuf2.set(o.save_readbuf2);
        save_inputbuf = o.save_inputbuf;
        return this;
    }

    T_tasave_T copy() {
        return new T_tasave_T().set(this);
    }

    @Override
    public T_tasave_T zero() {
        return set(new T_tasave_T());
    }

    static T_tasave_T[] array(int n) {
        T_tasave_T[] a = new T_tasave_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_tasave_T();
        }
        return a;
    }
}
