// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_tcap_entry_T implements Struct<T_tcap_entry_T> {
    int bt_entry;
    BytePtr bt_string;

    T_tcap_entry_T() {
    }

    T_tcap_entry_T(int bt_entry, BytePtr bt_string) {
        this.bt_entry = bt_entry;
        this.bt_string = bt_string;
    }

    public T_tcap_entry_T set(T_tcap_entry_T o$) {
        bt_entry = o$.bt_entry;
        bt_string = o$.bt_string;
        return this;
    }

    T_tcap_entry_T copy() {
        return new T_tcap_entry_T().set(this);
    }

    public T_tcap_entry_T zero() {
        return set(new T_tcap_entry_T());
    }

    static T_tcap_entry_T[] array(int n) {
        T_tcap_entry_T[] a = new T_tcap_entry_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_tcap_entry_T();
        }
        return a;
    }
}
