// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_termrequest_T implements Struct<T_termrequest_T> {
    int tr_progress;
    long tr_start;

    public T_termrequest_T set(T_termrequest_T o$) {
        tr_progress = o$.tr_progress;
        tr_start = o$.tr_start;
        return this;
    }

    T_termrequest_T copy() {
        return new T_termrequest_T().set(this);
    }

    public T_termrequest_T zero() {
        return set(new T_termrequest_T());
    }

    static T_termrequest_T[] array(int n) {
        T_termrequest_T[] a = new T_termrequest_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_termrequest_T();
        }
        return a;
    }
}
