// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_termprop_T implements Struct<T_termprop_T> {
    BytePtr tpr_name;
    boolean tpr_set_by_termresponse;
    int tpr_status;

    public T_termprop_T set(T_termprop_T o$) {
        tpr_name = o$.tpr_name;
        tpr_set_by_termresponse = o$.tpr_set_by_termresponse;
        tpr_status = o$.tpr_status;
        return this;
    }

    T_termprop_T copy() {
        return new T_termprop_T().set(this);
    }

    public T_termprop_T zero() {
        return set(new T_termprop_T());
    }

    static T_termprop_T[] array(int n) {
        T_termprop_T[] a = new T_termprop_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_termprop_T();
        }
        return a;
    }
}
