// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_ttyinfo_T implements Struct<T_ttyinfo_T> {
    int backspace;
    int enter;
    int interrupt;
    boolean nl_does_cr;

    public T_ttyinfo_T set(T_ttyinfo_T o$) {
        backspace = o$.backspace;
        enter = o$.enter;
        interrupt = o$.interrupt;
        nl_does_cr = o$.nl_does_cr;
        return this;
    }

    T_ttyinfo_T copy() {
        return new T_ttyinfo_T().set(this);
    }

    public T_ttyinfo_T zero() {
        return set(new T_ttyinfo_T());
    }

    static T_ttyinfo_T[] array(int n) {
        T_ttyinfo_T[] a = new T_ttyinfo_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_ttyinfo_T();
        }
        return a;
    }
}
