// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_typebuf_T implements Struct<T_typebuf_T> {
    BytePtr tb_buf;
    BytePtr tb_noremap;
    int tb_buflen;
    int tb_off;
    int tb_len;
    int tb_maplen;
    int tb_silent;
    int tb_no_abbr_cnt;
    int tb_change_cnt;

    public T_typebuf_T set(T_typebuf_T o$) {
        tb_buf = o$.tb_buf;
        tb_noremap = o$.tb_noremap;
        tb_buflen = o$.tb_buflen;
        tb_off = o$.tb_off;
        tb_len = o$.tb_len;
        tb_maplen = o$.tb_maplen;
        tb_silent = o$.tb_silent;
        tb_no_abbr_cnt = o$.tb_no_abbr_cnt;
        tb_change_cnt = o$.tb_change_cnt;
        return this;
    }

    T_typebuf_T copy() {
        return new T_typebuf_T().set(this);
    }

    public T_typebuf_T zero() {
        return set(new T_typebuf_T());
    }

    static T_typebuf_T[] array(int n) {
        T_typebuf_T[] a = new T_typebuf_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_typebuf_T();
        }
        return a;
    }
}
