// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_undoline_T implements Struct<T_undoline_T> {
    BytePtr ul_line;
    long ul_len;
    int ul_textlen;

    public T_undoline_T set(T_undoline_T o$) {
        ul_line = o$.ul_line;
        ul_len = o$.ul_len;
        ul_textlen = o$.ul_textlen;
        return this;
    }

    T_undoline_T copy() {
        return new T_undoline_T().set(this);
    }

    public T_undoline_T zero() {
        return set(new T_undoline_T());
    }

    static T_undoline_T[] array(int n) {
        T_undoline_T[] a = new T_undoline_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_undoline_T();
        }
        return a;
    }
}
