// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_update_search_hl__out_T implements Struct<T_update_search_hl__out_T> {
    int r__;
    BytePtr line;
    boolean on_last_col;

    @Override
    public T_update_search_hl__out_T set(T_update_search_hl__out_T o) {
        r__ = o.r__;
        line = o.line;
        on_last_col = o.on_last_col;
        return this;
    }

    T_update_search_hl__out_T copy() {
        return new T_update_search_hl__out_T().set(this);
    }

    @Override
    public T_update_search_hl__out_T zero() {
        return set(new T_update_search_hl__out_T());
    }

    static T_update_search_hl__out_T[] array(int n) {
        T_update_search_hl__out_T[] a = new T_update_search_hl__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_update_search_hl__out_T();
        }
        return a;
    }
}
