// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_viewstate_T implements Struct<T_viewstate_T> {
    int vs_curswant;
    int vs_leftcol;
    int vs_skipcol;
    long vs_topline;
    long vs_botline;
    long vs_empty_rows;

    @Override
    public T_viewstate_T set(T_viewstate_T o) {
        vs_curswant = o.vs_curswant;
        vs_leftcol = o.vs_leftcol;
        vs_skipcol = o.vs_skipcol;
        vs_topline = o.vs_topline;
        vs_botline = o.vs_botline;
        vs_empty_rows = o.vs_empty_rows;
        return this;
    }

    T_viewstate_T copy() {
        return new T_viewstate_T().set(this);
    }

    @Override
    public T_viewstate_T zero() {
        return set(new T_viewstate_T());
    }

    static T_viewstate_T[] array(int n) {
        T_viewstate_T[] a = new T_viewstate_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_viewstate_T();
        }
        return a;
    }
}
