// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_vim_append_digit_long__out_T implements Struct<T_vim_append_digit_long__out_T> {
    boolean r__;
    long value;

    public T_vim_append_digit_long__out_T set(T_vim_append_digit_long__out_T o$) {
        r__ = o$.r__;
        value = o$.value;
        return this;
    }

    T_vim_append_digit_long__out_T copy() {
        return new T_vim_append_digit_long__out_T().set(this);
    }

    public T_vim_append_digit_long__out_T zero() {
        return set(new T_vim_append_digit_long__out_T());
    }

    static T_vim_append_digit_long__out_T[] array(int n) {
        T_vim_append_digit_long__out_T[] a = new T_vim_append_digit_long__out_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_vim_append_digit_long__out_T();
        }
        return a;
    }
}
