// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_visualinfo_T implements Struct<T_visualinfo_T> {
    final T_pos_T vi_start = new T_pos_T();
    final T_pos_T vi_end = new T_pos_T();
    int vi_mode;
    int vi_curswant;

    public T_visualinfo_T set(T_visualinfo_T o$) {
        vi_start.set(o$.vi_start);
        vi_end.set(o$.vi_end);
        vi_mode = o$.vi_mode;
        vi_curswant = o$.vi_curswant;
        return this;
    }

    T_visualinfo_T copy() {
        return new T_visualinfo_T().set(this);
    }

    public T_visualinfo_T zero() {
        return set(new T_visualinfo_T());
    }

    static T_visualinfo_T[] array(int n) {
        T_visualinfo_T[] a = new T_visualinfo_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_visualinfo_T();
        }
        return a;
    }
}
