// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_winlinevars_T implements Struct<T_winlinevars_T> {
    int draw_state;
    long lnum;
    int startrow;
    int row;
    int screen_row;
    long vcol;
    int col;
    int vcol_off_tp;
    int eol_hl_off;
    int off;
    int win_attr;
    int line_attr;
    int screen_line_flags;
    final int[] fromcol = new int[1];
    final int[] tocol = new int[1];
    int char_attr;
    int n_extra;
    BytePtr p_extra;
    BytePtr p_extra_free;
    int extra_attr;
    int n_attr_skip;
    int c_extra;
    int c_final;
    int extra_for_textprop;
    int saved_n_extra;
    BytePtr saved_p_extra;
    BytePtr saved_p_extra_free;
    int saved_extra_attr;
    int saved_n_attr_skip;
    int saved_extra_for_textprop;
    int saved_c_extra;
    int saved_c_final;
    int saved_char_attr;
    final byte[] extra = new byte[86];
    int filler_lines;

    @Override
    public T_winlinevars_T set(T_winlinevars_T o) {
        draw_state = o.draw_state;
        lnum = o.lnum;
        startrow = o.startrow;
        row = o.row;
        screen_row = o.screen_row;
        vcol = o.vcol;
        col = o.col;
        vcol_off_tp = o.vcol_off_tp;
        eol_hl_off = o.eol_hl_off;
        off = o.off;
        win_attr = o.win_attr;
        line_attr = o.line_attr;
        screen_line_flags = o.screen_line_flags;
        fromcol[0] = o.fromcol[0];
        tocol[0] = o.tocol[0];
        char_attr = o.char_attr;
        n_extra = o.n_extra;
        p_extra = o.p_extra;
        p_extra_free = o.p_extra_free;
        extra_attr = o.extra_attr;
        n_attr_skip = o.n_attr_skip;
        c_extra = o.c_extra;
        c_final = o.c_final;
        extra_for_textprop = o.extra_for_textprop;
        saved_n_extra = o.saved_n_extra;
        saved_p_extra = o.saved_p_extra;
        saved_p_extra_free = o.saved_p_extra_free;
        saved_extra_attr = o.saved_extra_attr;
        saved_n_attr_skip = o.saved_n_attr_skip;
        saved_extra_for_textprop = o.saved_extra_for_textprop;
        saved_c_extra = o.saved_c_extra;
        saved_c_final = o.saved_c_final;
        saved_char_attr = o.saved_char_attr;
        System.arraycopy(o.extra, 0, extra, 0, 86);
        filler_lines = o.filler_lines;
        return this;
    }

    T_winlinevars_T copy() {
        return new T_winlinevars_T().set(this);
    }

    @Override
    public T_winlinevars_T zero() {
        return set(new T_winlinevars_T());
    }

    static T_winlinevars_T[] array(int n) {
        T_winlinevars_T[] a = new T_winlinevars_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_winlinevars_T();
        }
        return a;
    }
}
