// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_winopt_T implements Struct<T_winopt_T> {
    final BytePtr[] wo_wcr = new BytePtr[1];
    final int[] wo_list = new int[1];
    final BytePtr[] wo_lcs = new BytePtr[1];
    final BytePtr[] wo_fcs = new BytePtr[1];
    final int[] wo_nu = new int[1];
    final int[] wo_rnu = new int[1];
    final BytePtr[] wo_ve = new BytePtr[1];
    final int[] wo_ve_flags = new int[1];
    final long[] wo_scr = new long[1];
    final int[] wo_sms = new int[1];
    final int[] wo_wrap = new int[1];
    final long[] wo_siso = new long[1];
    final long[] wo_so = new long[1];
    final long[] wo_sop = new long[1];
    long wo_wrap_flags;
    final BytePtr[] wo_whl = new BytePtr[1];

    @Override
    public T_winopt_T set(T_winopt_T o) {
        wo_wcr[0] = o.wo_wcr[0];
        wo_list[0] = o.wo_list[0];
        wo_lcs[0] = o.wo_lcs[0];
        wo_fcs[0] = o.wo_fcs[0];
        wo_nu[0] = o.wo_nu[0];
        wo_rnu[0] = o.wo_rnu[0];
        wo_ve[0] = o.wo_ve[0];
        wo_ve_flags[0] = o.wo_ve_flags[0];
        wo_scr[0] = o.wo_scr[0];
        wo_sms[0] = o.wo_sms[0];
        wo_wrap[0] = o.wo_wrap[0];
        wo_siso[0] = o.wo_siso[0];
        wo_so[0] = o.wo_so[0];
        wo_sop[0] = o.wo_sop[0];
        wo_wrap_flags = o.wo_wrap_flags;
        wo_whl[0] = o.wo_whl[0];
        return this;
    }

    T_winopt_T copy() {
        return new T_winopt_T().set(this);
    }

    @Override
    public T_winopt_T zero() {
        return set(new T_winopt_T());
    }

    static T_winopt_T[] array(int n) {
        T_winopt_T[] a = new T_winopt_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_winopt_T();
        }
        return a;
    }
}
