// Code generated by `go tool whim skel -java` from a C translation unit; DO NOT EDIT.

package whim.editor;

import whim.rt.*;

final class T_yankreg_T implements Struct<T_yankreg_T> {
    Ptr<T_string_T> y_array;
    long y_size;
    byte y_type;
    int y_width;

    @Override
    public T_yankreg_T set(T_yankreg_T o) {
        y_array = o.y_array;
        y_size = o.y_size;
        y_type = o.y_type;
        y_width = o.y_width;
        return this;
    }

    T_yankreg_T copy() {
        return new T_yankreg_T().set(this);
    }

    @Override
    public T_yankreg_T zero() {
        return set(new T_yankreg_T());
    }

    static T_yankreg_T[] array(int n) {
        T_yankreg_T[] a = new T_yankreg_T[n];
        for (int k = 0; k < n; k++) {
            a[k] = new T_yankreg_T();
        }
        return a;
    }
}
