package whim

import (
	"strings"

	"github.com/arbace/go-whim/crefactor/togo"
)

// What the generator is told about the core it translates to Go:
// editor/crt.go's contract with vim's
// core.  internal/gen hard-coded all of it before -- in skel.go, editor.go,
// gen.go, analyze.go and body_expr.go -- and names none of it now.

// gaGrowInner is ga_grow_inner(): the one function whose body is a rule of the
// runtime's rather than a translation (internal/gen/CONVENTIONS.md,
// Growarrays).  C allocates, copies and clears new_len bytes; GaGrowTo does it
// in elements of the storage's type.
const gaGrowInner = `func ga_grow_inner(gap *S_growarray, n int32) int32 {
	if n < gap.ga_growsize {
		n = gap.ga_growsize
	}

	if n < gap.ga_len/2 {
		n = gap.ga_len / 2
	}

	if n > 0 && usize(gap.ga_len+n) > SIZE_MAX/usize(gap.ga_itemsize) {
		return FAIL
	}
	// C allocates, copies and clears new_len bytes here; GaGrowTo does it
	// in elements of the storage's type.
	gap.ga_maxlen = gap.ga_len + n
	GaGrowTo(gap, int(gap.ga_maxlen))
	return OK
}
`

// gaGrowInnerFor is gaGrowInner with the result type the C gives it: `int`,
// OK and FAIL, until phase 166 made a success bool, and then `bool`, true and
// false.
func gaGrowInnerFor(result string) string {
	if result != "bool" {
		return gaGrowInner
	}
	s := strings.Replace(gaGrowInner, "n int32) int32 {", "n int32) bool {", 1)
	s = strings.ReplaceAll(s, "return FAIL", "return false")
	return strings.ReplaceAll(s, "return OK", "return true")
}

const editorHeader = `// Code generated by go tool whim gen from editor.c; DO NOT EDIT.
//
// editor.go is editor.c -- the core of whim-vim.c, everything above its first
// #include -- in Go, written by a program: internal/gen reads editor.c with
// modernc.org/cc/v4, decides for every C pointer whether it is a plain *T or
// a Ptr[T] that walks, and writes the types, the globals, their initial
// values and every function's body to internal/gen/CONVENTIONS.md.  crt.go is the C
// runtime it is written against; host.go is the host the core calls.
//
// Regenerate with make editor/editor.go (go tool whim gen).

package editor

`

// Gen is what internal/gen is told about editor.c.
var Gen = togo.Profile{
	Header:  editorHeader,
	Package: "editor",
	// The editor as an instance: its state an Editor's fields, the
	// functions reaching it its methods, the receiver `ed`; the hand-written
	// host's state is editorHost, which Editor embeds.  What the hand-written
	// files declare is read from them when the generator runs (cmd/whim gen).
	Instance: &togo.Instance{Type: "Editor", Receiver: "ed", Init: "initGlobals", Embed: "editorHost"},
	// vim's _(), the identity once gettext went; _ is Go's blank.
	Rename: map[string]string{"_": "gettext_"},
	// The C functions editor/crt.go replaces: their calls are translated,
	// their bodies are not (internal/gen/CONVENTIONS.md).
	Runtime: []string{
		"alloc", "alloc_clear", "lalloc", "lalloc_clear",
		"musl_memmove", "musl_memcpy", "musl_memset", "musl_memcmp",
		"ga_grow_inner",
		// the C string functions: editor/libc.go, on Go's byte functions
		"musl_strlen", "musl_strcpy", "musl_strncpy", "musl_strcat",
		"musl_strcmp", "musl_strncmp", "musl_strchr", "musl_strstr",
		"musl_strpbrk",
	},
	// ga_grow_inner()'s body is the one rule of its own: it grows the
	// storage with GaGrowTo, in elements of the storage's type.
	RuntimeBodies: []togo.RuntimeBody{{Name: "ga_grow_inner", Body: gaGrowInnerFor}},
	Allocators:    allocators,
	// vim_free: the garbage collector owns memory, and what is freed walks
	// nothing.
	Frees: []string{"vim_free"},
	Bytes: togo.ByteFuncs{
		Move: []string{"musl_memmove", "musl_memcpy"},
		Set:  "musl_memset",
		Cmp:  "musl_memcmp",
	},
	// size_t, since the core named no libc type.
	SizeType: "usize",
	// garray_T's ga_data, GaData[T] in editor/crt.go.
	GrowArray: togo.GrowArray{Type: "garray_T", Data: "ga_data"},
	// an option's variable, of whatever type.
	Puns: []string{"varp", "varp_arg"},
}
