package p098

// Whim phase 98 -- the character classes, the numbers and the sort.  See GOAL.md.
//
// THE CHARTER SAYS "no musl dependencies in `whim-vim.c` itself".  Phase 97 took the
// strings; this takes everything else that is PURE COMPUTATION -- a function of its
// arguments that asks the operating system nothing -- and defines it in the file, as
// plain C, with no preprocessor and no comment.  Eleven undefined symbols go:
//
// character classes  tolower toupper towlower towupper isalnum iscntrl ispunct
// numbers            atoi atol
// sorting            qsort bsearch
//
// AND `nm -u` IS NOT THE SCOPE, which is the whole reason this phase is bigger than
// that list.  musl spells six more classifiers as FUNCTION-LIKE MACROS in
// <ctype.h> -- `isalpha isdigit isgraph islower isupper`, and `isspace` through
// `__isspace` -- so a source that calls them produces no undefined symbol at all.
// Five of them are live here, at 17 sites, and until they go <ctype.h> cannot.  A
// phase scoped by `nm -u` would look finished and leave phase 99 unable to move.
//
// <wctype.h> HAS A THIRD USER AND IT IS A DEAD STATEMENT.  `iswupper` is named once,
// at the line after `return utf_isupper(c);` inside `vim_isupper` -- the residue of
// whim folding `if (enc_utf8)` to always-true.  gcc drops the unreachable block even
// at -O0, which is why the name is in the source and not in `nm -u`.  It is deleted
// rather than vendored, and that is measured rather than asserted: same file name,
// SOURCE_DATE_EPOCH=0, the binary is BYTE-IDENTICAL either side.
//
// NOTHING IN tools/sweep.sh COVERS AN UNREACHABLE STATEMENT, and that is a gap worth
// naming rather than a thing to fix here.  gcc's -Wunreachable-code has been a no-op
// since gcc 4.5 and is not in -Wall -Wextra; tools/deadsweep.py acts on warnings;
// funcreach.py and typereach.py read DEFINITIONS, and `iswupper` is a libc name with
// no definition in this file.  Measured: `whim-vim.c` holds EIGHTEEN statements that
// cannot run, and exactly ONE of them names a libc symbol.  This phase takes that
// one.  The other seventeen are a phase of their own: three of them are the folded
// Latin-1 arms of these same four functions, and deleting those would orphan
// `latin1flags`, `latin1upper` and `latin1lower` -- which would turn a vendoring
// phase into a cut.
//
// WHY towupper AND towlower ARE THE HARD ONES, and what was measured before choosing.
// Their one live arm each is `if (!(cmp_flags & CMP_INTERNAL)) return towupper(a);`
// inside `utf_toupper`/`utf_tolower`, and `'casemap'` defaults to
// "internal,keepascii" -- so the obvious reading is "unreachable unless the user
// types `:set casemap=`".  THAT READING IS WRONG.  An instrumented build marks 104
// of the 106 records of a full recording, 892 times in one trivial session: the
// caller is `utf_islower`/`utf_isupper` from `buf_init_chartab()`, running BEFORE
// 'casemap' has been applied, with `cmp_flags` still its static zero and arguments
// in exactly 128..255.  They classify the whole Latin-1 range at startup.
//
// FOUR ANSWERS WERE BUILT AND RECORDED.  musl implements them with a two-level
// base-6 packed table (src/ctype/casemap.h, 297 lines) and forty lines of bit
// arithmetic: exact, and the opposite of "obvious, simple, idiomatic C".  Routing
// them to vim's own table instead costs 96 upper and 96 lower codepoints above
// U+00FF and is a declared behaviour change.  An ASCII-only fallback misclassifies
// 62 of 128 Latin-1 bytes at startup and EVERY HARNESS HERE SAYS IT IS FINE, because
// 'isprint' ("@,161-255") and 'iskeyword' ("@,48-57,_,192-255") re-cover the same
// bytes by range -- which is why that one is rejected with a number rather than an
// opinion.  What runs is the fourth: musl's mapping RANGE-COMPRESSED INTO THE SHAPE
// THIS FILE ALREADY HAS, 187 + 171 `convertStruct` rows read by `utf_convert()`, the
// same size as vim's own 198 + 183 and read by the same function.  Exact, and in the
// file's own idiom.
//
// THE TWO DATA FILES WERE NOT REMEMBERED CONSTANTS while the test suite stood
// (448e9a8): musl-case.md's table was generated by `muslcase --generate`, which
// read THIS MACHINE'S libc, and `--verify` re-derived every one of the 1,114,112
// codepoints from the same authority; muslctype compiled musl-ctype.md's
// seventeen functions OUT OF THE SOURCE THIS PHASE PRODUCED and ran them beside
// libc's.  Both tools went with the suite; the data is what they last verified.
//
// THREE ANCHORS AND SIXTEEN COUNTED REWRITES.
//
// A  the seventeen functions and two prototypes, at the END OF THE BLOCK PHASE 97
// STARTED -- between the last #include and the enum wall -- so the file has one
// vendored block and not two.  The anchor is the junction itself, the end of
// `musl_fmtptr` and the first enum.  The prototypes are needed only because the
// two DEAD `return towupper(c);` mentions are rewritten too and sit below.
//
// THE SEVENTEEN USE THE FILE'S TWO-LINE DEFINITION STYLE, and that is mechanical
// rather than cosmetic.  tools/funcreach.py finds a definition with
// `^([A-Za-z_]\w*)\(...\)$` -- the NAME at column 0, which is what
// `    static int` on its own line gives.  Phase 97 wrote one-line headers
// (`static void *musl_memcpy(...)`), and MEASURED, funcreach.py sees 1,719
// definitions on this phase's input, exactly as it did before phase 97 ran: not
// one of its nineteen is in the reachability graph.  Nothing is wrong today --
// the block calls nothing funcreach tracks, and gcc's -Wunused-function still
// covers a dead one -- but a function written that way is outside the sweep, so
// these seventeen are written the way the other 1,719 are.
// B  the two tables and their wrappers, after vim's own `toUpper[]` -- so musl's
// sit beside vim's and `utf_convert()` is already declared above them.
// C  `return iswupper(c);`, deleted.
// D  sixteen call-site rewrites, each counted file-wide, applied ONLY to the text
// after the inserted block so that the block's own bodies are never rewritten.
//
// THE DECLARED DELTA IS NOTHING AT ALL, and it is the third kind of empty
// declaration this pipeline has.  Phase 92's was code that could not run; phase 96's
// was a possibility that had never existed; THIS ONE IS AN EQUALITY -- the code runs
// constantly and computes the same answer, so the evidence is equivalence rather
// than unreachability, and every probe is a MUST-NOT-DIFFER.
// The flags are read out of the boundary's makefile rather than written here a
// second time: the core's compile line is the boundary's (GOALS.md core rule 8).  The
// check needs the binary this phase was HANDED, to run its probes on both sides.

import (
	_ "embed"
	"fmt"
	"io"
	"regexp"
	"strings"

	"github.com/arbace/go-whim/crefactor/edit"
	"github.com/arbace/go-whim/internal/phase"
)

// The two blocks this phase splices in, kept beside it as data (musl-ctype.md,
// musl-case.md): each file's fenced block, byte for byte.
//
//go:embed musl-ctype.md
var muslCtypeMD string

//go:embed musl-case.md
var muslCaseMD string

// fenced is the one fenced block of a data file, byte for byte: everything
// between the opening ```c line and the closing ``` line, its last newline
// included.
func fenced(md string) (string, bool) {
	i := strings.Index(md, "```c\n")
	if i < 0 {
		return "", false
	}
	body := md[i+len("```c\n"):]
	j := strings.Index(body, "\n```\n")
	if j < 0 || strings.Contains(body[j+len("\n```\n"):], "```") {
		return "", false
	}
	return body[:j+1], true
}

func init() { phase.Register("whim98", Edit) }

var w98Before = map[string]int{
	"tolower": 2, "toupper": 2, "towlower": 2, "towupper": 2,
	"isalnum": 2, "iscntrl": 1, "ispunct": 1,
	"isalpha": 3, "isdigit": 7, "isgraph": 1, "islower": 1, "isupper": 5,
	"iswupper": 1, "isspace": 0, "isprint": 0,
	"atoi": 7, "atol": 3, "strtol": 0, "qsort": 1, "bsearch": 4,
	"utf_convert": 4, "sort_strings": 3, "sort_compare": 1,
}

// w98Free are the twenty musl_ names this phase defines.  This file is ONE
// namespace and a silent collision between a tentative definition and a vendored
// one is exactly what CLAUDE.md warns about, so each is required to be free.
var w98Free = []string{"musl_isdigit", "musl_isalpha", "musl_isupper", "musl_islower",
	"musl_isgraph", "musl_isspace", "musl_isalnum", "musl_iscntrl",
	"musl_ispunct", "musl_tolower", "musl_toupper", "musl_atoi",
	"musl_atol", "musl_strtol", "musl_bsearch", "musl_qsort", "musl_towupper",
	"musl_towlower", "musl_toUpper", "musl_toLower"}

// w98Rewrite is the seventeen names rewritten BELOW the inserted block.  How
// many call sites each has is READ from the input: w98Before is the input this
// was written against, and upstream moving one atol to strtol (vim 9.2.1122's
// getdigits) made every count there a refusal of a correct phase.
var w98Rewrite = []string{
	"tolower", "toupper", "towlower", "towupper",
	"isalnum", "iscntrl", "ispunct",
	"isalpha", "isdigit", "isgraph", "islower", "isupper",
	"atoi", "atol", "strtol", "qsort", "bsearch",
}

// w98Provided is everything <ctype.h> and <wctype.h> could still be providing.
var w98Provided = strings.Fields(
	"isalnum isalpha isblank iscntrl isdigit isgraph islower isprint " +
		"ispunct isspace isupper isxdigit isascii toascii tolower toupper " +
		"iswalnum iswalpha iswblank iswcntrl iswdigit iswgraph iswlower " +
		"iswprint iswpunct iswspace iswupper iswxdigit towlower towupper " +
		"towctrans wctrans wctype iswctype")

var w98Dead = regexp.MustCompile(`(?m)^ *return utf_is(?:upper|lower)\(c\);\n *if \(c >= 0x100\)$`)

// Whim98 vendors the character classes, the two ato*, qsort and bsearch.
func Edit(text []byte, w io.Writer) ([]byte, error) {
	nInc := edit.IncludeCount(text) // the headers it was handed (phase 169 drops the unused)
	p := edit.Ph{Tag: "vendor", W: w}
	var err error
	textEdit := func(t []byte, old, new, what string, n int) ([]byte, error) {
		k := strings.Count(string(t), old)
		if k != n {
			return nil, p.Die("%s -- the text occurs %d times, expected %d: %s",
				what, k, n, edit.PyRepr(edit.CoreHead(old, 70)))
		}
		p.Say(what)
		return []byte(strings.ReplaceAll(string(t), old, new)), nil
	}

	// ---- 0. the input's calls, READ ---------------------------------------------
	// iswupper's one call is a fact the phase depends on -- section C deletes
	// exactly that statement -- and so is `isspace` and `isprint` having none.
	calls := map[string]int{}
	var shape []string
	for _, name := range edit.SortedKeys(w98Before) {
		calls[name] = edit.CoreCalls(text, name)
		shape = append(shape, fmt.Sprintf("%s %d", name, calls[name]))
	}
	if calls["iswupper"] != 1 || calls["isspace"] != 0 || calls["isprint"] != 0 {
		return nil, p.Die("iswupper is called %d times, isspace %d and isprint %d: this phase deletes "+
			"the one iswupper and adds nothing for the other two", calls["iswupper"],
			calls["isspace"], calls["isprint"])
	}
	p.Say("the input's calls: " + strings.Join(shape, ", "))

	for _, name := range w98Free {
		if regexp.MustCompile(`\b` + name + `\b`).Match(text) {
			return nil, p.Die("%s already exists in the file", name)
		}
	}
	p.Say("the twenty musl_ names this phase defines are all free")

	// ---- THE INVARIANT, COMPUTED BEFORE ANYTHING IS INSERTED ------------------
	if k := len(w98Dead.FindAll(text, -1)); k != 2 {
		return nil, p.Die("the two dead `if (c >= 0x100)` arms of vim_isupper/vim_islower are not "+
			"where this phase found them (%d)", k)
	}
	p.Say("vim_isupper and vim_islower still open with `return utf_is*(c);` followed by an " +
		"unreachable `if (c >= 0x100)` -- which is the shape that makes iswupper a name " +
		"in the source and not a symbol in the object")

	// ---- A. the eighteen functions, after NGETTEXT ---------------------------
	block, ok := fenced(muslCtypeMD)
	if !ok {
		return nil, p.Die("musl-ctype.md does not hold exactly one fenced block")
	}
	// THE BLOCK JOINS PHASE 97'S RATHER THAN STARTING A SECOND ONE, so the anchor
	// is that JUNCTION -- the end of its last definition and the first enum --
	// and not a line of its own.
	const w98Tail = "    dest[18] = '\\0';\n    return 18;\n}\n"
	const w98Wall = "\nenum { BH_DIRTY = 1 };\n"
	if text, err = textEdit(text, w98Tail+w98Wall, w98Tail+block+w98Wall,
		"the eighteen functions go at the END OF PHASE 97's BLOCK, before the "+
			"enum wall -- one vendored block and not two -- defined before every "+
			"use, so only the two dead tow* mentions need a prototype", 1); err != nil {
		return nil, err
	}

	// ---- B. the two tables, beside vim's own ----------------------------------
	caseB, ok := fenced(muslCaseMD)
	if !ok {
		return nil, p.Die("musl-case.md does not hold exactly one fenced block")
	}
	const w98ToUpperEnd = "    {0x1e922, 0x1e943, 1, -34},\n};\n"
	if text, err = textEdit(text, w98ToUpperEnd, w98ToUpperEnd+caseB,
		"musl's case mapping as 187 + 171 convertStruct rows, after vim's own "+
			"toUpper[] -- the same shape, the same size, and read by the "+
			"utf_convert() that is already declared above them", 1); err != nil {
		return nil, err
	}

	// ---- C. the dead statement ------------------------------------------------
	if text, err = textEdit(text, "            return iswupper(c);\n", "",
		"vim_isupper's `return iswupper(c);`, which cannot run and is "+
			"<wctype.h>'s last user besides the two this phase vendors -- deleting "+
			"it is byte-identical, measured with SOURCE_DATE_EPOCH=0", 1); err != nil {
		return nil, err
	}

	// ---- D. the call sites, counted, and only BELOW the block -----------------
	// The rewrites are applied to the text AFTER the inserted functions so that
	// the block's own bodies -- musl_ispunct calls musl_isalnum, musl_atoi calls
	// musl_isdigit -- are never themselves rewritten.  A file-wide regex would
	// have turned musl_tolower's Body into musl_musl_tolower.
	cut := strings.Index(string(text), block) + len(block)
	head, Body := string(text[:cut]), string(text[cut:])
	total := 0
	for _, r := range w98Rewrite {
		var idx [][]int
		for _, m := range edit.CoreCallRe(r).FindAllStringIndex(Body, -1) {
			if m[0] > 0 && edit.IsWordByte(Body[m[0]-1]) {
				continue
			}
			idx = append(idx, m)
		}
		if len(idx) != calls[r] {
			return nil, p.Die("%s is called %d times below the inserted block, and %d times in the input",
				r, len(idx), calls[r])
		}
		total += len(idx)
		// ONE PASS over the original text, in order, because a span is an OFFSET
		// and every offset after a replacement is wrong -- CLAUDE.md's rule, and
		// the reason whim106 left five of 437 size_t behind when it was two.
		var Out strings.Builder
		prev := 0
		for _, m := range idx {
			// THE WHOLE MATCH IS REPLACED, not prefixed.  The Python writes
			// `re.sub(r'name\s*\(', 'musl_name(')`, so a call written
			// `isupper (c)` loses its space; keeping the matched text and
			// prefixing it leaves `musl_isupper (c)`, which is the same program
			// and a different file -- measured, 6 lines of the tree.
			Out.WriteString(Body[prev:m[0]])
			Out.WriteString("musl_" + r + "(")
			prev = m[1]
		}
		Out.WriteString(Body[prev:])
		Body = Out.String()
	}
	text = []byte(head + Body)
	p.Say(fmt.Sprintf("seventeen names rewritten at the counts read above -- %d call sites, every one "+
		"of them BELOW the block, so no vendored body rewrites itself", total))
	if k := edit.CoreCalls(text, "strtol"); k != 0 {
		return nil, p.Die("strtol is still called %d times, and <stdlib.h> would keep providing it", k)
	}

	// ---- what the sweep is handed, as a count rather than as trust ------------
	var left []string
	for _, n := range w98Provided {
		if edit.CoreCalls(text, n) > 0 {
			left = append(left, n)
		}
	}
	if len(left) > 0 {
		return nil, p.Die("<ctype.h>/<wctype.h> still has a user and phase 99 could not remove it: %s",
			strings.Join(left, " "))
	}
	for _, tn := range []string{"wint_t", "wctype_t", "wctrans_t"} {
		if regexp.MustCompile(`\b` + tn + `\b`).Match(text) {
			return nil, p.Die("%s is still named, and it is <wctype.h>'s", tn)
		}
	}
	p.Say("nothing <ctype.h> or <wctype.h> provides is called anywhere, and no wint_t, " +
		"wctype_t or wctrans_t is named -- which is the contract phase 99 removes the " +
		"two headers on, asserted here so that a miss fails THIS phase")
	if edit.CoreCalls(text, "iswupper") > 0 || regexp.MustCompile(`\biswupper\b`).Match(text) {
		return nil, p.Die("iswupper survives")
	}
	var directives, bad []string
	for _, l := range strings.Split(string(text), "\n") {
		if strings.HasPrefix(l, "#") {
			directives = append(directives, l)
			if !strings.HasPrefix(l, "#include <") {
				bad = append(bad, l)
			}
		}
	}
	if len(directives) != nInc || len(bad) > 0 {
		return nil, p.Die("the directives are no longer 18 #includes of a system header: %d, %s",
			len(directives), strings.Join(bad, " "))
	}
	p.Say("18 directives, every one an #include of a system header -- this phase adds no " +
		"preprocessor and removes none; the two it makes unnecessary are phase 99's")
	return text, nil
}
