// Code generated by "stringer -output stringer.go -linecomment -type=tokCh,Kind,Linkage,StorageDuration"; DO NOT EDIT.

package cc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ADDASSIGN-57345]
	_ = x[ALIGNAS-57346]
	_ = x[ALIGNOF-57347]
	_ = x[ANDAND-57348]
	_ = x[ANDASSIGN-57349]
	_ = x[ARROW-57350]
	_ = x[ASM-57351]
	_ = x[ATOMIC-57352]
	_ = x[ATTRIBUTE-57353]
	_ = x[AUTO-57354]
	_ = x[AUTOTYPE-57355]
	_ = x[BF16-57356]
	_ = x[BOOL-57357]
	_ = x[BREAK-57358]
	_ = x[CASE-57359]
	_ = x[CHAR-57360]
	_ = x[CHARCONST-57361]
	_ = x[COMPLEX-57362]
	_ = x[CONST-57363]
	_ = x[CONTINUE-57364]
	_ = x[DDD-57365]
	_ = x[DEC-57366]
	_ = x[DECIMAL128-57367]
	_ = x[DECIMAL32-57368]
	_ = x[DECIMAL64-57369]
	_ = x[DECLSPEC-57370]
	_ = x[DEFAULT-57371]
	_ = x[DIVASSIGN-57372]
	_ = x[DO-57373]
	_ = x[DOUBLE-57374]
	_ = x[ELSE-57375]
	_ = x[ENUM-57376]
	_ = x[EQ-57377]
	_ = x[EXTERN-57378]
	_ = x[FLOAT-57379]
	_ = x[FLOAT128-57380]
	_ = x[FLOAT128X-57381]
	_ = x[FLOAT16-57382]
	_ = x[FLOAT32-57383]
	_ = x[FLOAT32X-57384]
	_ = x[FLOAT64-57385]
	_ = x[FLOAT64X-57386]
	_ = x[FLOATCONST-57387]
	_ = x[FOR-57388]
	_ = x[GENERIC-57389]
	_ = x[GEQ-57390]
	_ = x[GOTO-57391]
	_ = x[HEADER_NAME-57392]
	_ = x[IDENTIFIER-57393]
	_ = x[IF-57394]
	_ = x[IMAG-57395]
	_ = x[IMAGINARY-57396]
	_ = x[INC-57397]
	_ = x[INLINE-57398]
	_ = x[INT-57399]
	_ = x[INT128-57400]
	_ = x[INTCONST-57401]
	_ = x[LABEL-57402]
	_ = x[LEQ-57403]
	_ = x[LONG-57404]
	_ = x[LONGCHARCONST-57405]
	_ = x[LONGSTRINGLITERAL-57406]
	_ = x[LSH-57407]
	_ = x[LSHASSIGN-57408]
	_ = x[MODASSIGN-57409]
	_ = x[MULASSIGN-57410]
	_ = x[NEQ-57411]
	_ = x[NONNULL-57412]
	_ = x[NORETURN-57413]
	_ = x[ORASSIGN-57414]
	_ = x[OROR-57415]
	_ = x[PPNUMBER-57416]
	_ = x[PPPASTE-57417]
	_ = x[REAL-57418]
	_ = x[REGISTER-57419]
	_ = x[RESTRICT-57420]
	_ = x[RETURN-57421]
	_ = x[RSH-57422]
	_ = x[RSHASSIGN-57423]
	_ = x[SHORT-57424]
	_ = x[SIGNED-57425]
	_ = x[SIZEOF-57426]
	_ = x[STATIC-57427]
	_ = x[STATICASSERT-57428]
	_ = x[STRINGLITERAL-57429]
	_ = x[STRUCT-57430]
	_ = x[SUBASSIGN-57431]
	_ = x[SWITCH-57432]
	_ = x[THREADLOCAL-57433]
	_ = x[TYPEDEF-57434]
	_ = x[TYPENAME-57435]
	_ = x[TYPEOF-57436]
	_ = x[UINT128-57437]
	_ = x[UNION-57438]
	_ = x[UNSIGNED-57439]
	_ = x[VOID-57440]
	_ = x[VOLATILE-57441]
	_ = x[WHILE-57442]
	_ = x[XORASSIGN-57443]
}

const _tokCh_name = "'+=''_Alignas''_Alignof''&&''&=''->''__asm__''_Atomic''__attribute__''auto''__auto_type''__bf16''_Bool''break''case''char'character constant'_Complex''const''continue''...''--''_Decimal128''_Decimal32''_Decimal64''__declspec''default''/=''do''double''else''enum''==''extern''float''_Float128''_Float128x''_Float16''_Float32''_Float32x''_Float64''_Float64x'floating point constant'for''_Generic''>=''goto'<header-name>identifier'if''__imag__''_Imaginary''++''inline''int''__int128'integer constant'__label__''<=''long'long character constantlong string literal'<<''<<=''%=''*=''!=''_Nonnull''_Noreturn''|=''||'preprocessing number'##''__real__''register''restrict''return''>>''>>=''short''signed''sizeof''static'_Static_assertstring literal'struct''-=''switch''_Thread_local''typedef'type name'typeof''__uint128_t''union''unsigned''void''volatile''while''^='"

var _tokCh_index = [...]uint16{0, 4, 14, 24, 28, 32, 36, 45, 54, 69, 75, 88, 96, 103, 110, 116, 122, 140, 150, 157, 167, 172, 176, 189, 201, 213, 225, 234, 238, 242, 250, 256, 262, 266, 274, 281, 292, 304, 314, 324, 335, 345, 356, 379, 384, 394, 398, 404, 417, 427, 431, 441, 453, 457, 465, 470, 480, 496, 507, 511, 517, 540, 559, 563, 568, 572, 576, 580, 590, 601, 605, 609, 629, 633, 643, 653, 663, 671, 675, 680, 687, 695, 703, 711, 725, 739, 747, 751, 759, 774, 783, 792, 800, 813, 820, 830, 836, 846, 853, 857}

func (i tokCh) String() string {
	idx := int(i) - 57345
	if i < 57345 || idx >= len(_tokCh_index)-1 {
		return "tokCh(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokCh_name[_tokCh_index[idx]:_tokCh_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidKind-0]
	_ = x[Array-1]
	_ = x[BFloat16-2]
	_ = x[Bool-3]
	_ = x[Char-4]
	_ = x[ComplexChar-5]
	_ = x[ComplexDouble-6]
	_ = x[ComplexFloat-7]
	_ = x[ComplexFloat16-8]
	_ = x[ComplexInt-9]
	_ = x[ComplexLong-10]
	_ = x[ComplexLongDouble-11]
	_ = x[ComplexLongLong-12]
	_ = x[ComplexShort-13]
	_ = x[ComplexUInt-14]
	_ = x[ComplexUShort-15]
	_ = x[Decimal128-16]
	_ = x[Decimal32-17]
	_ = x[Decimal64-18]
	_ = x[Double-19]
	_ = x[Enum-20]
	_ = x[Float-21]
	_ = x[Float128-22]
	_ = x[Float128x-23]
	_ = x[Float16-24]
	_ = x[Float32-25]
	_ = x[Float32x-26]
	_ = x[Float64-27]
	_ = x[Float64x-28]
	_ = x[Function-29]
	_ = x[Int-30]
	_ = x[Int128-31]
	_ = x[Long-32]
	_ = x[LongDouble-33]
	_ = x[LongLong-34]
	_ = x[Ptr-35]
	_ = x[SChar-36]
	_ = x[Short-37]
	_ = x[Struct-38]
	_ = x[UChar-39]
	_ = x[UInt-40]
	_ = x[UInt128-41]
	_ = x[ULong-42]
	_ = x[ULongLong-43]
	_ = x[UShort-44]
	_ = x[Union-45]
	_ = x[Void-46]
	_ = x[maxKind-47]
}

const _Kind_name = "InvalidKindarray__bf16_Boolchar_Complex char_Complex double_Complex float_Complex _Float16_Complex int_Complex long_Complex long double_Complex long long_Complex short_Complex unsigned_Complex unsigned short_Decimal128_Decimal32_Decimal64doubleenumfloat_Float128_Float128x_Float16_Float32_Float32x_Float64_Float64xfunctionint__int128longlong doublelong longpointersigned charshortstructunsigned charunsignedunsigned __int128unsigned longunsigned long longunsigned shortunionvoidmaxKind"

var _Kind_index = [...]uint16{0, 11, 16, 22, 27, 31, 44, 59, 73, 90, 102, 115, 135, 153, 167, 184, 207, 218, 228, 238, 244, 248, 253, 262, 272, 280, 288, 297, 305, 314, 322, 325, 333, 337, 348, 357, 364, 375, 380, 386, 399, 407, 424, 437, 455, 469, 474, 478, 485}

func (i Kind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Kind_index)-1 {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[idx]:_Kind_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[External-0]
	_ = x[Internal-1]
	_ = x[None-2]
}

const _Linkage_name = "ExternalInternalNone"

var _Linkage_index = [...]uint8{0, 8, 16, 20}

func (i Linkage) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Linkage_index)-1 {
		return "Linkage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Linkage_name[_Linkage_index[idx]:_Linkage_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Static-0]
	_ = x[Automatic-1]
	_ = x[Allocated-2]
}

const _StorageDuration_name = "StaticAutomaticAllocated"

var _StorageDuration_index = [...]uint8{0, 6, 15, 24}

func (i StorageDuration) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StorageDuration_index)-1 {
		return "StorageDuration(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageDuration_name[_StorageDuration_index[idx]:_StorageDuration_index[idx+1]]
}
