package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// runGocat writes a Go package's files as one file on stdout: one package
// clause, one import block merged from all of them, then each file's
// declarations with their comments, in the files' order.  A package is free
// to be one file; this is what lets a tool that works a file at a time --
// go-lisp's go2lisp (doc/GO-LISP.md) -- see the whole package.
//
//	whim gocat <dir>
//
// Test files and files with a build constraint are left out, and so is a
// file of another package.
func runGocat(args []string) int {
	if len(args) != 1 {
		fmt.Fprintln(os.Stderr, "usage: whim gocat <dir>")
		return 2
	}
	out, err := gocat(args[0])
	if err != nil {
		fmt.Fprintf(os.Stderr, "whim gocat: %v\n", err)
		return 1
	}
	os.Stdout.Write(out)
	return 0
}

func gocat(dir string) ([]byte, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)
	pkg := ""
	imports := map[string]bool{} // each spec as written: `"path"` or `name "path"`
	var bodies bytes.Buffer
	for _, path := range paths {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		fs := token.NewFileSet()
		f, err := parser.ParseFile(fs, path, src, parser.ParseComments|parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		off := func(p token.Pos) int { return fs.Position(p).Offset }
		if bytes.Contains(src[:off(f.Package)], []byte("//go:build")) {
			continue
		}
		switch {
		case pkg == "":
			pkg = f.Name.Name
		case f.Name.Name != pkg:
			continue
		}
		for _, is := range f.Imports {
			spec := is.Path.Value
			if is.Name != nil {
				spec = is.Name.Name + " " + spec
			}
			imports[spec] = true
		}
		// the declarations start after the package clause and the imports;
		// every comment among them comes with them
		from := off(f.Name.End())
		for _, d := range f.Decls {
			if g, ok := d.(*ast.GenDecl); ok && g.Tok == token.IMPORT {
				from = off(g.End())
			}
		}
		fmt.Fprintf(&bodies, "\n// ---- %s ----\n", filepath.Base(path))
		if f.Doc != nil {
			// the file's own doc, above its package clause, goes with it
			bodies.WriteString("\n" + string(src[off(f.Doc.Pos()):off(f.Doc.End())]) + "\n")
		}
		bodies.Write(bytes.TrimLeft(src[from:], "\n"))
	}
	if pkg == "" {
		return nil, fmt.Errorf("%s holds no Go package", dir)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by go tool whim gocat %s; DO NOT EDIT.\n\npackage %s\n", dir, pkg)
	if len(imports) > 0 {
		var is []string
		for i := range imports {
			is = append(is, i)
		}
		sort.Strings(is)
		b.WriteString("\nimport (\n")
		for _, i := range is {
			b.WriteString("\t" + i + "\n")
		}
		b.WriteString(")\n")
	}
	b.Write(bodies.Bytes())
	return format.Source(b.Bytes())
}
