package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"
)

// gaGrowInner is ga_grow_inner(): the one function whose body is a rule of the
// runtime's rather than a translation (tx/CONVENTIONS.md, Growarrays).  C
// allocates, copies and clears new_len bytes; GaGrowTo does it in elements of
// the storage's type.
const gaGrowInner = `func ga_grow_inner(gap *S_growarray, n int32) int32 {
	if n < gap.ga_growsize {
		n = gap.ga_growsize
	}

	if n < gap.ga_len/2 {
		n = gap.ga_len / 2
	}

	if n > 0 && usize(gap.ga_len+n) > SIZE_MAX/usize(gap.ga_itemsize) {
		return FAIL
	}
	// C allocates, copies and clears new_len bytes here; GaGrowTo does it
	// in elements of the storage's type.
	gap.ga_maxlen = gap.ga_len + n
	GaGrowTo(gap, int(gap.ga_maxlen))
	return OK
}
`

const editorHeader = `// Code generated by tx/skel from editor.c; DO NOT EDIT.
//
// editor.go is editor.c -- the core of whim-vim.c, everything above its first
// #include -- in Go, written by a program: tx/skel reads editor.c with
// modernc.org/cc/v4, decides for every C pointer whether it is a plain *T or
// a Ptr[T] that walks, and writes the types, the globals, their initial
// values and every function's body to tx/CONVENTIONS.md.  crt.go is the C
// runtime it is written against; host.go is the host the core calls.
//
// Regenerate with tx/gen.sh.  Measured: the core delta accepts a build of
// editor/ exactly as the phase it follows declares.

package main

`

// writeEditor writes editor.go whole, and refuses if any function or initial
// value has no rule.
func (g *gen) writeEditor(path string, skip map[string]bool) error {
	body, report := g.bodies(skip)
	if report != "" {
		return fmt.Errorf("functions the emitter cannot write:\n%s", report)
	}
	inits, failed := g.initializers()
	if len(failed) > 0 {
		return fmt.Errorf("initial values the emitter cannot write:\n%s", strings.Join(failed, "\n"))
	}
	var b strings.Builder
	b.WriteString(editorHeader)
	b.WriteString(strings.TrimPrefix(g.typesText(), "package main\n\n"))
	b.WriteString("\n")
	b.WriteString(strings.TrimPrefix(g.globalsText(), "package main\n\n"))
	b.WriteString("\n// The initial values of the file-scope objects and the hoisted statics whose\n// C initializer is not all zeros.\nfunc init() {\n")
	b.WriteString(inits)
	b.WriteString("}\n\n")
	b.WriteString(gaGrowInner + "\n")
	b.WriteString(body)
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("the generated file is not Go: %v", err)
	}
	return os.WriteFile(path, src, 0o644)
}
