package p126

// The arguments of every swap() and cut() internal/phase/126/edit.go makes, in source
// order, EXTRACTED from the heredoc by an AST walk rather than retyped.  They
// are blocks of C carrying blank lines and 200-column statements, and a changed
// byte in one is invisible to the compile and to a filtered read alike -- which
// is tools/gocmp/genlits.py's rule, applied to single-line literals too because
// the rule is about retyping and not about newlines.
const (
	w126s0Old   = "typedef struct block_hdr bhdr_T;\n\ntypedef struct memfile memfile_T;\n\ntypedef long blocknr_T;\n\ntypedef struct mf_hashitem_S mf_hashitem_T;\n\nstruct mf_hashitem_S\n{\n    mf_hashitem_T *mhi_next;\n    mf_hashitem_T *mhi_prev;\n    blocknr_T mhi_key;\n};\n\nenum { MHT_INIT_SIZE = 64 };\n\ntypedef struct mf_hashtab_S\n{\n    long_u mht_mask;\n    long_u mht_count;\n    mf_hashitem_T **mht_buckets;\n    mf_hashitem_T *mht_small_buckets[MHT_INIT_SIZE];\n    char mht_fixed;\n} mf_hashtab_T;\n\nstruct block_hdr\n{\n    mf_hashitem_T bh_hashitem;\n    bhdr_T *bh_next;\n    bhdr_T *bh_prev;\n    char_u *bh_data;\n    int bh_page_count;\n    char bh_flags;\n};\n"
	w126s0New   = "typedef struct block_hdr    bhdr_T;\ntypedef struct memfile      memfile_T;\n\nstruct block_hdr\n{\n    bhdr_T      *bh_next;\n    bhdr_T      *bh_prev;\n    char_u      *bh_data;\n\n    char        bh_flags;\n};\n"
	w126s0What  = "the block header and the hash types"
	w126s0Why   = "a block header carries a hash item and a page count, and this phase leaves it carrying two links, a page and a lock bit"
	w126s1Old   = "struct memfile\n{\n    bhdr_T *mf_free_first;\n    bhdr_T *mf_used_first;\n    bhdr_T *mf_used_last;\n    mf_hashtab_T mf_hash;\n    blocknr_T mf_blocknr_max;\n    unsigned mf_page_size;\n};"
	w126s1New   = "struct memfile\n{\n    bhdr_T      *mf_used_first;\n    unsigned    mf_page_size;\n};"
	w126s1What  = "the memfile"
	w126s1Why   = "it is a free list, a used list, a hash and a counter, and this phase leaves it a used list and a page size"
	w126s2Old   = "typedef struct info_pointer\n{\n    blocknr_T ip_bnum;"
	w126s2New   = "typedef struct info_pointer\n{\n    bhdr_T      *ip_block;"
	w126s2What  = "the stack entry's block"
	w126s2Why   = "a stack entry remembers the block it came down through"
	w126s3Old   = "struct pointer_entry\n{\n    blocknr_T pe_bnum;\n    linenr_T pe_line_count;\n    int pe_page_count;\n};"
	w126s3New   = "struct pointer_entry\n{\n    bhdr_T      *pe_block;\n    linenr_T    pe_line_count;\n};"
	w126s3What  = "the pointer entry"
	w126s3Why   = "a pointer entry is a child and the number of lines under it"
	w126s4Old   = "    linenr_T ml_line_count;\n    memfile_T *ml_mfp;\n"
	w126s4New   = "    linenr_T    ml_line_count;\n\n    memfile_T   *ml_mfp;\n    bhdr_T      *ml_root;\n"
	w126s4What  = "the memline"
	w126s4Why   = "the root is the one block no descent can reach, so it is named"
	w126s5Old   = "    mfp->mf_free_first = nullptr;\n    mfp->mf_used_first = nullptr;\n    mfp->mf_used_last = nullptr;\n    mf_hash_init(&mfp->mf_hash);\n    mfp->mf_page_size = MEMFILE_PAGE_SIZE;\n    mfp->mf_blocknr_max = 0;\n"
	w126s5New   = "    mfp->mf_used_first = nullptr;\n    mfp->mf_page_size = MEMFILE_PAGE_SIZE;\n"
	w126s5What  = "mf_open()'s body"
	w126s5Why   = "it initialises what the memfile no longer has"
	w126s6Old   = "    while (mfp->mf_free_first != nullptr)\n    {\n        vim_free(mf_rem_free(mfp));\n    }\n    mf_hash_free(&mfp->mf_hash);\n    vim_free(mfp);"
	w126s6New   = "    vim_free(mfp);"
	w126s6What  = "mf_close()'s tail"
	w126s6Why   = "it drains a free list and frees a bucket array that are both gone.  The loop above it, which frees every block on the USED list, is untouched -- and it is now the only one, because mf_free() releases a block outright"
	w126s7Old   = "mf_new(memfile_T *mfp, int page_count)\n{\n    bhdr_T *hp;\n    bhdr_T *freep;\n    char_u *p;\n    hp = nullptr;\n    freep = mfp->mf_free_first;\n    if (freep != nullptr && freep->bh_page_count >= page_count)\n    {\n        if (freep->bh_page_count > page_count)\n        {\n            if (hp == nullptr && (hp = mf_alloc_bhdr(mfp, page_count)) == nullptr)\n            {\n                return nullptr;\n            }\n            hp->bh_hashitem.mhi_key = freep->bh_hashitem.mhi_key;\n            freep->bh_hashitem.mhi_key += page_count;\n            freep->bh_page_count -= page_count;\n        }\n        else if (hp == nullptr)\n        {\n            if ((p = alloc((usize)mfp->mf_page_size * page_count)) == nullptr)\n            {\n                return nullptr;\n            }\n            hp = mf_rem_free(mfp);\n            hp->bh_data = p;\n        }\n        else\n        {\n            freep = mf_rem_free(mfp);\n            hp->bh_hashitem.mhi_key = freep->bh_hashitem.mhi_key;\n            vim_free(freep);\n        }\n    }\n    else\n    {\n        if (hp == nullptr && (hp = mf_alloc_bhdr(mfp, page_count)) == nullptr)\n        {\n            return nullptr;\n        }\n        hp->bh_hashitem.mhi_key = mfp->mf_blocknr_max;\n        mfp->mf_blocknr_max += page_count;\n    }\n    hp->bh_flags = BH_LOCKED;\n    hp->bh_page_count = page_count;\n    mf_ins_used(mfp, hp);\n    mf_ins_hash(mfp, hp);\n"
	w126s7New   = "mf_new(memfile_T *mfp, int page_count)\n{\n    bhdr_T      *hp;\n\n    if ((hp = mf_alloc_bhdr(mfp, page_count)) == nullptr)\n    {\n        return nullptr;\n    }\n    hp->bh_flags = BH_LOCKED;\n    mf_ins_used(mfp, hp);\n"
	w126s7What  = "mf_new()"
	w126s7Why   = "three of its four arms split, adopt or reuse a block from the free list by BLOCK-NUMBER ARITHMETIC, and the fourth takes the next number from the counter.  What is left is the allocation all four ended in"
	w126s8Old   = "mf_get(memfile_T *mfp, blocknr_T nr, int page_count)\n{\n    bhdr_T *hp;\n    if (nr >= mfp->mf_blocknr_max || nr < 0)\n    {\n        return nullptr;\n    }\n    hp = mf_find_hash(mfp, nr);\n    if (hp == nullptr)\n    {\n            return nullptr;\n        }\n    else\n    {\n        mf_rem_used(mfp, hp);\n        mf_rem_hash(mfp, hp);\n    }\n    hp->bh_flags |= BH_LOCKED;\n    mf_ins_used(mfp, hp);\n    mf_ins_hash(mfp, hp);\n    return hp;\n}"
	w126s8New   = "mf_get(memfile_T *mfp, bhdr_T *hp)\n{\n    if (hp == nullptr)\n    {\n        return nullptr;\n    }\n\n    mf_rem_used(mfp, hp);\n\n    hp->bh_flags |= BH_LOCKED;\n    mf_ins_used(mfp, hp);\n\n    return hp;\n}"
	w126s8What  = "mf_get()"
	w126s8Why   = "it is the lookup itself.  Both of its ways of failing were ways of failing to RESOLVE a number -- out of range, or absent from the hash -- and the null test that survives is the same shape for a caller: every `goto error_noblock` and every `return FAIL` below it is reached by the same line as before"
	w126s9Old   = "mf_free(memfile_T *mfp, bhdr_T *hp)\n{\n    vim_free(hp->bh_data);\n    mf_rem_hash(mfp, hp);\n    mf_rem_used(mfp, hp);\n    mf_ins_free(mfp, hp);\n}"
	w126s9New   = "mf_free(memfile_T *mfp, bhdr_T *hp)\n{\n    mf_rem_used(mfp, hp);\n    mf_free_bhdr(hp);\n}"
	w126s9What  = "mf_free()"
	w126s9Why   = "it freed the page and kept the header on a free list under its old number, for mf_new() to split or adopt.  With no number to key it by, a released block is released: mf_free_bhdr() is the function that already did exactly this for every block in mf_close()"
	w126c10A    = "    static void\nmf_ins_hash(memfile_T *mfp, bhdr_T *hp)"
	w126c10B    = "    static void\nmf_ins_used(memfile_T *mfp, bhdr_T *hp)"
	w126c10What = "the three hash wrappers"
	w126s11Old  = "    hp->bh_prev = nullptr;\n    if (hp->bh_next == nullptr)\n    {\n        mfp->mf_used_last = hp;\n    }\n    else\n    {\n        hp->bh_next->bh_prev = hp;\n    }\n}"
	w126s11New  = "    hp->bh_prev = nullptr;\n    if (hp->bh_next != nullptr)\n    {\n        hp->bh_next->bh_prev = hp;\n    }\n}"
	w126s11What = "mf_ins_used()'s tail"
	w126s11Why  = "it maintains a tail pointer nothing reads"
	w126s12Old  = "    if (hp->bh_next == nullptr)\n    {\n        mfp->mf_used_last = hp->bh_prev;\n    }\n    else\n    {\n        hp->bh_next->bh_prev = hp->bh_prev;\n    }\n"
	w126s12New  = "    if (hp->bh_next != nullptr)\n    {\n        hp->bh_next->bh_prev = hp->bh_prev;\n    }\n"
	w126s12What = "mf_rem_used()'s head"
	w126s12Why  = "it maintains the same tail pointer"
	w126s13Old  = "    hp->bh_page_count = page_count;\n    return hp;\n}\n"
	w126s13New  = "    return hp;\n}\n"
	w126s13What = "mf_alloc_bhdr()'s page count"
	w126s13Why  = "the header stops carrying a count nothing reads; the argument still sizes the allocation two lines above"
	w126c14A    = "    static void\nmf_ins_free(memfile_T *mfp, bhdr_T *hp)"
	w126c14B    = "typedef struct pointer_block PTR_BL;"
	w126c14What = "the free list and the whole hash implementation"
	w126s15Old  = "    if (hp->bh_hashitem.mhi_key != 0)\n    {\n        iemsg(e_didnt_get_block_nr_zero);\n        goto error;\n    }\n    pp = (PTR_BL *)(hp->bh_data);\n    pp->pb_count = 1;\n    pp->pb_pointer[0].pe_bnum = 1;\n    pp->pb_pointer[0].pe_page_count = 1;\n    pp->pb_pointer[0].pe_line_count = 1;\n    mf_put(hp);\n    if ((hp = ml_new_data(mfp, 1)) == nullptr)\n    {\n        goto error;\n    }\n    if (hp->bh_hashitem.mhi_key != 1)\n    {\n        iemsg(e_didnt_get_block_nr_one);\n        goto error;\n    }\n"
	w126s15New  = "    buf->b_ml.ml_root = hp;\n    pp = (PTR_BL *)(hp->bh_data);\n    pp->pb_count = 1;\n    pp->pb_pointer[0].pe_line_count = 1;\n    mf_put(hp);\n\n    if ((hp = ml_new_data(mfp, 1)) == nullptr)\n    {\n        goto error;\n    }\n    ((PTR_BL *)(buf->b_ml.ml_root->bh_data))->pb_pointer[0].pe_block = hp;\n"
	w126s15What = "ml_open()'s two blocks"
	w126s15Why  = "it made a pointer block and a data block and asserted they came back numbered 0 and 1, then wrote the number 1 into the root entry BEFORE the block existed.  The root is remembered instead, and the entry is filled with the block itself once there is one"
	w126s16Old  = "    buf->b_ml.ml_stack_size = 0;\n"
	w126s16New  = "    buf->b_ml.ml_stack_size = 0;\n    buf->b_ml.ml_root = nullptr;\n"
	w126s16What = "ml_open()'s preamble"
	w126s16Why  = "ml_root joins the fields ml_open() clears before it can fail, so the error path leaves a memline that names no block"
	w126s17Old  = "    linenr_T t;\n    blocknr_T bnum;\n    linenr_T low;"
	w126s17New  = "    linenr_T    t;\n    bhdr_T      *bp;\n    linenr_T low;"
	w126s17What = "ml_find_line()'s cursor"
	w126s17Why  = "the descent carries the block it is about to fetch"
	w126s19Old  = "    bnum = 0;\n    page_count = 1;\n    low = 1;"
	w126s19New  = "    bp = buf->b_ml.ml_root;\n    low = 1;"
	w126s19What = "where a descent starts"
	w126s19Why  = "it started at block number 0 because ml_open() had asserted the root was block 0"
	w126s20Old  = "                bnum = ip->ip_bnum;\n                low = ip->ip_low;"
	w126s20New  = "                bp = ip->ip_block;\n                low = ip->ip_low;"
	w126s20What = "where a descent resumes"
	w126s20Why  = "ML_FIND restarts from the deepest stack entry that still covers the line"
	w126s21Old  = "        if ((hp = mf_get(mfp, bnum, page_count)) == nullptr)"
	w126s21New  = "        if ((hp = mf_get(mfp, bp)) == nullptr)"
	w126s21What = "the descent's fetch"
	w126s21Why  = "it is the lookup this phase removes"
	w126s22Old  = "        ip->ip_bnum = bnum;\n        ip->ip_low = low;"
	w126s22New  = "        ip->ip_block = bp;\n        ip->ip_low = low;"
	w126s22What = "what a descent pushes"
	w126s22Why  = "the stack remembers the block, not its number"
	w126s23Old  = "                bnum = pp->pb_pointer[idx].pe_bnum;\n                page_count = pp->pb_pointer[idx].pe_page_count;\n                high = low - 1;"
	w126s23New  = "                bp = pp->pb_pointer[idx].pe_block;\n                high = low - 1;"
	w126s23What = "the step down"
	w126s23Why  = "the child is the entry itself, and its page count was only ever the argument of the lookup on the line above"
	w126s24Old  = "                vim_snprintf((char *)IObuff, emsg_iobuff_room(), e_line_count_wrong_in_block_nr, bnum);\n                iemsg(iobuff_or(e_line_count_wrong_in_block_nr));"
	w126s24New  = "                iemsg(e_line_count_wrong_in_block);"
	w126s24What = "E323"
	w126s24Why  = "it is the one message in the file that printed a block number.  The arm above it, which reports a line past the end, keeps IObuff and its formatting"
	w126s25Old  = "static char e_line_count_wrong_in_block_nr[] = \"E323: Line count wrong in block %ld\";"
	w126s25New  = "static char e_line_count_wrong_in_block[]  = \"E323: Line count wrong in block\" ;"
	w126s25What = "E323's text"
	w126s25Why  = "the %ld has nothing to print"
	w126s27Old  = "        blocknr_T bnum_left;\n        blocknr_T bnum_right;"
	w126s27New  = "        bhdr_T      *bp_left;\n        bhdr_T      *bp_right;"
	w126s27What = "ml_append_int()'s two labels"
	w126s27Why  = "a split labels the block on each side of it, and a label is now the block"
	w126s28Old  = "        bnum_left = hp_left->bh_hashitem.mhi_key;\n        bnum_right = hp_right->bh_hashitem.mhi_key;\n        page_count_left = hp_left->bh_page_count;\n        page_count_right = hp_right->bh_page_count;\n"
	w126s28New  = "        bp_left = hp_left;\n        bp_right = hp_right;\n"
	w126s28What = "what a data-block split labels its halves with"
	w126s28Why  = "the number and the page count came out of the two block headers"
	w126s29Old  = "                if (hp->bh_hashitem.mhi_key != 0)\n                {\n                    break;\n                }"
	w126s29New  = "                if (hp != buf->b_ml.ml_root)\n                {\n                    break;\n                }"
	w126s29What = "the root test"
	w126s29Why  = "a pointer block that has overflowed is split in two UNLESS it is the root, which must keep its identity because the tree hangs from it.  The test was `is this block number 0`, which was the root only because ml_open() had made it first"
	w126s30Old  = "                pp->pb_pointer[0].pe_bnum = hp_new->bh_hashitem.mhi_key;\n                pp->pb_pointer[0].pe_line_count = buf->b_ml.ml_line_count;\n                pp->pb_pointer[0].pe_page_count = 1;\n"
	w126s30New  = "                pp->pb_pointer[0].pe_block = hp_new;\n                pp->pb_pointer[0].pe_line_count = buf->b_ml.ml_line_count;\n"
	w126s30What = "the root split"
	w126s30Why  = "the root copies itself into a new block and keeps ONE entry pointing at it -- which is why ml_root is set once and never again: the block that is the root is still the root afterwards"
	w126s31Old  = "            bnum_left = hp->bh_hashitem.mhi_key;\n            bnum_right = hp_new->bh_hashitem.mhi_key;\n            page_count_left = 1;\n            page_count_right = 1;\n"
	w126s31New  = "            bp_left = hp;\n            bp_right = hp_new;\n"
	w126s31What = "what a pointer-block split labels its halves with"
	w126s31Why  = "the loop climbs, and each level relabels with the two blocks it has just made"
)

// The three page-count stores, taken by their exact text with the newline and
// indentation before them.  Extracted, not retyped, for whim126lit's own reason.
const (
	w126pc1 = "pp->pb_pointer[pb_idx].pe_page_count = page_count_left;\n"
	w126pc2 = "pp->pb_pointer[pb_idx + 1].pe_page_count = page_count_right;\n"
	w126pc3 = "pp_new->pb_pointer[0].pe_page_count = page_count_right;\n"
)
